Repository kyma-project/telemetry-manager, pull requests merged in 2023-08, with the labels that each got.

#216 Dynatrace integration tutorial
  docs/user/assets/dynatrace-integration-diagram.svg
  docs/user/integration/dynatrace/README.md
  docs/user/integration/dynatrace/sample-app/values.yaml
Labels: size/L, lgtm

#320 Remove the dependency on github.com/prometheus/prometheus
  docs/user/resources/02-logpipeline.md
  go.mod
  go.sum
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
Labels: lgtm, size/XL

#325 Refactor Istio access logs test
  hack/deploy-istio.sh
  test/integration/istio_access_logs_test.go
  test/testkit/k8s/namespace.go
Labels: area/tests, lgtm, size/M

#323 Add Prometheus receiver for scraping annotated services
  config/samples/telemetry_v1alpha1_metricpipeline.yaml
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/relabel_configs.go
  test/e2e/metrics_prometheus_input_test.go
  test/integration/istio_access_logs_test.go
  test/testkit/mocks/custom_metric_provider.go
  test/testkit/mocks/metricproducer/metric_producer.go
  test/testkit/otlp/metrics/metrics.go
Labels: lgtm, size/XL

#332 Add security.md
  SECURITY.md
Labels: lgtm, size/XS

#321 align wording for Telemetry Manager
  docs/user/01-manager.md
  docs/user/README.md
Labels: documentation, lgtm, size/XS, area/documentation, area/telemetry

#334 Ensure mandatory README sections
  README.md
Labels: lgtm, size/S

#335 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/L, lgtm

#341 make links relative again
  README.md
  docs/contributor/assets/e2e-test-suites.png
  docs/contributor/assets/test-pyramid.png
  docs/contributor/governance.md
  docs/contributor/installation.md
  docs/contributor/testing.md
  docs/contributor/troubleshooting.md
  docs/user/01-manager.md
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/integration/dynatrace/README.md
  docs/user/resources/README.md
  docs/user/resources/_sidebar.md
Labels: lgtm, size/M

#343 remove sidebar link
  docs/user/_sidebar.md
Labels: lgtm, size/XS

#342 Refactor tests
  .gitignore
  Makefile
  test/integration/istio/const.go
  test/integration/istio/istio_access_logs_test.go
  test/integration/istio/suite_test.go
  test/testkit/k8s/apiserver/proxy_client.go
  test/testkit/k8s/label_opts.go
  test/testkit/k8s/label_opts_test.go
  test/testkit/k8s/namespace.go
  test/testkit/k8s/objects.go
  test/testkit/k8s/secret.go
  test/testkit/k8s/secret_opts.go
  test/testkit/k8s/service.go
  test/testkit/k8s/telemetry.go
  test/testkit/k8s/verifiers/deployment.go
  test/testkit/kyma/istio/istio.go
  test/testkit/kyma/pipelinelist.go
  test/testkit/kyma/telemetry/log/parser.go
  test/testkit/kyma/telemetry/log/pipeline.go
  test/testkit/kyma/telemetry/metric/pipeline.go
  test/testkit/kyma/telemetry/trace/pipeline.go
  test/testkit/matchers/log_matchers_test.go
  test/testkit/matchers/metric_matchers.go
  test/testkit/matchers/metric_matchers_test.go
  test/testkit/matchers/prometheus_matcher_test.go
  test/testkit/matchers/suite_test.go
  test/testkit/matchers/trace_matchers.go
  test/testkit/matchers/trace_matchers_test.go
  test/testkit/mocks/backend.go
  test/testkit/mocks/backend_config_map.go
  test/testkit/mocks/backend_deployment.go
  test/testkit/mocks/external_backend_service.go
  test/testkit/mocks/log_spammer.go
  test/testkit/mocks/logbackend_config_map.go
  test/testkit/mocks/urlprovider.go
  test/testkit/opts.go
  test/testkit/otlp/metrics/exporter.go
  test/testkit/otlp/metrics/metrics.go
  test/testkit/otlp/traces/traces.go
  test/testkit/port_registry.go
Labels: area/tests, size/L, lgtm

#340 Revert fluent-bit metric exposure
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  test/e2e/logging_fluentbit_metrics_test.go
  test/e2e/logging_parser_test.go
Labels: lgtm, size/M, area/logging

#345 Increase default metric scrape interval to 30 sec
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/receivers.go
Labels: kind/bug, lgtm, size/S, area/telemetry

#344 Release amendments and GitHub Release changelog improvements
  .goreleaser.yaml
  docs/contributor/releasing.md
Labels: lgtm, size/M

#350 Bump module version and images for release 0.9.0
  Makefile
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/S, area/telemetry

#351 update otel-collector, fluent-bit and directory-size-exporter
  Dockerfile
  config/samples/http-mockserver.yaml
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend_deployment.go
Labels: kind/feature, lgtm, area/logging, area/tracing, size/S

#352 added milestone management to the release process
  docs/contributor/releasing.md
Labels: kind/feature, lgtm, size/M, area/documentation

#360 fix: Make insecure flag in tls config optional
  apis/telemetry/v1alpha1/shared_types.go
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/development/telemetry.kyma-project.io_metricpipelines.yaml
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
Labels: lgtm, area/tracing, size/S

#365 chore: Remove the MILV config file
  milv.config.yaml
Labels: lgtm, size/XS

#357 chore: Integrate ConventionalCommits specification support to the SDLC
  .commitlint.js
  .github/dependabot.yml
  .github/workflows/conventional-pr.yml
  .goreleaser.yaml
  docs/contributor/releasing.md
Labels: size/L, lgtm, area/ci

#353 docs: Add HOME and fix link
  apis/telemetry/v1alpha1/logpipeline_types.go
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  docs/user/03-traces.md
  docs/user/_sidebar.md
  docs/user/resources/02-logpipeline.md
Labels: lgtm, area/documentation, size/S

#368 chore: Bump directory-size-exporter to use Golang 1.21.0
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS, area/dependency

#370 chore: Switch ConventionalCommits enforcer to amannn/action-semantic-pull-request
  .commitlint.js
  .github/workflows/conventional-pr.yml
  docs/contributor/releasing.md
Labels: lgtm, size/M, area/ci

#333 feat: Add conditions that reflect status of different Telemetry components
  .golangci.yaml
  apis/operator/v1alpha1/telemetry_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_telemetries.yaml
  controllers/operator/suite_test.go
  controllers/operator/telemetry_controller.go
  controllers/operator/telemetry_controller_test.go
  docs/user/06-conditions.md
  docs/user/resources/01-telemetry.md
  internal/reconciler/logparser/status.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/status.go
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/reconciler/telemetry/metric_components_checker.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/mocks/component_health_checker.go
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/telemetry/status.go
  internal/reconciler/telemetry/status_test.go
  internal/reconciler/telemetry/trace_components_checker.go
  internal/reconciler/telemetry/trace_components_checker_test.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
  internal/testutils/log_pipeline_builder.go
  internal/testutils/metric_pipeline_builder.go
  internal/testutils/trace_pipeline_builder.go
  main.go
Labels: kind/feature, lgtm, size/XXL, area/telemetry

#371 feat: Update references to new name 'TraceGateway' except for Kubernetes resources
  config/dashboards/configmap_opentelemetry_trace_gateway_dashboard.yaml
  config/dashboards/kustomization.yaml
  controllers/telemetry/metricpipeline_controller_test.go
  controllers/telemetry/tracepipeline_controller_test.go
  docs/user/06-conditions.md
  docs/user/assets/telemetry-components.drawio.svg
  internal/reconciler/status.go
  internal/reconciler/telemetry/trace_components_checker_test.go
  internal/reconciler/tracepipeline/status_test.go
  main.go
  test/e2e/README.md
  test/e2e/assets/tracing-tests.svg
  test/e2e/tracing_test.go
Labels: size/L, lgtm

#354 test: Add Istio tracing integration test
  Makefile
  hack/deploy-istio.sh
  test/integration/istio/istio_tracing_test.go
  test/integration/istio/suite_test.go
  test/testkit/k8s/verifiers/pod.go
  test/testkit/matchers/trace_matchers.go
  test/testkit/matchers/trace_matchers_test.go
Labels: area/tests, size/L, lgtm, area/tracing

#383 test: Unify timeouts for Consistently usage
  test/e2e/consts.go
  test/e2e/logging_annotation_test.go
  test/e2e/logging_exclude_container_test.go
  test/e2e/logging_label_test.go
  test/e2e/metrics_test.go
  test/e2e/tracing_test.go
Labels: area/tests, lgtm, size/M

#382 fix: Reconcile webhook while waiting for module deletion
  internal/reconciler/telemetry/reconciler.go
  test/e2e/telemetry_test.go
Labels: kind/bug, lgtm, size/M, area/telemetry
