Repository kyma-project/telemetry-manager, pull requests merged in 2023-04, with the labels that each got.

#115 Refactor Fluent Bit deletion
  internal/kubernetes/utils.go
  internal/reconciler/logpipeline/reconciler.go
Labels: lgtm, size/M

#119 Hardened configuration values for metrics gateway
  internal/reconciler/metricpipeline/config_builder.go
  internal/reconciler/metricpipeline/config_builder_test.go
Labels: lgtm, size/S

#121 Update Otel collector to 0.74.0
  main.go
Labels: lgtm, size/XS

#118 Refactor trace generation in e2e tests
  go.mod
  go.sum
  internal/otelmatchers/matchers.go
  internal/otelmatchers/otlp_json_trace_parser.go
  internal/otelmatchers/testdata/consist_of_spans_with_attributes/full_match.jsonl
  internal/otelmatchers/testdata/consist_of_spans_with_attributes/no_match.jsonl
  internal/otelmatchers/testdata/consist_of_spans_with_attributes/partial_match.jsonl
  internal/otelmatchers/testdata/consist_of_spans_with_ids/full_match.jsonl
  internal/otelmatchers/testdata/consist_of_spans_with_ids/no_match.jsonl
  internal/otelmatchers/testdata/consist_of_spans_with_ids/partial_match.jsonl
  internal/otelmatchers/testdata/consist_of_spans_with_trace_id/full_match.jsonl
  internal/otelmatchers/testdata/consist_of_spans_with_trace_id/no_match.jsonl
  internal/otelmatchers/testdata/consist_of_spans_with_trace_id/partial_match.jsonl
  internal/otelmatchers/trace_matchers.go
  internal/otelmatchers/trace_matchers_test.go
  test/e2e/tracing_test.go
Labels: lgtm, size/XXL

#127 Prepare owner references to support multiple pipelines
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  internal/kubernetes/utils.go
  internal/kubernetes/utils_test.go
Labels: size/L, lgtm

#126 Enhance pipeline lock mechanism
  Makefile
  internal/kubernetes/lock.go
  internal/kubernetes/lock_test.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/resources/otelcollector/resources.go
  main.go
Labels: size/L, lgtm

#131 Set telemetry namespace to default
  main.go
Labels: lgtm, size/XS

#130 update to fluentbit 2.0.11
  Dockerfile
  config/samples/http-mockserver.yaml
Labels: lgtm, size/XS, area/telemetry

#139 Enable unlimited retries in LogPipelines with custom output
  controllers/telemetry/logpipeline_controller_test.go
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/output.go
  internal/fluentbit/config/builder/output_test.go
Labels: lgtm, size/XS

#141 Fix variable name discrepancies in tracing test
  test/e2e/testkit/mocks/traces/external_backend_service.go
  test/e2e/testkit/otlp/traces/traces.go
  test/e2e/testkit/otlp/traces_service.go
  test/e2e/testkit/port_registry.go
  test/e2e/tracing_test.go
Labels: size/L, lgtm

#142 update to otel-collector 0.75.0, update fluentbit to golang 1.20.3
  Dockerfile
  config/samples/http-mockserver.yaml
  main.go
Labels: kind/feature, lgtm, size/XS

#140 Add aliases to otel exporters
  Makefile
  config/manager/kustomization.yaml
  controllers/telemetry/otel_test_helpers.go
  internal/otelcollector/config/builder/config_builder.go
  internal/otelcollector/config/builder/config_builder_test.go
  internal/otelcollector/config/config.go
  internal/reconciler/metricpipeline/config_builder.go
  internal/reconciler/metricpipeline/config_builder_test.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/config_builder.go
  internal/reconciler/tracepipeline/config_builder_test.go
  internal/reconciler/tracepipeline/reconciler.go
Labels: kind/feature, size/L, lgtm

#120 Watches for resources with multiple ownership
  .DS_Store
  controllers/telemetry/errors.go
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/logpipeline_controller_test.go
  internal/kubernetes/utils.go
  internal/kubernetes/utils_test.go
  internal/reconciler/logpipeline/reconciler.go
Labels: kind/bug, size/L, lgtm
