Repository kyma-project/telemetry-manager, pull requests merged in 2023-10, with the labels that each got.

#319 chore: Bump controller-runtime to 0.16.2
  Makefile
  controllers/operator/suite_test.go
  controllers/operator/telemetry_controller.go
  controllers/telemetry/logparser_controller.go
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/metricpipeline_controller_test.go
  controllers/telemetry/suite_test.go
  controllers/telemetry/tracepipeline_controller.go
  controllers/telemetry/tracepipeline_controller_test.go
  go.mod
  go.sum
  internal/kubernetes/mocks/Client.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/telemetry/status_test.go
  internal/reconciler/tracepipeline/status_test.go
  main.go
  webhook/logparser/webhook.go
  webhook/logpipeline/webhook.go
  webhook/logpipeline/webhook_suite_test.go
Labels: lgtm, size/XL

#442 feat: OTel-collector logs in JSON encoding only
  internal/otelcollector/config/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/config_builder.go
  internal/otelcollector/config/trace/gateway/config_builder_test.go
Labels: kind/feature, lgtm, area/monitoring, area/tracing, size/S

#449 chore: Bump otel pkgs (SDKs and exporters)
  .github/dependabot.yml
  go.mod
  go.sum
Labels: lgtm, size/M, area/ci

#435 feat: Deprecate LogParser
  apis/telemetry/v1alpha1/logparser_types.go
  config/busola/kustomization.yaml
  config/busola/logparser_busola_extension_cm.yaml
  config/crd/bases/telemetry.kyma-project.io_logparsers.yaml
  docs/user/02-logs.md
  docs/user/README.md
  docs/user/assets/logs-flow.drawio.svg
  docs/user/resources/03-logparser.md
  docs/user/resources/_sidebar.md
  internal/resources/fluentbit/resources.go
  test/e2e/manager_test.go
  webhook/dryrun/testdata/expected/pipelines/fluent-bit.conf
  webhook/dryrun/testdata/given/fluent-bit-configmap.yaml
Labels: kind/feature, size/L, lgtm, area/logging

#439 feat: LogPipeline HTTP output mTLS support
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/secret_refs.go
  apis/telemetry/v1alpha1/shared_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/development/telemetry.kyma-project.io_metricpipelines.yaml
  controllers/telemetry/logpipeline_controller_test.go
  docs/index.html
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/fluentbit/config/builder/output.go
  internal/fluentbit/config/builder/output_test.go
  internal/otelcollector/config/otlpexporter/config_builder_test.go
  internal/otelcollector/config/otlpexporter/env_vars.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/sync.go
  internal/reconciler/logpipeline/sync_test.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  main.go
  test/e2e/logs_fluentbit_metrics_test.go
  test/e2e/logs_mtls_test.go
  test/testkit/kyma/telemetry/log/pipeline.go
  test/testkit/kyma/telemetry/metric/pipeline.go
  test/testkit/kyma/telemetry/trace/pipeline.go
  test/testkit/mocks/backend/backend.go
  test/testkit/mocks/backend/config_map.go
  test/testkit/mocks/backend/fluentd/config_map.go
  test/testkit/mocks/backend/tls/tls.go
  test/testkit/verifiers/logs.go
Labels: lgtm, size/XXL

#443 chore: Owner reference interceptor
  internal/kubernetes/owner_reference_setter.go
  internal/kubernetes/owner_reference_setter_test.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
Labels: size/L, lgtm

#454 chore: Bump images and module version for 1.1.0 release
  Makefile
  config/manager/kustomization.yaml
  module_config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, area/telemetry, kind/chore

#455 docs: Update docs to follow docsify-tabs syntax
  docs/index.html
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
Labels: lgtm, size/XXL, area/documentation

#457 feat: Remove loggingexporter from gateways
  docs/contributor/performance-tests/metrics/metrics.md
  internal/otelcollector/config/exporters.go
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/config.go
  internal/otelcollector/config/trace/gateway/config_builder.go
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/config_map.go
  test/testkit/mocks/backend/deployment.go
Labels: lgtm, size/M, area/traces

#460 docs: Update metric pipeline KPIs
  docs/user/04-metrics.md
Labels: lgtm, area/documentation, size/S, area/metrics

#456 feat: Manual scaling for trace and metric gateways
  apis/operator/v1alpha1/telemetry_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  config/busola/telemetry_busola_extension_cm.yaml
  config/crd/bases/operator.kyma-project.io_telemetries.yaml
  config/samples/operator_v1alpha1_telemetry.yaml
  controllers/telemetry/errors.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/suite_test.go
  controllers/telemetry/tracepipeline_controller.go
  docs/user/resources/01-telemetry.md
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/resources/otelcollector/gateway/resources.go
  internal/resources/otelcollector/gateway/resources_test.go
  test/e2e/metrics_basic_test.go
  test/e2e/traces_basic_test.go
  test/testkit/kyma/common_names.go
Labels: lgtm, size/XL, area/manager

#463 feat: Update to otel-collector 0.87.0 and fluentbit 2.1.10
  Dockerfile
  config/samples/http-mockserver.yaml
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
  main.go
  sec-scanners-config.yaml
  test/e2e/metrics_runtime_input_test.go
  test/testkit/mocks/backend/deployment.go
Labels: kind/feature, lgtm, size/M, area/logs, area/metrics, area/traces

#467 test: Add gardener integration job
  .github/workflows/markdown-link-check.yml
  .github/workflows/pull-governance.yml
  .github/workflows/push-integration.yml
  Makefile
Labels: area/tests, size/L, lgtm, area/ci, kind/chore

#470 docs: Added new trace troubleshooting symptom
  docs/user/03-traces.md
Labels: documentation, kind/feature, lgtm, size/S, area/traces

#468 feat: Adjust filter to handle istio spans based on OTEL tracer
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/processors.go
  internal/otelcollector/config/trace/gateway/processors_test.go
  test/e2e/traces_noisy_span_filter_test.go
  test/testkit/otlp/traces/helpers.go
Labels: kind/feature, size/L, lgtm, area/traces

#471 feat: Constraint minimal replicas
  apis/operator/v1alpha1/telemetry_types.go
  config/crd/bases/operator.kyma-project.io_telemetries.yaml
  docs/user/resources/01-telemetry.md
  test/e2e/metrics_basic_test.go
  test/e2e/traces_basic_test.go
Labels: lgtm, size/M, area/metrics, area/traces

#477 fix: Fix noisy span filter rule for healthz endpoint
  internal/otelcollector/config/trace/gateway/processors.go
  internal/otelcollector/config/trace/gateway/processors_test.go
  test/testkit/otlp/traces/helpers.go
Labels: lgtm, size/XS

#469 feat: Add metric gateway hardened configuration
  docs/contributor/performance-tests/metrics/metrics.md
  docs/user/04-metrics.md
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/resources/otelcollector/agent/resources.go
Labels: lgtm, size/M, area/documentation, area/metrics

#472 chore: Introduce test targets not requiring k3d
  .github/workflows/pull-governance.yml
  Makefile
Labels: lgtm, size/M, area/ci, kind/chore, area/manager

#478 feat: TLS settings in LogPipeline view
  config/busola/logpipeline_busola_extension_cm.yaml
  webhook/logpipeline/webhook.go
Labels: kind/feature, lgtm, area/logs

#486 fix: Sync secrets for deployable pipelines only.
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/sync.go
  internal/reconciler/logpipeline/sync_test.go
Labels: lgtm, size/M, area/logging, area/telemetry

#484 chore: Release artefacts for experimental channel
  .gitignore
  .goreleaser.yaml
  Makefile
  docs/contributor/releasing.md
  hack/deploy-module.sh
  hack/release.sh
  module-config-dev.yaml
  module-config.yaml
Labels: lgtm, size/M, kind/chore, area/manager

#488 chore: Bump images and module version for 1.2.0 release
  Makefile
  config/manager/kustomization.yaml
  module-config-dev.yaml
  module-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, area/manager

#490 deps: Bump istio module dependency to 1.1.1
  Makefile
Labels: lgtm, size/XS, kind/chore, area/manager

#487 feat: Resolve service.name based on Kubernetes attributes
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/README.md
  internal/otelcollector/config/gatewayprocs/k8s_attribute_proc.go
  internal/otelcollector/config/gatewayprocs/k8s_attribute_proc_test.go
  internal/otelcollector/config/gatewayprocs/resolve_service_name_proc.go
  internal/otelcollector/config/gatewayprocs/resolve_service_name_proc_test.go
  internal/otelcollector/config/gatewayprocs/resource_procs.go
  internal/otelcollector/config/gatewayprocs/resource_procs_test.go
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/processors.go
  internal/otelcollector/config/trace/gateway/config.go
  internal/otelcollector/config/trace/gateway/config_builder.go
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/drop_noisy_spans.go
  internal/otelcollector/config/trace/gateway/processors.go
  internal/otelcollector/config/trace/gateway/processors_test.go
  internal/otelcollector/config/trace/gateway/testdata/config.yaml
  test/e2e/metrics_cumulative_to_delta_test.go
  test/e2e/metrics_service_name_test.go
  test/e2e/traces_service_name_test.go
  test/testkit/k8s/daemon_set.go
  test/testkit/k8s/deployment.go
  test/testkit/k8s/job.go
  test/testkit/k8s/pod.go
  test/testkit/k8s/pod_spec.go
  test/testkit/k8s/stateful_set.go
  test/testkit/mocks/metricproducer/metric_producer.go
  test/testkit/mocks/servicenamebundle/service_name_bundle.go
  test/testkit/mocks/servicenamebundle/telemetry_gen.go
Labels: lgtm, size/XXL

#493 feat: Disable grafana-loki output
  apis/telemetry/v1alpha1/logpipeline_types.go
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  controllers/operator/telemetry_controller_test.go
  controllers/telemetry/logpipeline_controller_test.go
  docs/user/02-logs.md
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  internal/conditions/conditions.go
  internal/fluentbit/config/builder/output.go
  internal/fluentbit/config/builder/output_test.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  main.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/XL, area/logs

#495 test: Fix noisy span filter E2E tests
  test/e2e/traces_noisy_span_filter_test.go
  test/testkit/kyma/common_names.go
  test/testkit/otlp/traces/helpers.go
  test/testkit/verifiers/traces.go
Labels: size/L, lgtm

#497 chore: Bump amannn/action-semantic-pull-request to 5.3.0
  .github/workflows/pull-governance.yml
Labels: lgtm, size/XS, area/ci

#501 chore: Add missing github actions
  .github/workflows/pull-module.yml
  .github/workflows/push-integration.yml
  .github/workflows/slack-message.json
  Makefile
  hack/deploy-module.sh
Labels: size/L, lgtm, area/ci, kind/chore
