Repository kyma-project/telemetry-manager, pull requests merged in 2023-09, with the labels that each got.

#385 fix: Broken docu links in busola extensions
  config/busola/logparser_busola_extension_cm.yaml
  config/busola/logpipeline_busola_extension_cm.yaml
  config/busola/telemetry_busola_extension_cm.yaml
  config/busola/tracepipeline_busola_extension_cm.yaml
Labels: kind/bug, lgtm, area/documentation, size/S

#386 fix: Corrected navigation of module in busola
  config/busola/telemetry_busola_extension_cm.yaml
Labels: kind/bug, lgtm, size/XS, area/documentation

#388 fix: Broken doc links
  apis/telemetry/v1alpha1/logpipeline_types.go
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  docs/contributor/installation.md
  docs/user/resources/02-logpipeline.md
Labels: lgtm, size/XS

#387 chore: Release 0.10.0
  Makefile
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, area/logging, size/XS, area/monitoring, area/tracing, area/telemetry

#391 chore: Update module-name in sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, area/telemetry, kind/chore

#364 feat: Add support for scraping istiofied workloads
  config/rbac/role.yaml
  controllers/telemetry/errors.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/metricpipeline_controller_test.go
  controllers/telemetry/otel_test_helpers.go
  controllers/telemetry/tracepipeline_controller_test.go
  docs/user/04-metrics.md
  go.mod
  go.sum
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/relabel_configs.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
  internal/reconciler/metricpipeline/istio_status_checker.go
  internal/reconciler/metricpipeline/istio_status_checker_test.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/resources/otelcollector/agent/resources.go
  internal/resources/otelcollector/agent/resources_test.go
  internal/resources/otelcollector/core/core.go
  internal/resources/otelcollector/gateway/resources.go
  internal/resources/otelcollector/gateway/resources_test.go
  internal/setup/predicates.go
  main.go
Labels: lgtm, size/XXL, area/telemetry

#395 fix: Relabel configs that drop if scheme is HTTP/HTTPS
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/relabel_configs.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
Labels: lgtm, size/S

#377 test: Check for custom spans in Istio tracing test
  test/integration/istio/istio_tracing_test.go
  test/testkit/matchers/trace_matchers.go
  test/testkit/mocks/metricproducer/metric_producer.go
Labels: area/tests, lgtm, size/M

#398 feat: Show module status in busola view
  config/busola/telemetry_busola_extension_cm.yaml
Labels: kind/feature, lgtm, area/telemetry

#400 fix: Do not fail reconciliation if no deployable pipelines
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
Labels: kind/bug, lgtm, size/S, area/telemetry

#393 feat: Extend the descriptions of manifests
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/shared_types.go
  apis/telemetry/v1alpha1/tracepipeline_types.go
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/development/telemetry.kyma-project.io_metricpipelines.yaml
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
Labels: kind/feature, lgtm, size/XL, area/documentation

#394 chore: Use the new module-config-file flag when creating module
  .gitignore
  .goreleaser.yaml
  Makefile
  docs/contributor/installation.md
  docs/contributor/releasing.md
  hack/deploy-module.sh
  hack/release.sh
  module_config.yaml
Labels: lgtm, size/M, area/telemetry, kind/chore

#384 test: OTEL mTLS E2E Test for TracePipeline and MetricPipeline
  test/e2e/metrics_test.go
  test/e2e/tracing_test.go
  test/testkit/kyma/telemetry/trace/pipeline.go
  test/testkit/mocks/backend/backend.go
  test/testkit/mocks/backend/config_map.go
  test/testkit/mocks/backend/options.go
  test/testkit/tls.go
Labels: lgtm, size/XL

#402 chore: bump envtest k8s version to 1.27.1
  Makefile
Labels: lgtm, size/XS

#399 chore: Update to newest istio module
  Makefile
Labels: lgtm, area/logging, size/XS, area/tracing, area/telemetry

#396 docs: Amend metrics doc + diagrams
  docs/user/04-metrics.md
  docs/user/assets/metrics-arch.drawio.svg
  docs/user/assets/metrics-resources.drawio.svg
  docs/user/assets/traces-arch.drawio.svg
Labels: documentation, lgtm, size/XXL, area/documentation, area/telemetry

#403 chore: Bump images and module version for 1.0.0 release
  Makefile
  config/manager/kustomization.yaml
  module_config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, area/telemetry, kind/chore

#404 chore: Fix logs in secretref package
  internal/secretref/secret_ref.go
Labels: lgtm, size/XS

#392 test: Scrape istiofied workloads
  hack/deploy-istio.sh
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/metrics_runtime_input_test.go
  test/e2e/metrics_test.go
  test/integration/istio/const.go
  test/integration/istio/istio_access_logs_test.go
  test/integration/istio/istio_metric_test.go
  test/integration/istio/istio_tracing_test.go
  test/testkit/matchers/log_matchers.go
  test/testkit/matchers/metric/metric_matchers.go
  test/testkit/matchers/metric/metric_matchers_test.go
  test/testkit/matchers/metric/pmetric_utils.go
  test/testkit/matchers/metric/suite_test.go
  test/testkit/matchers/metric_matchers.go
  test/testkit/matchers/metric_matchers_test.go
  test/testkit/matchers/trace_matchers.go
  test/testkit/matchers/unmarshal.go
  test/testkit/mocks/metricproducer/metric_producer.go
  test/testkit/otlp/metrics/metrics.go
Labels: lgtm, size/XXL

#407 feat: Preserve restartedAt annotation
  internal/kubernetes/utils.go
  internal/kubernetes/utils_test.go
Labels: size/L, lgtm

#405 feat: Reflect blockage of deletion in module status
  apis/operator/v1alpha1/telemetry_types.go
  config/crd/bases/operator.kyma-project.io_telemetries.yaml
  docs/user/06-conditions.md
  docs/user/resources/01-telemetry.md
  internal/reconciler/status.go
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/reconciler/telemetry/metric_components_checker.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/mocks/component_health_checker.go
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/telemetry/status.go
  internal/reconciler/telemetry/status_test.go
  internal/reconciler/telemetry/trace_components_checker.go
  internal/reconciler/telemetry/trace_components_checker_test.go
  internal/testutils/log_parser_builder.go
  main.go
  test/e2e/telemetry_test.go
Labels: kind/feature, lgtm, size/XL, area/telemetry

#421 test: Simplify Mock Backend Creation in E2E test
  test/e2e/consts.go
  test/e2e/logging_annotation_test.go
  test/e2e/logging_dedot_test.go
  test/e2e/logging_exclude_container_test.go
  test/e2e/logging_fluentbit_metrics_test.go
  test/e2e/logging_label_test.go
  test/e2e/logging_log_delivery_test.go
  test/e2e/logging_parser_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/metrics_runtime_input_test.go
  test/e2e/metrics_test.go
  test/e2e/tracing_test.go
  test/integration/istio/const.go
  test/integration/istio/istio_access_logs_test.go
  test/integration/istio/istio_metric_test.go
  test/integration/istio/istio_tracing_test.go
  test/testkit/mocks/backend/backend.go
  test/testkit/mocks/backend/config_map.go
  test/testkit/mocks/backend/external_service.go
  test/testkit/mocks/backend/options.go
  test/testkit/mocks/urlprovider/urlprovider.go
Labels: area/tests, lgtm, size/XXL

#422 feat: Update to fluentbit 2.1.9 and otel-collector 0.85.0
  Dockerfile
  config/samples/http-mockserver.yaml
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: kind/feature, lgtm, size/S, area/telemetry

#427 chore: Update telemetry-manager and directory-size-exporter to latest…
  Makefile
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS, area/dependency, kind/chore

#429 fix: Potential race condition during webhook setup
  main.go
Labels: lgtm, area/logging, size/S

#406 docs: Perf tests for the metric agent
  docs/contributor/performance-tests/metrics/assets/agent-multi-receiver-accepted.jpg
  docs/contributor/performance-tests/metrics/assets/agent-multi-receiver-cpu.jpg
  docs/contributor/performance-tests/metrics/assets/agent-multi-receiver-memory.jpg
  docs/contributor/performance-tests/metrics/assets/agent-multi-receiver-refused.jpg
  docs/contributor/performance-tests/metrics/assets/max-pod-agent-accepted-metrics.jpg
  docs/contributor/performance-tests/metrics/assets/max-pod-agent-cpu.jpg
  docs/contributor/performance-tests/metrics/assets/max-pod-agent-memory.jpg
  docs/contributor/performance-tests/metrics/assets/max-pod-gateway-accepted-metrics.jpg
  docs/contributor/performance-tests/metrics/assets/max-pod-gateway-sent-metrics.jpg
  docs/contributor/performance-tests/metrics/assets/max-pod-k8s-api.jpg
  docs/contributor/performance-tests/metrics/assets/overall-peak-cpu.jpg
  docs/contributor/performance-tests/metrics/assets/overall-peak-memory.jpg
  docs/contributor/performance-tests/metrics/assets/overall-peak-metric-point-refused.jpg
  docs/contributor/performance-tests/metrics/assets/overall-peak-metric-point.jpg
  docs/contributor/performance-tests/metrics/assets/single-target-peak-metric-point.jpg
  docs/contributor/performance-tests/metrics/metrics.md
Labels: lgtm, size/XL, area/documentation

#428 fix: Update resource and memory limiter settings for otel gateways
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/processors.go
  internal/otelcollector/config/trace/gateway/processors_test.go
  main.go
Labels: lgtm, area/tracing, size/S

#419 feat: Add hardened metric agent configuration
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/processors.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  main.go
Labels: size/L, lgtm, area/telemetry

#420 feat: Improve status condition messages when deletion is blocked by pending resources
  controllers/operator/telemetry_controller_test.go
  docs/user/06-conditions.md
  internal/conditions/conditions.go
  internal/extslices/extslices.go
  internal/extslices/extslices_test.go
  internal/reconciler/logparser/status.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/reconciler/telemetry/metric_components_checker.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/status.go
  internal/reconciler/telemetry/status_test.go
  internal/reconciler/telemetry/status_utils.go
  internal/reconciler/telemetry/trace_components_checker.go
  internal/reconciler/telemetry/trace_components_checker_test.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
  internal/testutils/log_pipeline_builder.go
  internal/testutils/metric_pipeline_builder.go
  internal/testutils/trace_pipeline_builder.go
  test/e2e/telemetry_test.go
Labels: lgtm, size/XL

#432 docs: Perf tests updates for the metric agent
  docs/contributor/performance-tests/metrics/metrics.md
Labels: lgtm, size/XL, area/documentation, area/telemetry, area/performance

#423 docs: Add operation sections, move telemetry status docu
  apis/operator/v1alpha1/telemetry_types.go
  config/crd/bases/operator.kyma-project.io_telemetries.yaml
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/06-conditions.md
  docs/user/README.md
  docs/user/resources/01-telemetry.md
Labels: kind/feature, size/L, lgtm, area/documentation

#434 chore: Update OpenTelemetry Collector to 0.86.0
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: lgtm, size/XS, area/telemetry

#436 test: Add missing trace filter rules test
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/processors.go
  internal/otelcollector/config/trace/gateway/processors_test.go
  test/e2e/traces_noisy_span_filter_test.go
  test/testkit/otlp/traces/exporter.go
  test/testkit/otlp/traces/helpers.go
  test/testkit/otlp/traces/traces.go
  test/testkit/verifiers/traces.go
Labels: area/tests, size/L, lgtm, area/tracing, area/telemetry

#437 test: Revamp trace matchers
  test/e2e/traces_noisy_span_filter_test.go
  test/integration/istio/istio_traces_test.go
  test/testkit/matchers/trace/ptrace_utils.go
  test/testkit/matchers/trace/suite_test.go
  test/testkit/matchers/trace/trace_matchers.go
  test/testkit/matchers/trace/trace_matchers_test.go
  test/testkit/matchers/trace_matchers.go
  test/testkit/matchers/trace_matchers_test.go
  test/testkit/verifiers/traces.go
Labels: lgtm, size/XL
