Repository kyma-project/telemetry-manager, pull requests merged in 2023-06, with the labels that each got.

#192 Only rotate server cert upon expiry
  internal/webhookcert/ca_cert_provider.go
  internal/webhookcert/ca_cert_provider_test.go
  internal/webhookcert/cert_chain_checker.go
  internal/webhookcert/cert_chain_checker_test.go
  internal/webhookcert/cert_expiry_checker.go
  internal/webhookcert/cert_expiry_checker_test.go
  internal/webhookcert/resources.go
  internal/webhookcert/server_cert_generator.go
  internal/webhookcert/server_cert_generator_test.go
  internal/webhookcert/server_cert_provider.go
  internal/webhookcert/server_cert_provider_test.go
  internal/webhookcert/server_cert_storage.go
  internal/webhookcert/server_cert_storage_test.go
  internal/webhookcert/webhook_cert.go
  internal/webhookcert/webhook_cert_test.go
  main.go
Labels: lgtm, size/XXL

#199 Fix race condition
  main.go
Labels: lgtm, size/S

#197 increase memory limit for operator
  config/manager/manager.yaml
Labels: lgtm, size/XS, area/telemetry

#202 Improve fluent bit config reconciliation
  config/samples/telemetry_v1alpha1_logpipeline.yaml
  controllers/telemetry/logparser_controller.go
  controllers/telemetry/logpipeline_controller_test.go
  internal/reconciler/logparser/sync.go
  internal/reconciler/logparser/sync_test.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/sync.go
  internal/reconciler/logpipeline/sync_test.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  main.go
Labels: size/L, lgtm

#204 Remove Fluent Bit from log collection
  internal/resources/fluentbit/resources.go
Labels: lgtm, size/XS

#206 Make excluded Fluent Bit container more specific
  internal/resources/fluentbit/resources.go
Labels: lgtm, size/XS

#198 Optional Loki LogPipeline
  controllers/telemetry/tracepipeline_controller.go
  internal/kubernetes/utils.go
  internal/kubernetes/utils_test.go
  internal/resources/lokilogpipeline/resources.go
  internal/resources/lokilogpipeline/resources_test.go
  main.go
  test/e2e/logging_test.go
Labels: size/L, lgtm, area/logging, area/telemetry

#205 update images to use newest golang and otel-collector version
  Dockerfile
  config/samples/http-mockserver.yaml
  main.go
  sec-scanners-config.yaml
  test/e2e/testkit/mocks/backend_deployment.go
Labels: kind/feature, lgtm, size/S

#200 E2e service exposure
  .golangci.yaml
  go.mod
  go.sum
  hack/provision-test-env.sh
  test/e2e/logging_test.go
  test/e2e/manager_test.go
  test/e2e/metrics_test.go
  test/e2e/suite_test.go
  test/e2e/telemetry_test.go
  test/e2e/testkit/k8s/apiserver/proxy_client.go
  test/e2e/testkit/k8s/service.go
  test/e2e/testkit/k8s/verifiers/deployment.go
  test/e2e/testkit/kyma/telemetry/log/pipeline.go
  test/e2e/testkit/mocks/external_backend_service.go
  test/e2e/testkit/mocks/urlprovider.go
  test/e2e/testkit/otlp/metrics/exporter.go
  test/e2e/testkit/otlp/metrics/metrics.go
  test/e2e/testkit/otlp/traces/exporter.go
  test/e2e/testkit/otlp/traces/traces.go
  test/e2e/testkit/port_registry.go
  test/e2e/tracing_test.go
Labels: lgtm, size/XXL

#201 Do not delete module resource until all managed resources are gone
  config/manager/kustomization.yaml
  internal/reconciler/telemetry/reconciler.go
  test/e2e/suite_test.go
  test/e2e/telemetry_test.go
Labels: size/L, lgtm, area/telemetry

#209 Fix OTLP push URL for E2E tests
  test/e2e/metrics_test.go
  test/e2e/testkit/mocks/urlprovider.go
  test/e2e/tracing_test.go
Labels: lgtm, size/S

#212 adjusted version number
  Makefile
Labels: lgtm, area/ci, kind/chore

#214 Support dark mode for diagrams in documentation
  docs/user/README.md
  docs/user/assets/general-components.drawio.svg
  docs/user/assets/general-stages.drawio.svg
  docs/user/assets/manager-lifecycle.drawio.svg
  docs/user/assets/tracing-intro.drawio.svg
Labels: kind/bug, documentation, lgtm, size/XL

#221 Downgrade Golang version to 1.20.4
  Dockerfile
  config/samples/http-mockserver.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, area/logging, area/telemetry

#226 Fix Whitesource exclude list
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#229 Add Grafana dashboard for metric gateway
  config/dashboards/configmap_opentelemetry_metric_gateway_dashboard.yaml
  config/dashboards/configmap_opentelemetry_trace_collector_dashboard.yaml
  config/dashboards/kustomization.yaml
Labels: lgtm, size/XL

#208 add pprof extension to metric-gateway and trace-collector
  config/networking/networkpolicy.yaml
  config/rbac/role.yaml
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  internal/kubernetes/utils.go
  internal/otelcollector/config/builder/config_builder.go
  internal/otelcollector/config/builder/config_builder_test.go
  internal/otelcollector/config/config.go
  internal/reconciler/metricpipeline/config_builder.go
  internal/reconciler/metricpipeline/config_builder_test.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/config_builder.go
  internal/reconciler/tracepipeline/config_builder_test.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/resources/otelcollector/resources.go
  internal/resources/otelcollector/resources_test.go
  main.go
  test/e2e/metrics_test.go
  test/e2e/testkit/k8s/apiserver/proxy_client.go
  test/e2e/tracing_test.go
Labels: size/L, lgtm

#227 Support dynamic resource profiles for tracing and metrics
  .golangci.yaml
  config/manager/manager.yaml
  controllers/telemetry/metricpipeline_controller_test.go
  controllers/telemetry/tracepipeline_controller_test.go
  internal/otelcollector/config/builder/config_builder.go
  internal/otelcollector/config/builder/config_builder_test.go
  internal/reconciler/metricpipeline/config_builder.go
  internal/reconciler/metricpipeline/config_builder_test.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/config_builder.go
  internal/reconciler/tracepipeline/config_builder_test.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/resources/otelcollector/resources.go
  internal/resources/otelcollector/resources_test.go
  main.go
  test/e2e/metrics_test.go
  test/e2e/tracing_test.go
Labels: size/L, lgtm

#225 Add doc-url to module template
  .gitignore
  Makefile
  hack/deploy-module.sh
  hack/release.sh
Labels: kind/feature, lgtm, size/M, area/telemetry

#232 update otel collector clusterrole
  config/rbac/role.yaml
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/resources/common/resources.go
  internal/resources/common/resources_test.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  internal/resources/otelcollector/resources.go
  internal/resources/otelcollector/resources_test.go
  main.go
Labels: size/L, lgtm

#234 upgrade envtest k8s version to 1.26.5
  Makefile
Labels: lgtm, size/XS

#231 Generate JUnit XML output for e2e tests
  .gitignore
  Makefile
  config/manager/kustomization.yaml
Labels: lgtm, size/S

#235 use envtest v1.26.1 instead of v1.26.5
  Makefile
Labels: lgtm, size/XS

#233 Upgrade test
  Makefile
  hack/upgrade-test.sh
  test/e2e/metrics_test.go
  test/e2e/tracing_test.go
Labels: lgtm, size/M

#238 Skip pending pipelines from collector config
  .golangci.yaml
  internal/kubernetes/lock.go
  internal/kubernetes/lock_test.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  test/e2e/metrics_test.go
  test/e2e/tracing_test.go
Labels: lgtm, size/XL, area/monitoring, area/tracing

#243 Limit Fluent Bit to 300 retries
  controllers/telemetry/logpipeline_controller_test.go
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/output.go
  internal/fluentbit/config/builder/output_test.go
  webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
Labels: lgtm, area/logging, size/S
