Repository kyma-project/telemetry-manager, pull requests merged in 2023-11, with the labels that each got.

#503 fix: Adjust slack notifier payload in github action
  .github/workflows/slack-message.json
Labels: lgtm, size/XS, area/ci, kind/chore

#408 fix: The logic to check if pipeline is present in configmap or not
  controllers/telemetry/logpipeline_controller_test.go
Labels: lgtm, size/XS

#506 fix: Consider LogPipeline undeployable only if grafana-loki output is defined with non-empty url
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/status.go
Labels: kind/bug, lgtm, size/XS, area/logs

#505 chore: Cleanup issue templates
  .github/ISSUE_TEMPLATE/documentation-improvement.md
  .github/ISSUE_TEMPLATE/new-sig-or-wg-proposal.md
  .github/ISSUE_TEMPLATE/security-vulnerability.md
  .github/OWNERS
  .github/issue-template.md
  .github/workflows/slack-message.json
Labels: size/L, lgtm, area/ci

#508 fix: The metric pipeline example
  config/samples/telemetry_v1alpha1_metricpipeline.yaml
Labels: lgtm, size/XS, area/telemetry, area/metrics

#502 feat: Unify OTel Collector resource management
  controllers/telemetry/metricpipeline_controller_test.go
  controllers/telemetry/tracepipeline_controller_test.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/status_test.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent/resources.go
  internal/resources/otelcollector/agent/resources_test.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/config.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/core_pod_spec.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway/resources.go
  internal/resources/otelcollector/gateway/resources_test.go
  internal/resources/otelcollector/gateway_test.go
  main.go
  test/e2e/metrics_basic_test.go
  test/e2e/metrics_runtime_input_test.go
  test/e2e/traces_basic_test.go
  test/testkit/kyma/common_names.go
  test/testkit/verifiers/monitoring.go
Labels: lgtm, size/XXL

#510 fix: Incorrect indentation of metric pipeline
  config/samples/telemetry_v1alpha1_metricpipeline.yaml
Labels: lgtm, size/XS, area/telemetry, area/metrics

#507 chore: Add github action for upgrade test
  .github/template/finalize-test/action.yaml
  .github/workflows/pull-lifecycle.yml
  .github/workflows/slack-message.json
  Makefile
  hack/build-image.sh
  hack/deploy-module.sh
  hack/get-kyma-filename.sh
  hack/lint-manifests.sh
  hack/provision-k3d.sh
  hack/release.sh
  hack/upgrade-test.sh
  hack/wait-for-namespaces.sh
Labels: size/L, lgtm, area/ci, kind/chore

#517 chore: Bump images and module version for 1.3.0 release
  Makefile
  config/manager/kustomization.yaml
  module-config-dev.yaml
  module-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, area/manager

#518 chore: Pass GORELEASER_VERSION env variable to release script
  Makefile
Labels: lgtm, size/XS, kind/chore, area/manager

#512 feat: Remove cumulativeToDelta and its dependencies
  apis/telemetry/v1alpha1/metricpipeline_types.go
  config/development/telemetry.kyma-project.io_metricpipelines.yaml
  docs/user/integration/dynatrace/README.md
  docs/user/resources/05-metricpipeline.md
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/testutils/metric_pipeline_builder.go
  main.go
  sec-scanners-config.yaml
  test/e2e/metrics_cumulative_to_delta_test.go
  test/testkit/kyma/telemetry/metric/pipeline.go
  test/testkit/matchers/metric/metric_matchers.go
  test/testkit/matchers/metric/pmetric_utils.go
  test/testkit/mocks/backend/deployment.go
  test/testkit/otlp/metrics/exporter.go
  test/testkit/otlp/metrics/helpers.go
  test/testkit/otlp/metrics/metrics.go
Labels: size/L, lgtm

#519 chore: Cherry-pick the fix for the release script
  Makefile
Labels: lgtm, size/XS, kind/chore, area/manager

#520 chore: Use --module-archive-version-overwrite flag when creating module
  hack/deploy-module.sh
  hack/release.sh
Labels: lgtm, size/S, kind/chore, area/manager

#521 chore: Cherry-pick the usage of --module-archive-version-overwrite flag
  hack/deploy-module.sh
  hack/release.sh
Labels: lgtm, size/S, kind/chore, area/manager

#515 chore: Configure link checker to not validate against main branch
  .github/workflows/pull-code-checks.yml
Labels: lgtm, size/XS, area/ci, kind/chore

#525 chore: Bump directory-size-exporter to update Golang
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#524 chore: Remove prometheus/self config from the metrics-agent ConfigMap
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
  test/e2e/metrics_prometheus_input_test.go
Labels: lgtm, size/M, kind/chore, area/metrics

#529 test: Fix E2E tests on Gardener
  test/e2e/metrics_service_name_test.go
  test/e2e/traces_service_name_test.go
Labels: area/tests, lgtm, size/XS

#516 docs: ADR: Trace/Metric Pipeline status based on Otel Collector metrics
  docs/contributor/arch/001-otel-collector-metric-based-pipeline-status.md
  docs/contributor/assets/prom-integration-alerts-flow.svg
  docs/contributor/assets/prom-integration-direct-queries-flow.svg
  docs/contributor/assets/prom-integration-extra-ctrl-flow.svg
Labels: size/L, lgtm

#534 chore: Remove grafana dashboards for telemtry components
  config/dashboards/configmap_fluentbit_dashboard.yaml
  config/dashboards/configmap_opentelemetry_trace_gateway_dashboard.yaml
  config/dashboards/kustomization.yaml
  config/default/kustomization.yaml
  config/development/configmap_opentelemetry_metric_gateway_dashboard.yaml
  config/development/kustomization.yaml
  test/e2e/manager_test.go
Labels: lgtm, size/XXL

#539 docs: Add first version of SAP CLS integration
  docs/user/integration/sap-cloud-logging/README.md
Labels: kind/feature, size/L, lgtm, area/documentation

#535 fix: Remove session affinity for Otel collector services
  docs/contributor/performance-tests/metrics/metrics.md
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
Labels: lgtm, size/S

#542 docs: Improve integration with sap cloud logging
  docs/user/integration/sap-cloud-logging/README.md
Labels: lgtm, size/M

#541 fix: Flaky e2e logging test
  test/testkit/mocks/backend/config_map.go
  test/testkit/mocks/logproducer/log_producer.go
Labels: lgtm, size/S

#547 test: Enable e2e logging tests for gardener integration test
  Makefile
Labels: area/tests, lgtm, size/XS

#530 test: Enable gocyclo linter
  .golangci.yaml
  apis/telemetry/v1alpha1/logpipeline_validation.go
  main.go
Labels: size/L, lgtm, area/ci

#548 docs: Fix broken links
  docs/user/03-traces.md
  docs/user/integration/sap-cloud-logging/README.md
Labels: lgtm, size/XS

#564 chore: Bump images and module version for 1.4.0 release
  Makefile
  config/manager/kustomization.yaml
  module-config-dev.yaml
  module-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, area/ci, kind/chore

#511 feat: Istio support for trace and metric gateway
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/istiostatus/istio_status_checker.go
  internal/istiostatus/istio_status_checker_test.go
  internal/kubernetes/utils.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/resources/otelcollector/config.go
  internal/resources/otelcollector/gateway.go
  main.go
  test/integration/istio/istio_metrics_test.go
  test/integration/istio/istio_traces_test.go
  test/integration/istio/suite_test.go
  test/testkit/kyma/istio/peerauthentication.go
  test/testkit/mocks/backend/backend.go
  test/testkit/mocks/backend/deployment.go
  test/testkit/mocks/metricproducer/metric_producer.go
Labels: lgtm, size/XL, area/telemetry, area/metrics, area/traces

#568 test: Add Istio input E2E tests
  test/integration/istio/access_logs_test.go
  test/integration/istio/metrics_istio_input_test.go
  test/integration/istio/metrics_otlp_input_test.go
  test/integration/istio/metrics_prometheus_input_test.go
  test/integration/istio/traces_test.go
  test/testkit/kyma/telemetry/metric/pipeline.go
Labels: size/L, lgtm

#571 test: Change Gardener GCP machine type for gardener integration test
  Makefile
Labels: area/tests, lgtm, size/XS

#543 docs: Enhance prerequisites in Cloud Logging integration tutorial
  docs/user/integration/sap-cloud-logging/README.md
Labels: lgtm, size/XS

#576 feat: Update to Otel Collector 0.89.0
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/XS, area/metrics, area/traces

#579 test: Update Istio module version for integration tests
  Makefile
Labels: area/tests, lgtm, size/XS

#580 test: Increase timeout for gomega.Eventually blocks
  test/integration/istio/metrics_otlp_input_test.go
  test/testkit/periodic/periodic.go
  test/testkit/verifiers/objects.go
Labels: area/tests, lgtm, size/S

#578 chore: Update to scratch based image of otel-collector
  .github/workflows/pull-module.yml
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: lgtm, size/S, kind/chore, area/metrics, area/traces

#585 test: Fix flaky Istio test
  test/integration/istio/metrics_otlp_input_test.go
Labels: area/tests, lgtm, size/XS, kind/failing-test

#583 chore: Update to istio module 1.2.0
  .github/pull-request-template.md
  Makefile
Labels: lgtm, size/S, kind/chore, area/manager

#589 feat: Filter namespaces per MetricPipeline
  .github/workflows/pull-module.yml
  apis/telemetry/v1alpha1/metricpipeline_defaults.go
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  config/development/metricpipeline_busola_extension_cm.yaml
  config/development/telemetry.kyma-project.io_metricpipelines.yaml
  config/samples/telemetry_v1alpha1_metricpipeline.yaml
  docs/user/04-metrics.md
  docs/user/resources/05-metricpipeline.md
  hack/deploy-module.sh
  internal/fluentbit/config/builder/namespace_filter.go
  internal/namespaces/system.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/metric/shared_attributes.go
  internal/otelcollector/config/ottlexpr/expressions.go
  internal/otelcollector/config/trace/gateway/drop_noisy_spans.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/testutils/metric_pipeline_builder.go
  test/e2e/metrics_namespace_selector_test.go
  test/e2e/metrics_otlp_input_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/metrics_runtime_input_test.go
  test/e2e/metrics_service_name_test.go
  test/e2e/traces_service_name_test.go
  test/integration/istio/metrics_istio_input_test.go
  test/integration/istio/metrics_otlp_input_test.go
  test/integration/istio/metrics_prometheus_input_test.go
  test/testkit/kyma/telemetry/metric/pipeline.go
  test/testkit/mocks/metricproducer/metric_producer.go
  test/testkit/mocks/servicenamebundle/service_name_bundle.go
  test/testkit/mocks/telemetrygen/telemetrygen.go
  test/testkit/otlp/kubeletstats/metrics.go
  test/testkit/verifiers/metrics.go
Labels: kind/feature, lgtm, size/XXL, area/metrics, cla: yes

#587 docs: Introduced new chapter for gateways
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/assets/gateways-istio.drawio.svg
  docs/user/assets/telemetry-components.drawio.svg
  docs/user/gateways.md
  docs/user/integration/dynatrace/README.md
  docs/user/integration/dynatrace/assets/integration.drawio.svg
  docs/user/resources/README.md
  docs/user/resources/_sidebar.md
Labels: kind/feature, lgtm, size/XXL, area/documentation, cla: yes
