Repository kyma-project/telemetry-manager, pull requests merged in 2023-02, with the labels that each got.

#1 Setup Telemetry Manager Repository
  .gitignore
  CODEOWNERS
  CODE_OF_CONDUCT.md
  Dockerfile
  Makefile
  README.md
  controller/tracepipeline/config_builder.go
  controller/tracepipeline/config_builder_test.go
  go.mod
  go.sum
  hack/.golangci.yml
  hack/boilerplate.go.txt
  hack/lint-manifests.sh
  hack/utilities.sh
  hack/verify-lint.sh
  main.go
Labels: lgtm, size/XXL

#9 Add dependabot config
  .github/dependabot.yml
Labels: lgtm, area/ci, size/S

#5 update Dockerfile to latest fluentbit, otel-collector and golang image
  Dockerfile
  main.go
Labels: lgtm, size/XS

#22 Bump controller runtime
  go.mod
  go.sum
  internal/kubernetes/mocks/Client.go
Labels: lgtm, size/M

#25 Add a go mod tidy check
  Makefile
  go.mod
  go.sum
Labels: size/L, lgtm

#26 Expose File System Buffer limit as metric
  controller/logpipeline/controller.go
  controller/logpipeline/controller_test.go
Labels: lgtm, size/S

#27 Re-add pprof endpoint
  main.go
Labels: lgtm, size/S

#23 Generate webhook configuration by operator
  Makefile
  config/rbac/role.yaml
  internal/kubernetes/utils.go
  internal/resources/webhook/resources.go
  internal/setup/webhook.go
  internal/setup/webhook_test.go
  main.go
Labels: size/L, lgtm

#30 Add otel collector RBAC creation
  controller/logpipeline/controller.go
  controller/tracepipeline/controller.go
  controller/tracepipeline/controller_test.go
  controller/tracepipeline/suite_test.go
  internal/resources/common/resources.go
  internal/resources/common/resources_test.go
  internal/resources/logpipeline/resources.go
  internal/resources/logpipeline/resources_test.go
  main.go
Labels: size/L, lgtm

#40 Add ginkgo linter
  .golangci.yaml
  controller/logpipeline/controller_test.go
Labels: lgtm, size/XS

#37 update otel-collector to 0.72.0
  main.go
Labels: lgtm, size/XS, area/telemetry

#28 Add governance job milv config
  CODEOWNERS
  milv.config.yaml
Labels: lgtm, size/S

#19 Adding pod ip usage for trace collector
  controller/tracepipeline/config_builder.go
  controller/tracepipeline/config_builder_test.go
  controller/tracepipeline/resources.go
Labels: lgtm, size/M, area/telemetry
