Repository kyma-project/telemetry-manager, pull requests merged in 2023-07, with the labels that each got.

#245 Update docs for Fluent Bit retry limit
  docs/user/02-logs.md
Labels: lgtm, size/XS

#246 Set log level for telemetry module to existing default
  config/manager/manager.yaml
Labels: lgtm, size/XS

#240 Basic metric agent setup
  .golangci.yaml
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/rbac/role.yaml
  config/samples/telemetry_v1alpha1_metricpipeline.yaml
  controllers/telemetry/metricpipeline_controller_test.go
  controllers/telemetry/suite_test.go
  controllers/telemetry/tracepipeline_controller_test.go
  docs/user/resources/05-metricpipeline.md
  internal/otelcollector/config/builder/otlpoutput/config_builder.go
  internal/otelcollector/config/builder/otlpoutput/config_builder_test.go
  internal/otelcollector/config/builder/otlpoutput/env_vars.go
  internal/otelcollector/config/config.go
  internal/reconciler/metricpipeline/config_builder.go
  internal/reconciler/metricpipeline/config_builder_test.go
  internal/reconciler/metricpipeline/config_builder_test_utils.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/tracepipeline/config_builder.go
  internal/reconciler/tracepipeline/config_builder_test.go
  internal/reconciler/tracepipeline/config_builder_test_utils.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
  internal/resources/otelcollector/agent/resources.go
  internal/resources/otelcollector/agent/resources_test.go
  internal/resources/otelcollector/core/core.go
  internal/resources/otelcollector/gateway/resources.go
  internal/resources/otelcollector/gateway/resources_test.go
  main.go
  sec-scanners-config.yaml
  test/e2e/testkit/mocks/backend_deployment.go
Labels: lgtm, area/monitoring, size/XXL, area/telemetry

#247 Release 0.6.0
  Makefile
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/S, area/telemetry

#249 Restructure OTEL collector config builders
  .golangci.yaml
  internal/otelcollector/config/builder/metric/agent/config_builder.go
  internal/otelcollector/config/builder/metric/agent/config_builder_test.go
  internal/otelcollector/config/builder/metric/gateway/config_builder.go
  internal/otelcollector/config/builder/metric/gateway/config_builder_test.go
  internal/otelcollector/config/builder/metric/gateway/processors.go
  internal/otelcollector/config/builder/metric/gateway/processors_test.go
  internal/otelcollector/config/builder/trace/gateway/config_builder.go
  internal/otelcollector/config/builder/trace/gateway/config_builder_test.go
  internal/otelcollector/config/builder/trace/gateway/processors.go
  internal/otelcollector/config/builder/trace/gateway/processors_test.go
  internal/reconciler/metricpipeline/config_builder.go
  internal/reconciler/metricpipeline/config_builder_test.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/testutils/metric_pipeline_builder.go
  internal/testutils/trace_pipeline_builder.go
Labels: lgtm, size/XXL, area/telemetry

#252 Remove trace filter for Loki connections
  internal/otelcollector/config/builder/trace/gateway/config_builder_test.go
  internal/otelcollector/config/builder/trace/gateway/processors.go
  internal/otelcollector/config/builder/trace/gateway/processors_test.go
Labels: lgtm, size/XS

#251 Adjust docs for Loki removal
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/assets/general-components.drawio.svg
  docs/user/assets/logging-arch.drawio.svg
  docs/user/assets/logging-pipelines.drawio.svg
Labels: size/L, lgtm, area/logging, kind/cleanup

#242 Adjusts the testing strategy document to adhere to typical quality standards
  docs/contributor/testing.md
Labels: lgtm, size/M

#255 Update OpenTelemetry Collector to 0.81.0
  main.go
  sec-scanners-config.yaml
  test/e2e/testkit/mocks/backend_deployment.go
Labels: lgtm, size/XS

#256 Fix broken links
  apis/telemetry/v1alpha1/logpipeline_types.go
  config/busola/logpipeline_busola_extension_cm.yaml
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  docs/user/03-traces.md
  docs/user/resources/02-logpipeline.md
  webhook/logpipeline/webhook.go
Labels: lgtm, size/S

#257 Testing pipelines versioning
  test/e2e/logging_test.go
  test/e2e/metrics_test.go
  test/e2e/suite_test.go
  test/e2e/telemetry_test.go
  test/e2e/testkit/k8s/label_opts.go
  test/e2e/testkit/k8s/label_opts_test.go
  test/e2e/testkit/k8s/objects.go
  test/e2e/testkit/k8s/telemetry.go
  test/e2e/testkit/kyma/telemetry/metric/pipeline.go
  test/e2e/testkit/kyma/telemetry/trace/pipeline.go
  test/e2e/tracing_test.go
Labels: size/L, lgtm

#260 Fix installation guide typo
  docs/contributor/installation.md
Labels: kind/bug, lgtm, size/S, area/telemetry

#262 Enable new Fluentbit metric exposure
  .golangci.yaml
  Makefile
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  test/e2e/logging_test.go
  test/e2e/metrics_test.go
  test/e2e/testkit/matchers/log_matchers.go
  test/e2e/testkit/matchers/log_matchers_test.go
  test/e2e/testkit/matchers/metric_matchers.go
  test/e2e/testkit/matchers/metric_matchers_test.go
  test/e2e/testkit/matchers/prometheus_matcher.go
  test/e2e/testkit/matchers/prometheus_matcher_test.go
  test/e2e/testkit/matchers/suite_test.go
  test/e2e/testkit/matchers/testdata/consist_of_spans_with_attributes/full_match.jsonl
  test/e2e/testkit/matchers/testdata/consist_of_spans_with_attributes/no_match.jsonl
  test/e2e/testkit/matchers/testdata/consist_of_spans_with_attributes/partial_match.jsonl
  test/e2e/testkit/matchers/testdata/consist_of_spans_with_ids/full_match.jsonl
  test/e2e/testkit/matchers/testdata/consist_of_spans_with_ids/no_match.jsonl
  test/e2e/testkit/matchers/testdata/consist_of_spans_with_ids/partial_match.jsonl
  test/e2e/testkit/matchers/testdata/consist_of_spans_with_trace_id/full_match.jsonl
  test/e2e/testkit/matchers/testdata/consist_of_spans_with_trace_id/no_match.jsonl
  test/e2e/testkit/matchers/testdata/consist_of_spans_with_trace_id/partial_match.jsonl
  test/e2e/testkit/matchers/testdata/have_logs/logs.jsonl
  test/e2e/testkit/matchers/testdata/have_metrics/full_match.jsonl
  test/e2e/testkit/matchers/testdata/have_metrics/no_match.jsonl
  test/e2e/testkit/matchers/testdata/have_metrics/partial_match.jsonl
  test/e2e/testkit/matchers/testdata/prometheus/metrics.txt
  test/e2e/testkit/matchers/trace_matchers.go
  test/e2e/testkit/matchers/trace_matchers_test.go
  test/e2e/tracing_test.go
  webhook/dryrun/testdata/expected/pipelines/fluent-bit.conf
  webhook/dryrun/testdata/given/fluent-bit-configmap.yaml
Labels: size/L, lgtm, area/logging

#268 Add role to create/patch events
  config/rbac/role.yaml
  controllers/operator/telemetry_controller.go
  main.go
Labels: kind/bug, lgtm, size/S, area/telemetry

#266 Introduce make targets to run e2e tests per signal
  Makefile
  test/e2e/logging_test.go
  test/e2e/manager_test.go
  test/e2e/metrics_test.go
  test/e2e/telemetry_test.go
  test/e2e/testkit/matchers/log_matchers_test.go
  test/e2e/testkit/matchers/metric_matchers_test.go
  test/e2e/testkit/matchers/prometheus_matcher_test.go
  test/e2e/testkit/matchers/trace_matchers_test.go
  test/e2e/tracing_test.go
Labels: lgtm, size/M

#263 Refines the PR-template with the testability aspects.
  .github/pull-request-template.md
Labels: lgtm, size/M, area/ci

#241 add sidebar
  docs/user/_sidebar.md
Labels: lgtm, size/XS

#274 Fix otel-collector crash due to missing secret ref
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  test/e2e/metrics_test.go
  test/e2e/tracing_test.go
Labels: lgtm, size/M

#273 Replace all hard-coded collector ports with constants
  internal/otelcollector/config/builder/common/ports.go
  internal/otelcollector/config/builder/metric/agent/config_builder.go
  internal/otelcollector/config/builder/metric/agent/receivers.go
  internal/otelcollector/config/builder/metric/gateway/config_builder.go
  internal/otelcollector/config/builder/trace/gateway/config_builder.go
  internal/otelcollector/config/builder/trace/gateway/processors.go
  internal/otelcollector/ports/ports.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/resources/otelcollector/core/core.go
  internal/resources/otelcollector/gateway/resources.go
Labels: size/L, lgtm, area/telemetry

#275 replace relative links
  docs/user/01-manager.md
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/README.md
Labels: documentation, lgtm, size/M, area/documentation

#270 Revert "Optional Loki LogPipeline (#198), Automatic deployment of the Loki pipeline if service is present."
  controllers/telemetry/tracepipeline_controller.go
  internal/kubernetes/utils.go
  internal/kubernetes/utils_test.go
  internal/resources/lokilogpipeline/resources.go
  internal/resources/lokilogpipeline/resources_test.go
  main.go
  test/e2e/logging_test.go
Labels: kind/bug, size/L, lgtm, area/logging, area/telemetry

#278 Release 0.7.0
  Makefile
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/S

#277 Filter by input source in metric gateway
  .golangci.yaml
  internal/otelcollector/config/builder/metric/agent/processors.go
  internal/otelcollector/config/builder/metric/gateway/config.go
  internal/otelcollector/config/builder/metric/gateway/config_builder.go
  internal/otelcollector/config/builder/metric/gateway/config_builder_test.go
  internal/otelcollector/config/builder/metric/gateway/exporters.go
  internal/otelcollector/config/builder/metric/gateway/processors.go
  internal/otelcollector/config/builder/metric/gateway/processors_test.go
  internal/otelcollector/config/builder/metric/shared_attributes.go
Labels: size/L, lgtm, area/monitoring, area/telemetry

#279 Refine otlpexporter package API
  internal/otelcollector/config/builder/common/config_base_exporters.go
  internal/otelcollector/config/builder/common/otlpexporter/config_builder.go
  internal/otelcollector/config/builder/common/otlpexporter/config_builder_test.go
  internal/otelcollector/config/builder/common/otlpexporter/env_vars.go
  internal/otelcollector/config/builder/metric/gateway/config.go
  internal/otelcollector/config/builder/metric/gateway/config_builder.go
  internal/otelcollector/config/builder/metric/gateway/config_builder_test.go
  internal/otelcollector/config/builder/trace/gateway/config.go
  internal/otelcollector/config/builder/trace/gateway/config_builder.go
  internal/otelcollector/config/builder/trace/gateway/config_builder_test.go
Labels: size/L, lgtm

#269 Update Fluent Bit to 2.1.7 & golang to 1.20.6
  Dockerfile
  config/samples/http-mockserver.yaml
  main.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, area/dependency, size/S

#284 fix rendering issues
  docs/user/03-traces.md
Labels: documentation, lgtm, size/XS, area/documentation, area/telemetry

#291 Disable the dupl linter verifications for the "_test.go" files.
  .golangci.yaml
Labels: lgtm, size/M

#296 Add a simple Prometheus endpoint scraping e2e test scenario
  .golangci.yaml
  test/e2e/metrics_runtime_input_test.go
  test/e2e/metrics_workloads_input_test.go
  test/e2e/testkit/kyma/telemetry/metric/pipeline.go
  test/e2e/testkit/mocks/custom_metric_provider.go
Labels: size/L, lgtm

#297 Rename input.application.workloads to input.application.prometheus
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  config/development/telemetry.kyma-project.io_metricpipelines.yaml
  config/samples/telemetry_v1alpha1_metricpipeline.yaml
  docs/user/resources/05-metricpipeline.md
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/processors.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/shared_attributes.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/testutils/metric_pipeline_builder.go
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/testkit/kyma/telemetry/metric/pipeline.go
Labels: size/L, lgtm

#224 CumulativeToDelta conversion support for metricpipelines
  apis/telemetry/v1alpha1/metricpipeline_types.go
  config/development/telemetry.kyma-project.io_metricpipelines.yaml
  docs/user/resources/05-metricpipeline.md
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/testutils/metric_pipeline_builder.go
  test/e2e/metrics_test.go
  test/e2e/testkit/kyma/telemetry/metric/pipeline.go
  test/e2e/testkit/matchers/metric_matchers.go
  test/e2e/testkit/matchers/metric_matchers_test.go
  test/e2e/testkit/matchers/testdata/have_metrics_sum/full_match.jsonl
  test/e2e/testkit/matchers/testdata/have_metrics_sum/no_match.jsonl
  test/e2e/testkit/matchers/testdata/have_metrics_sum/partial_match.jsonl
  test/e2e/testkit/otlp/metrics/exporter.go
  test/e2e/testkit/otlp/metrics/metrics.go
Labels: size/L, lgtm

#289 Make Telemetry CRD namspace scoped
  apis/operator/v1alpha1/telemetry_types.go
  config/busola/telemetry_busola_extension_cm.yaml
  config/crd/bases/operator.kyma-project.io_telemetries.yaml
  config/rbac/role.yaml
  controllers/operator/telemetry_controller.go
  controllers/operator/telemetry_controller_test.go
  docs/user/resources/01-telemetry.md
  internal/reconciler/telemetry/reconciler.go
  main.go
  test/e2e/manager_test.go
  test/e2e/suite_test.go
  test/e2e/telemetry_test.go
  test/e2e/testkit/k8s/telemetry.go
Labels: size/L, lgtm

#300 Markdown link checker
  .github/workflows/markdown-link-check.yml
  .mlc.config.json
  README.md
  docs/contributor/governance.md
Labels: lgtm, area/ci, size/S

#283 Do not add pipleine to fluent bit configmap if secret ref is missing
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/logpipeline_controller_test.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/sync.go
  internal/reconciler/logpipeline/sync_test.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  internal/setup/predicates.go
  webhook/dryrun/file_writer.go
Labels: kind/bug, size/L, lgtm, area/logging, area/telemetry

#293 Add e2e logging tests
  .golangci.yaml
  controllers/telemetry/tracepipeline_controller.go
  test/e2e/logging_annotation_test.go
  test/e2e/logging_exclude_container_test.go
  test/e2e/logging_fluentbit_metrics_test.go
  test/e2e/logging_label_test.go
  test/e2e/logging_log_delivery_test.go
  test/e2e/logging_parser_test.go
  test/e2e/metrics_test.go
  test/e2e/testkit/kyma/telemetry/log/parser.go
  test/e2e/testkit/kyma/telemetry/log/pipeline.go
  test/e2e/testkit/matchers/log_matchers.go
  test/e2e/testkit/matchers/log_matchers_test.go
  test/e2e/testkit/matchers/testdata/have_logs/logs.jsonl
  test/e2e/testkit/mocks/log_spammer.go
  test/e2e/tracing_test.go
Labels: lgtm, area/logging, size/XXL, area/telemetry

#305 Release 0.8.0
  Makefile
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, area/logging, area/tracing, size/S, area/telemetry

#290 Adds a link to the code style guideline.
  .github/pull-request-template.md
Labels: lgtm, size/XS, area/ci

#307 add status badge to Telemetry README
  README.md
Labels: lgtm, size/XS

#302 E2E test various metric types
  config/samples/telemetry_v1alpha1_metricpipeline.yaml
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/testkit/matchers/metric_matchers.go
  test/e2e/testkit/matchers/metric_matchers_test.go
  test/e2e/testkit/mocks/custom_metric_provider.go
  test/e2e/testkit/otlp/metrics/metrics.go
Labels: size/L, lgtm
