Repository kyma-project/telemetry-manager, pull requests merged in 2023-12, with the labels that each got.

#573 chore: Remove kyma common logging dependency and refactor logging/overrides logic
  controllers/telemetry/suite_test.go
  go.mod
  go.sum
  internal/kubernetes/configmap.go
  internal/kubernetes/configmap_test.go
  internal/logger/logger.go
  internal/overrides/config.go
  internal/overrides/handler.go
  internal/overrides/handler_test.go
  internal/overrides/overrides.go
  internal/reconciler/logparser/reconciler.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  main.go
Labels: lgtm, size/XL, cla: yes

#600 test: Improve push metrics test
  test/integration/istio/metrics_otlp_input_test.go
Labels: area/tests, lgtm, size/M, kind/missing-test, area/telemetry, area/metrics, cla: yes

#602 chore: Bump images and module version for releasing 1.5.0
  Makefile
  config/manager/kustomization.yaml
  main.go
  module-config-dev.yaml
  module-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/S, area/telemetry, kind/chore, cla: yes

#590 feat: Use separate tail plugin per LogPipeline
  controllers/telemetry/logpipeline_controller_test.go
  internal/fluentbit/config/builder/config_builder.go
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/input.go
  internal/fluentbit/config/builder/input_test.go
  internal/fluentbit/config/builder/kubernetes_filter.go
  internal/fluentbit/config/builder/kubernetes_filter_test.go
  internal/fluentbit/config/builder/metadata_filter.go
  internal/fluentbit/config/builder/namespace_filter.go
  internal/fluentbit/config/builder/namespace_filter_test.go
  internal/fluentbit/config/builder/section_builder.go
  internal/fluentbit/config/builder/section_builder_test.go
  internal/resources/fluentbit/resources.go
  webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
Labels: lgtm, area/logging, size/XL, cla: yes

#604 chore: Update Ginkgo CLI to match with go.mod
  Makefile
Labels: lgtm, size/XS, cla: yes

#599 chore: Remove ModuleTemplate from releases
  .github/template/prepare-test/action.yaml
  .github/workflows/pull-module.yml
  .github/workflows/push-release.yml
  .gitignore
  .goreleaser.yaml
  docs/contributor/installation.md
  docs/contributor/releasing.md
  hack/release.sh
  module-config-dev.yaml
Labels: size/L, lgtm, area/ci, kind/chore, cla: yes

#605 chore: Update directory-size-exporter to use Go 1.21.5
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#598 feat: Reflect metric agent status in metric pipeline
  controllers/telemetry/suite_test.go
  docs/user/resources/01-telemetry.md
  internal/conditions/conditions.go
  internal/reconciler/metricpipeline/mocks/daemonset_prober.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/telemetry/metric_components_checker.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/status_test.go
  main.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_secret_rotation_test.go
  test/testkit/verifiers/metrics.go
Labels: size/L, lgtm, area/metrics, cla: yes

#612 chore: Improve import linting
  .golangci.yaml
  Makefile
  controllers/operator/suite_test.go
  controllers/operator/telemetry_controller_test.go
  controllers/telemetry/logparser_controller_test.go
  controllers/telemetry/logpipeline_controller_test.go
  controllers/telemetry/metricpipeline_controller_test.go
  controllers/telemetry/suite_test.go
  controllers/telemetry/tracepipeline_controller_test.go
  test/e2e/logs_annotation_test.go
  test/e2e/logs_basic_test.go
  test/e2e/logs_custom_output_test.go
  test/e2e/logs_dedot_test.go
  test/e2e/logs_exclude_container_test.go
  test/e2e/logs_label_test.go
  test/e2e/logs_mtls_test.go
  test/e2e/logs_parser_test.go
  test/e2e/logs_webhook_test.go
  test/e2e/manager_test.go
  test/e2e/metrics_basic_test.go
  test/e2e/metrics_secret_rotation_test.go
  test/e2e/metrics_service_name_test.go
  test/e2e/suite_test.go
  test/e2e/telemetry_test.go
  test/e2e/traces_basic_test.go
  test/e2e/traces_mtls_test.go
  test/e2e/traces_multi_pipeline_test.go
  test/e2e/traces_noisy_span_filter_test.go
  test/e2e/traces_secret_rotation_test.go
  test/e2e/traces_service_name_test.go
  test/testkit/matchers/log/log_matcher_test.go
  test/testkit/matchers/metric/metric_matchers_test.go
  test/testkit/matchers/trace/trace_matchers_test.go
  webhook/logpipeline/webhook_suite_test.go
  webhook/logpipeline/webhook_test.go
Labels: size/L, lgtm, cla: yes

#613 chore: Use dot import for gomega matchers in testkit
  test/testkit/verifiers/daemonset.go
  test/testkit/verifiers/deployment.go
  test/testkit/verifiers/logs.go
  test/testkit/verifiers/metrics.go
  test/testkit/verifiers/monitoring.go
  test/testkit/verifiers/objects.go
  test/testkit/verifiers/telemetry.go
  test/testkit/verifiers/traces.go
Labels: size/L, lgtm, cla: yes

#616 chore: Avoid adding remote origin in release script
  Makefile
  hack/release.sh
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#618 chore: Add GITHUB_TOKEN env when running release make target
  .github/workflows/push-release.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#619 chore: Fetch all history in Github Release workflow
  .github/workflows/push-release.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#625 docs: Remove obsolete log attribute prefix limitations
  docs/user/02-logs.md
Labels: lgtm, area/logging, size/XS, cla: yes

#624 docs: Update Fluent Bit Config ADR
  docs/contributor/arch/002-fluent-bit-without-file-system-buffer.md
Labels: lgtm, size/XS, cla: yes

#628 docs: Adjust telemetry to new content guidelines
  README.md
  docs/contributor/development.md
  docs/contributor/governance.md
  docs/contributor/installation.md
  docs/contributor/performance-tests/metrics/metrics.md
  docs/contributor/releasing.md
  docs/contributor/testing.md
  docs/contributor/troubleshooting.md
  docs/user/01-manager.md
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/README.md
  docs/user/gateways.md
  docs/user/integration/dynatrace/README.md
  docs/user/integration/jaeger/README.md
  docs/user/integration/loki/README.md
  docs/user/integration/opentelemetry-demo/README.md
  docs/user/integration/sap-cloud-logging/README.md
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/03-logparser.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
Labels: size/L, lgtm, cla: yes

#633 test: Implement e2e tests for the overrides functionality
  test/e2e/logs_dedot_test.go
  test/e2e/logs_exclude_container_test.go
  test/e2e/overrides_test.go
  test/integration/istio/access_logs_test.go
  test/testkit/kyma/overrides/overrides.go
  test/testkit/kyma/telemetry/log/pipeline.go
  test/testkit/matchers/log/log_matcher_test.go
  test/testkit/matchers/log/log_matchers.go
Labels: size/L, lgtm, cla: yes

#634 fix: Improved dynatrace integration guide
  docs/user/integration/dynatrace/README.md
  docs/user/integration/sap-cloud-logging/README.md
  docs/user/integration/sap-cloud-logging/secret-example.yaml
Labels: kind/bug, lgtm, area/documentation, size/S, cla: yes

#627 fix: Allow network policy based on signal type
  internal/otelcollector/ports/ports.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/config.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  test/e2e/metrics_basic_test.go
  test/e2e/traces_basic_test.go
  test/integration/istio/metrics_otlp_input_test.go
  test/integration/istio/traces_test.go
  test/testkit/k8s/network_policy.go
Labels: kind/bug, size/L, lgtm, area/telemetry, area/metrics, area/traces, cla: yes

#635 fix: Allow network policy based on signal type (#627)
  internal/otelcollector/ports/ports.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/config.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  test/e2e/metrics_basic_test.go
  test/e2e/traces_basic_test.go
  test/integration/istio/metrics_otlp_input_test.go
  test/integration/istio/traces_test.go
  test/testkit/k8s/network_policy.go
Labels: kind/bug, size/L, lgtm, area/telemetry, area/metrics, area/traces, cla: yes

#639 chore: Create release 1.5.1
  Makefile
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, area/telemetry, area/metrics, area/traces, cla: yes

#640 chore: Backport new release process
  .github/template/prepare-test/action.yaml
  .github/workflows/pull-module.yml
  .github/workflows/push-release.yml
  .gitignore
  .goreleaser.yaml
  Makefile
  docs/contributor/installation.md
  docs/contributor/releasing.md
  hack/release.sh
  module-config-dev.yaml
Labels: size/L, lgtm, area/ci, kind/chore, cla: yes

#641 fix: Fixed link in docu and adjusted code checks to run also on docu changes only
  .github/template/setup-golang/action.yaml
  .github/workflows/pull-code-checks.yml
  .github/workflows/pull-docu-checks.yml
  .github/workflows/pull-github-checks.yml
  docs/user/README.md
Labels: kind/bug, lgtm, size/M, area/ci, area/documentation, cla: yes

#611 docs: Add minimal resource usage
  docs/user/README.md
  docs/user/gateways.md
Labels: kind/feature, lgtm, area/documentation, size/S, area/manager, cla: yes

#615 feat: Simplify MetricPipeline namespace filter
  apis/telemetry/v1alpha1/metricpipeline_defaults.go
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  config/development/metricpipeline_busola_extension_cm.yaml
  config/development/telemetry.kyma-project.io_metricpipelines.yaml
  config/samples/telemetry_v1alpha1_metricpipeline.yaml
  docs/user/04-metrics.md
  docs/user/resources/05-metricpipeline.md
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/status_test.go
  internal/testutils/metric_pipeline_builder.go
  test/e2e/metrics_namespace_selector_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/metrics_runtime_input_test.go
  test/e2e/metrics_service_name_test.go
  test/testkit/kyma/telemetry/metric/pipeline.go
Labels: lgtm, size/XL, cla: yes

#609 fix: Do not intercept outgoing connections from metric agent by Istio
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/gateway_test.go
  test/integration/istio/metrics_istio_input_test.go
Labels: lgtm, size/S, cla: yes

#629 feat: Include the Metrics feature in releases for fast and regular channels
  .github/workflows/pull-docu-checks.yml
  .github/workflows/pull-integration.yml
  Makefile
  config/busola/kustomization.yaml
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/crd/kustomization.yaml
  config/development/kustomization.yaml
  config/development/manager_deployment_patch.yaml
  config/manager/manager.yaml
  controllers/operator/telemetry_controller.go
  docs/user/04-metrics.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/assets/telemetry-components.drawio.svg
  docs/user/integration/dynatrace/README.md
  docs/user/integration/sap-cloud-logging/README.md
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/telemetry/status.go
  internal/reconciler/telemetry/status_test.go
  main.go
  test/e2e/telemetry_test.go
Labels: kind/feature, size/L, lgtm, area/metrics, cla: yes

#620 fix: Checkmarx issue Improper Error Handling
  internal/reconciler/metricpipeline/mocks/daemonset_prober.go
Labels: lgtm, size/S, area/metrics, cla: yes

#644 docs: Remove leftover notes about metrics feature unavailability
  docs/user/README.md
  docs/user/resources/05-metricpipeline.md
Labels: documentation, lgtm, size/XS, area/metrics, cla: yes

#626 feat: Add metric gateway OTLP endpoint to the telemetry status
  apis/operator/v1alpha1/telemetry_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  config/busola/telemetry_busola_extension_cm.yaml
  config/crd/bases/operator.kyma-project.io_telemetries.yaml
  docs/user/resources/01-telemetry.md
  internal/reconciler/telemetry/status.go
  internal/reconciler/telemetry/status_test.go
Labels: size/L, lgtm, area/telemetry, area/metrics, cla: yes

#638 feat: Align MetricPipeline conditions with Kubernetes API conventions
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/metricpipeline_types_test.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/busola/telemetry_busola_extension_cm.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  docs/user/resources/01-telemetry.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/overrides/handler.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/telemetry/metric_components_checker.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/testutils/metric_pipeline_builder.go
  test/e2e/metrics_basic_test.go
  test/e2e/metrics_mtls_test.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/metrics_runtime_input_test.go
  test/e2e/metrics_secret_rotation_test.go
  test/e2e/metrics_service_name_test.go
  test/testkit/verifiers/metrics.go
Labels: lgtm, size/XXL, cla: yes

#649 feat: Enhance Status Message for Max Pipeline Count Exceeded
  docs/user/resources/01-telemetry.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/reconciler/telemetry/metric_components_checker.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/trace_components_checker_test.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
  test/e2e/metrics_multi_pipeline_test.go
Labels: kind/feature, lgtm, size/M, area/metrics, area/traces, cla: yes

#650 docs: Fix link to documentation for enabling module
  docs/user/integration/dynatrace/README.md
  docs/user/integration/jaeger/README.md
  docs/user/integration/loki/README.md
  docs/user/integration/opentelemetry-demo/README.md
  docs/user/integration/sap-cloud-logging/README.md
Labels: kind/bug, lgtm, area/documentation, size/S, cla: yes

#655 chore: Bump images and module version 1.6.0
  Makefile
  config/manager/kustomization.yaml
  main.go
  module-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/S, area/telemetry, kind/chore, cla: yes

#659 fix: Add missing metric-gateway-priority-class argument
  config/manager/manager.yaml
Labels: kind/bug, lgtm, size/XS, area/metrics, cla: yes

#648 feat: Drop istio metrics for internal communication
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/drop_internal_communication.go
  internal/otelcollector/config/metric/agent/drop_internal_communication_test.go
  internal/otelcollector/config/metric/agent/processors.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
  internal/otelcollector/config/ottlexpr/expressions.go
  internal/otelcollector/config/trace/gateway/drop_noisy_spans.go
  internal/otelcollector/config/trace/gateway/processors_test.go
  internal/otelcollector/config/trace/gateway/testdata/config.yaml
  test/integration/istio/metrics_istio_input_test.go
Labels: size/L, lgtm, area/metrics, cla: yes

#662 test: Validate Istio metric attributes
  test/integration/istio/metrics_istio_input_test.go
Labels: lgtm, kind/missing-test, size/S, area/metrics, cla: yes

#663 chore: Remove go/docker labels from dependabot, improve slack notification
  .github/dependabot.yml
  .github/workflows/slack-message.json
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#660 feat: Add support additional endpoint path
  apis/telemetry/v1alpha1/shared_types.go
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/otelcollector/config/exporters.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/otlpexporter/config_builder.go
  internal/otelcollector/config/otlpexporter/config_builder_test.go
  internal/otelcollector/config/otlpexporter/env_vars.go
  internal/otelcollector/config/trace/gateway/config_builder.go
  test/e2e/metrics_endpoint_path_validation_test.go
  test/e2e/metrics_endpoint_with_path_test.go
  test/e2e/traces_endpoint_path_validation_test.go
  test/e2e/traces_endpoint_with_path_test.go
  test/testkit/kyma/common_names.go
  test/testkit/kyma/env.go
  test/testkit/kyma/telemetry/metric/pipeline.go
  test/testkit/kyma/telemetry/trace/pipeline.go
  test/testkit/verifiers/secret.go
Labels: size/L, lgtm, area/metrics, area/traces, cla: yes

#664 docs: Fix broken links to istio docu
  docs/user/03-traces.md
  docs/user/integration/sap-cloud-logging/README.md
  docs/user/integration/sap-cloud-logging/configmap-deeplinks.yaml
  docs/user/integration/sap-cloud-logging/configmap-navigation.yaml
  docs/user/integration/sap-cloud-logging/secret-example.yaml
Labels: kind/bug, lgtm, size/M, area/documentation, cla: yes

#669 fix: Metric gateway endpoint not set in module status
  internal/reconciler/telemetry/status.go
  internal/reconciler/telemetry/status_test.go
Labels: kind/bug, lgtm, size/S, area/metrics, cla: yes

#668 fix: Improve stability of post-submit job
  Makefile
  test/integration/istio/traces_test.go
Labels: lgtm, size/XS, kind/failing-test, area/metrics, area/traces, cla: yes

#672 fix: Metric gateway endpoint not set in module status (#669)
  internal/reconciler/telemetry/status.go
  internal/reconciler/telemetry/status_test.go
Labels: kind/bug, lgtm, size/S, area/metrics, cla: yes

#665 test: Add e2e tests for disabling reconciliation via overrides ConfigMap
  .github/template/prepare-test/action.yaml
  .github/template/setup-golang/action.yaml
  .github/workflows/post-integration.yml
  .github/workflows/post-release.yml
  .github/workflows/pull-integration.yml
  .github/workflows/pull-lifecycle.yml
  Makefile
  test/e2e/logs_annotation_test.go
  test/e2e/logs_basic_test.go
  test/e2e/logs_custom_output_test.go
  test/e2e/logs_dedot_test.go
  test/e2e/logs_exclude_container_test.go
  test/e2e/logs_label_test.go
  test/e2e/logs_mtls_test.go
  test/e2e/logs_parser_test.go
  test/e2e/logs_webhook_test.go
  test/e2e/manager_test.go
  test/e2e/overrides_test.go
  test/e2e/telemetry_test.go
  test/e2e/traces_basic_test.go
  test/e2e/traces_mtls_test.go
  test/e2e/traces_multi_pipeline_test.go
  test/e2e/traces_noisy_span_filter_test.go
  test/e2e/traces_secret_rotation_test.go
  test/e2e/traces_service_name_test.go
  test/integration/istio/access_logs_test.go
  test/integration/istio/traces_test.go
  test/testkit/kyma/overrides/overrides.go
  test/testkit/verifiers/telemetry.go
Labels: size/L, lgtm, kind/missing-test, area/manager, cla: yes

#667 feat: Remove unused kyma prometheus filter rule
  internal/otelcollector/config/trace/gateway/drop_noisy_spans.go
  internal/otelcollector/config/trace/gateway/processors_test.go
  internal/otelcollector/config/trace/gateway/testdata/config.yaml
Labels: kind/feature, lgtm, size/XS, area/metrics, area/traces, cla: yes

#676 chore: Set up unit test coverage check
  .github/workflows/pull-code-checks.yml
  .testcoverage.yml
  Makefile
  controllers/operator/suite_test.go
  controllers/telemetry/suite_test.go
  webhook/logpipeline/webhook_suite_test.go
Labels: area/tests, lgtm, size/M, area/ci, kind/chore, cla: yes

#678 feat: Bump Fluent Bit to 2.2.1
  .testcoverage.yml
  Dockerfile
  Makefile
  config/samples/http-mockserver.yaml
  main.go
  sec-scanners-config.yaml
  webhook/dryrun/command_runner.go
  webhook/dryrun/dryrun.go
  webhook/dryrun/dryrun_test.go
  webhook/dryrun/file_writer.go
  webhook/dryrun/file_writer_test.go
  webhook/dryrun/mocks/command_runner.go
  webhook/dryrun/mocks/file_writer.go
Labels: size/L, lgtm, cla: yes
