Repository kyma-project/telemetry-manager, pull requests merged in 2023-05, with the labels that each got.

#151 Flaky logpipeline controller test fix
  controllers/telemetry/logpipeline_controller_test.go
Labels: lgtm, size/XS

#129 Automate module verification and release process
  .gitignore
  .goreleaser.yaml
  Makefile
  README.md
  config/samples/operator_v1alpha1_telemetry.yaml
  hack/get_kyma_file_name.sh
  hack/verify_kyma_status.sh
  hack/verify_telemetry_status.sh
  sec-scanners-config.yaml
Labels: kind/feature, size/L, lgtm, area/telemetry

#153 Release 0.1.0
  Makefile
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#156 Remove kyma-system namespace from Kustomize files
  README.md
  config/manager/manager.yaml
  hack/provision-test-env.sh
Labels: lgtm, size/S, area/telemetry

#154 Bump directory-size-exporter
  main.go
Labels: lgtm, size/XS

#161 Release 0.2.0
  Makefile
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/S

#164 Remove .DS_Store and add to .gitignore
  .DS_Store
  .gitignore
Labels: lgtm, size/XS

#162 Restructure module targets in Makefile
  Makefile
  README.md
  docs/deploying-module-template.md
  hack/deploy-module.sh
  hack/get-kyma-filename.sh
  hack/release.sh
  hack/verify_kyma_status.sh
  hack/verify_telemetry_status.sh
Labels: kind/feature, size/L, lgtm, area/documentation, area/telemetry

#146 Add support for multiple TracePipelines and MetricPipelines
  controllers/telemetry/metricpipeline_controller_test.go
  controllers/telemetry/otel_test_helpers.go
  controllers/telemetry/tracepipeline_controller_test.go
  internal/otelcollector/config/builder/config_builder.go
  internal/otelcollector/config/builder/config_builder_test.go
  internal/otelcollector/config/builder/env_vars.go
  internal/reconciler/metricpipeline/config_builder.go
  internal/reconciler/metricpipeline/config_builder_test.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/config_builder.go
  internal/reconciler/tracepipeline/config_builder_test.go
  internal/reconciler/tracepipeline/reconciler.go
  main.go
Labels: size/L, lgtm

#165 update to otel-collector 0.77.0
  main.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/XS

#167 Add E2E tests for multi-pipeline support
  Makefile
  test/e2e/metrics_test.go
  test/e2e/testkit/mocks/backend_deployment.go
  test/e2e/testkit/otlp/matchers/metric_matchers.go
  test/e2e/testkit/otlp/matchers/metric_matchers_test.go
  test/e2e/testkit/otlp/matchers/trace_matchers.go
  test/e2e/testkit/otlp/matchers/trace_matchers_test.go
  test/e2e/tracing_test.go
Labels: lgtm, size/XL

#170 update to fluent-bit 2.1.2
  Dockerfile
  config/samples/http-mockserver.yaml
  main.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm

#174 Delete config file
  config.yaml
Labels: lgtm, size/XS, kind/cleanup, area/telemetry

#182 Revert "Bump github.com/onsi/gomega from 1.27.6 to 1.27.7"
  go.mod
  go.sum
Labels: lgtm, size/XS

#181 Include priority class
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manager/priority_class.yaml
  config/manager/priority_class_high.yaml
  controllers/telemetry/logpipeline_controller_test.go
  controllers/telemetry/metricpipeline_controller_test.go
  controllers/telemetry/tracepipeline_controller_test.go
  test/e2e/logging_test.go
  test/e2e/manager_test.go
  test/e2e/testkit/kyma/telemetry/log/pipeline.go
Labels: size/L, lgtm, area/telemetry

#189 Reduce flakiness of e2e tests
  test/e2e/metrics_test.go
  test/e2e/testkit/k8s/verifiers/deployment.go
  test/e2e/testkit/mocks/backend_deployment.go
  test/e2e/tracing_test.go
Labels: area/tests, size/L, lgtm, kind/failing-test, area/telemetry

#169 Migrate helm leftovers to kustomize
  config/busola/kustomization.yaml
  config/busola/logparser_busola_extension_cm.yaml
  config/busola/logpipeline_busola_extension_cm.yaml
  config/busola/telemetry_busola_extension_cm.yaml
  config/busola/tracepipeline_busola_extension_cm.yaml
  config/dashboards/configmap_fluentbit_dashboard.yaml
  config/dashboards/configmap_opentelemetry_dashboard.yaml
  config/dashboards/kustomization.yaml
  config/default/kustomization.yaml
  config/networking/kustomization.yaml
  config/networking/networkpolicy.yaml
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  test/e2e/manager_test.go
Labels: lgtm, size/XXL, area/telemetry

#173 Reconcile ValidatingWebhookConfiguration
  .golangci.yaml
  Makefile
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  controllers/operator/suite_test.go
  controllers/operator/telemetry_controller.go
  hack/lint-manifests.sh
  internal/reconciler/telemetry/reconciler.go
  internal/setup/webhook.go
  internal/webhookcert/ca_cert_generator.go
  internal/webhookcert/ca_cert_generator_test.go
  internal/webhookcert/ca_cert_provider.go
  internal/webhookcert/ca_cert_provider_test.go
  internal/webhookcert/clock.go
  internal/webhookcert/crypto_utils.go
  internal/webhookcert/resources.go
  internal/webhookcert/server_cert_generator.go
  internal/webhookcert/server_cert_generator_test.go
  internal/webhookcert/webhook_cert.go
  internal/webhookcert/webhook_cert_test.go
  main.go
  test/e2e/manager_test.go
  test/e2e/metrics_test.go
  test/e2e/suite_test.go
  test/e2e/telemetry_test.go
  test/e2e/testkit/k8s/telemetry.go
Labels: lgtm, size/XXL

#191 Release 0.4.0
  Makefile
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/S, area/telemetry

#190 Clean up Fluent Bit volume mounts
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
Labels: lgtm, size/S

#194 Update `control-plane` label
  config/default/kustomization.yaml
Labels: lgtm, size/XS, kind/failing-test, area/telemetry
