Repository kyma-project/telemetry-manager, pull requests merged in 2023-03, with the labels that each got.

#43 Remove sleep statement from webhook test
  webhook/logpipeline/webhook_suite_test.go
Labels: lgtm, size/XS

#31 Restore support to deploy operator with kustomize manifests
  Makefile
  config/crd/bases/telemetry.kyma-project.io_logparsers.yaml
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/role_binding.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  hack/provision-test-env.sh
Labels: size/L, lgtm

#45 Bind services to localhost in tests
  controller/logparser/suite_test.go
  controller/logpipeline/suite_test.go
  controller/tracepipeline/suite_test.go
  webhook/logpipeline/webhook_suite_test.go
Labels: lgtm, size/S

#44 Add end-to-end tests
  Makefile
  go.mod
  hack/provision-test-env.sh
  test/e2e/manager_test.go
  test/e2e/suite_test.go
Labels: size/L, lgtm

#52 Update README
  README.md
Labels: lgtm, size/M

#53 Fixed spelling of Telemetry Manager in README
  README.md
Labels: lgtm, size/S

#54 Fix k3d installation
  Makefile
Labels: lgtm, size/XS

#56 Add stylecheck linter
  .golangci.yaml
  internal/kubernetes/utils.go
  webhook/logpipeline/validation/mocks/variables_validator.go
  webhook/logpipeline/validation/variable_validator.go
  webhook/logpipeline/validation/variable_validator_test.go
  webhook/logpipeline/webhook.go
Labels: lgtm, size/M

#61 Restore kubebuilder PROJECT file
  PROJECT
Labels: lgtm, size/M

#46 Remove unnecessary cli flags
  config/manager/manager.yaml
  controllers/telemetry/tracepipeline_controller_test.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/resources.go
  internal/reconciler/tracepipeline/resources_test.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
  main.go
  webhook/dryrun/dryrun.go
Labels: size/L, lgtm

#71 updated otel-collector and fluentbit version
  Dockerfile
  config/samples/http-mockserver.yaml
  controllers/telemetry/tracepipeline_controller_test.go
  main.go
Labels: lgtm, size/S, area/telemetry

#63 Add an e2e tracing test
  Makefile
  go.mod
  go.sum
  hack/provision-test-env.sh
  internal/otelmatchers/matchers.go
  internal/otelmatchers/otlp_json_trace_parser.go
  test/e2e/suite_test.go
  test/e2e/tracing_test.go
Labels: lgtm, size/XL

#77 Document the e2e tracing test
  hack/provision-test-env.sh
  test/e2e/README.md
  test/e2e/assets/tracing-tests.svg
  test/e2e/tracing_test.go
Labels: lgtm, size/M

#83 Bump otel pkgs from 1.11.1 to 1.14.0
  go.mod
  go.sum
Labels: lgtm, size/M

#70 update Configurable Monitoring status in README
  README.md
Labels: lgtm, size/S

#84 update to fluentbit 2.0.10
  Dockerfile
  config/samples/http-mockserver.yaml
  main.go
Labels: lgtm, area/logging, size/XS, area/telemetry

#87 remove gopkg.in/yaml.v2 dependency
  go.mod
  internal/reconciler/metricpipeline/config_builder_test.go
  internal/reconciler/tracepipeline/config_builder_test.go
Labels: size/L, lgtm

#92 Update Makefile 'Build Dependency' targets
  Makefile
Labels: lgtm, size/S

#93 Restrict RBAC for telemetry manager
  config/rbac/role.yaml
  main.go
Labels: lgtm, size/M

#97 Fix linting errors
  apis/telemetry/v1alpha1/logpipeline_validation.go
  controllers/operator/telemetry_controller_test.go
  controllers/telemetry/metricpipeline_controller_test.go
  controllers/telemetry/tracepipeline_controller_test.go
  internal/kubernetes/utils.go
  internal/reconciler/telemetry/reconciler.go
  webhook/logpipeline/webhook_suite_test.go
Labels: size/L, lgtm

#94 Set unlimited retries for Fluent Bit http output
  config/samples/http-mockserver.yaml
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/output.go
  internal/fluentbit/config/builder/output_test.go
  webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
Labels: lgtm, size/XS

#98 Improve tracing tests by using secret
  test/e2e/tracing_test.go
Labels: lgtm, size/S

#102 Set unlimited retries for Fluent Bit http output (#94)
  Makefile
  config/samples/http-mockserver.yaml
  controller/tracepipeline/controller_test.go
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/output.go
  internal/fluentbit/config/builder/output_test.go
  internal/kubernetes/utils.go
  webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
  webhook/logpipeline/validation/variable_validator.go
  webhook/logpipeline/webhook_suite_test.go
Labels: lgtm, size/M

#99 Watch fluentbit daemonset for deletion as well
  controllers/telemetry/logparser_controller.go
  controllers/telemetry/logpipeline_controller.go
  internal/setup/predicates.go
Labels: lgtm, size/M

#104 Update default image in Makefile
  Makefile
  config/manager/kustomization.yaml
Labels: lgtm, size/XS

#106 have manager namespace-agnostic
  README.md
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/samples/telemetry_v1alpha1_tracepipeline_jaeger.yaml
  config/webhook/manifests.yaml
  controllers/telemetry/metricpipeline_controller_test.go
  controllers/telemetry/suite_test.go
  controllers/telemetry/tracepipeline_controller_test.go
  internal/kubernetes/configmap_test.go
  internal/kubernetes/daemonset_test.go
  internal/kubernetes/deployment_test.go
  internal/reconciler/logpipeline/sync_test.go
  internal/resources/common/resources_test.go
  internal/resources/fluentbit/resources_test.go
  internal/resources/otelcollector/resources_test.go
  internal/setup/webhook_test.go
  main.go
Labels: size/L, lgtm

#109 Update default image to support namespace flag
  Makefile
  config/manager/kustomization.yaml
Labels: lgtm, size/XS

#75 Fixing checkmarx findings
  apis/telemetry/v1alpha1/logpipeline_validation.go
  main.go
  webhook/logpipeline/webhook_suite_test.go
Labels: lgtm, size/M

#110 Deploying telemetry module with the lifecycle manager
  .gitignore
  README.md
  config.yaml
  config/samples/operator_v1alpha1_telemetry.yaml
  docs/deploying-module-template.md
  milv.config.yaml
Labels: lgtm, size/M, area/documentation, area/telemetry
