Repository kyma-project/telemetry-manager, pull requests merged in 2024-12, with the labels that each got.

#1650 chore: Fix perf test problems
  hack/load-tests/log-fluentbit-test-setup.yaml
  hack/load-tests/metric-load-test-setup.yaml
  hack/load-tests/self-monitor-test-setup.yaml
  hack/load-tests/trace-load-test-setup.yaml
Labels: lgtm, area/ci, size/S, kind/chore

#1646 feat: Update to fluentbit 3.2.2
  main.go
  sec-scanners-config.yaml
Labels: kind/feature, size/XS, area/logs, cla: yes

#1651 chore: Bump images for the release 1.29.0
  .env
  config/manager/kustomization.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, cla: yes, area/release

#1653 chore: Switch integration testing to k8s 1.31
  .github/workflows/branch-integration.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1657 chore: Update to istio module 1.11.0
  .env
Labels: lgtm, size/XS, area/dependency, kind/chore, cla: yes

#1659 chore: Refactor OTel resources
  .testcoverage.yml
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  internal/labels/labels.go
  internal/labels/labels_test.go
  internal/reconciler/logpipeline/otel/reconciler.go
  internal/reconciler/logpipeline/otel/reconciler_test.go
  internal/reconciler/logpipeline/otel/status.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/telemetry/status.go
  internal/reconciler/telemetry/status_test.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/status.go
  internal/resources/common/labels.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/config.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  internal/resources/otelcollector/rbac.go
  internal/resources/otelcollector/rbac_test.go
  internal/resources/otelcollector/testdata/log-gateway.yaml
  internal/resources/otelcollector/testdata/metric-agent.yaml
  internal/resources/otelcollector/testdata/metric-gateway-istio.yaml
  internal/resources/otelcollector/testdata/metric-gateway.yaml
  internal/resources/otelcollector/testdata/trace-gateway.yaml
  internal/resources/selfmonitor/resources.go
  internal/utils/test/marshal.go
  main.go
Labels: lgtm, size/XXL, kind/chore, area/logs, area/metrics, area/traces, cla: yes

#1663 fix: Optimize Prometheus scrape target discovery
  hack/load-tests/metric-agent-test-setup.yaml
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/prometheus_receiver.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
Labels: kind/bug, lgtm, size/M, area/metrics, cla: yes

#1656 chore: Enforce consistent yaml formatting
  .yamlfmt
  Makefile
  config/busola/kustomization.yaml
  config/busola/logpipeline_busola_extension_cm.yaml
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/busola/telemetry_busola_extension_cm.yaml
  config/busola/tracepipeline_busola_extension_cm.yaml
  config/crd/bases/operator.kyma-project.io_telemetries.yaml
  config/crd/bases/telemetry.kyma-project.io_logparsers.yaml
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/webhook_in_operator_telemetries.yaml
  config/crd/patches/webhook_in_telemetry_logparsers.yaml
  config/crd/patches/webhook_in_telemetry_logpipelines.yaml
  config/crd/patches/webhook_in_telemetry_metricpipelines.yaml
  config/crd/patches/webhook_in_telemetry_tracepipelines.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/development/crd/bases/operator.kyma-project.io_telemetries.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logparsers.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/development/crd/kustomization.yaml
  config/development/crd/kustomizeconfig.yaml
  config/development/kustomization.yaml
  config/development/webhook-patches.yaml
  config/manager/manager.yaml
  config/manager/metrics_service.yaml
  config/manager/priority_class.yaml
  config/manager/priority_class_high.yaml
  config/networking/kustomization.yaml
  config/networking/networkpolicy.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/operator_v1alpha1_telemetry.yaml
  config/samples/telemetry_v1alpha1_logparser.yaml
  config/samples/telemetry_v1alpha1_logpipeline.yaml
  config/samples/telemetry_v1alpha1_logpipeline_otlp.yaml
  config/samples/telemetry_v1alpha1_metricpipeline.yaml
  config/samples/telemetry_v1alpha1_tracepipeline.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
Labels: lgtm, area/ci, size/XXL, kind/chore, cla: yes

#1666 feat: Bump OTel image version to 0.115.0
  docs/contributor/benchmarks/README.md
  hack/load-tests/run-load-test.sh
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
  test/testkit/mocks/telemetrygen/telemetrygen.go
Labels: kind/feature, area/tests, lgtm, area/documentation, size/S, area/metrics, area/traces, area/manager, cla: yes

#1669 fix: Optimize Prometheus scrape target discovery and prepare images for 1.29.1 release
  .env
  config/manager/kustomization.yaml
  hack/load-tests/metric-agent-test-setup.yaml
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/prometheus_receiver.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  main.go
  sec-scanners-config.yaml
Labels: kind/bug, lgtm, size/M, area/metrics, cla: yes, area/release

#1668 fix: Consider the existence of Istio when applying and deleting resources for Log Gateway
  controllers/telemetry/logpipeline_controller.go
  internal/reconciler/logpipeline/otel/reconciler.go
  internal/reconciler/logpipeline/otel/reconciler_test.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/testdata/log-gateway.yaml
Labels: kind/bug, lgtm, size/M, area/logs, cla: yes

#1654 chore: Remove OTel LogPipeline-related data from docs and Telemetry CRD
  Makefile
  config/crd/bases/operator.kyma-project.io_telemetries.yaml
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
Labels: lgtm, size/M, kind/chore, area/logs, cla: yes

#1658 chore: Add merge_group trigger for workflows
  .github/template/prepare-test/action.yaml
  .github/workflows/branch-integration.yml
  .github/workflows/build-image.yml
  .github/workflows/pr-all-checks-passed.yml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-lifecycle.yml
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1676 chore: Fix build-image after introducing merge queue
  .github/workflows/build-image.yml
  hack/await_image.sh
Labels: size/XS, area/ci, kind/chore, cla: yes

#1678 chore: Change image based on event
  .github/workflows/pr-integration.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1679 chore: Fix lifecyle tests with merge_group trigger
  .github/workflows/pr-lifecycle.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1673 chore: Update golang to 1.23.4 and alpine to 3.21
  Dockerfile
  go.mod
  internal/tools/go.mod
  main.go
  sec-scanners-config.yaml
Labels: area/dependency, size/S, kind/chore, cla: yes

#1677 fix: Remove CPU Limits from all resources
  config/manager/manager.yaml
  controllers/telemetry/logpipeline_controller.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/testdata/log-gateway.yaml
  internal/resources/otelcollector/testdata/metric-agent.yaml
  internal/resources/otelcollector/testdata/metric-gateway-istio.yaml
  internal/resources/otelcollector/testdata/metric-gateway.yaml
  internal/resources/otelcollector/testdata/trace-gateway.yaml
  internal/resources/selfmonitor/resources.go
  internal/resources/selfmonitor/resources_test.go
Labels: kind/bug, lgtm, size/M, area/logs, area/metrics, area/traces, area/manager, cla: yes

#1682 chore: Rename dev release to experimental release
  .github/template/prepare-test/action.yaml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-lifecycle.yml
  .github/workflows/tag-release.yml
  .gitignore
  .goreleaser.yaml
  Makefile
  docs/contributor/development.md
  docs/contributor/installation.md
  docs/contributor/pocs/performance-tests/metrics/metrics.md
  docs/contributor/releasing.md
  hack/get-kyma-filename.sh
  hack/release.sh
  hack/upgrade-test.sh
Labels: size/L, lgtm, kind/chore, cla: yes, area/release

#1681 chore: Apply security suggestions for gha
  .github/workflows/pr-github-checks.yml
Labels: area/ci, size/S, kind/chore, cla: yes

#1671 chore: Generate global constant and sec scan config for docker images
  .env
  .github/workflows/pr-code-checks.yml
  .golangci.yaml
  Makefile
  docs/contributor/releasing.md
  hack/load-tests/run-load-test.sh
  internal/images/images.go
  internal/reconciler/logpipeline/fluentbit/reconciler_test.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/gateway_test.go
  internal/resources/otelcollector/testdata/log-gateway.yaml
  internal/resources/otelcollector/testdata/metric-agent.yaml
  internal/resources/otelcollector/testdata/metric-gateway-istio.yaml
  internal/resources/otelcollector/testdata/metric-gateway.yaml
  internal/resources/otelcollector/testdata/trace-gateway.yaml
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/populateimages/main.go
  main.go
  sec-scanners-config.yaml
  test/e2e/overrides_test.go
  test/testkit/images.go
  test/testkit/mocks/backend/deployment.go
  test/testkit/mocks/telemetrygen/telemetrygen.go
Labels: area/tests, size/L, lgtm, area/documentation, kind/chore, cla: yes, area/release

#1690 chore: Remove flaky telemetry override e2e test
  test/e2e/overrides_test.go
Labels: area/tests, size/S, kind/chore, area/manager

#1688 chore: Prepare images for 1.30.0 release
  .env
  config/manager/kustomization.yaml
  internal/images/images.go
  main.go
  sec-scanners-config.yaml
  test/e2e/overrides_test.go
Labels: lgtm, size/M, kind/chore, cla: yes, area/release

#1691 chore: Fix operator image tag
  .env
Labels: size/XS, kind/chore, cla: yes, area/release

#1694 chore: Adjust upgrade test to new make targets
  .github/workflows/pr-lifecycle.yml
Labels: area/tests, lgtm, size/XS, kind/chore, cla: yes

#1692 chore: Prevent references to images from main on release-branch
  .github/workflows/pr-release.yml
Labels: area/ci, size/S, kind/chore, cla: yes

#1689 chore: Fix wrong sec-scanner-config.yaml file path
  internal/tools/populateimages/main.go
Labels: size/XS, kind/chore, cla: yes, area/release

#1693 chore: Revert running branch integration only on merge group
  .github/workflows/branch-integration.yml
Labels: size/XS, area/ci, kind/chore, cla: yes

#1670 chore: Refactor unit-tests to use golden files
  internal/resources/otelcollector/agent_test.go
  internal/resources/selfmonitor/resources_test.go
  internal/resources/selfmonitor/testdata/self-monitor.yaml
  internal/utils/test/marshal.go
Labels: area/tests, lgtm, size/XL, kind/chore, cla: yes

#1699 test: Fix flaky tests by really waiting for manager readiness
  .github/template/prepare-test/action.yaml
Labels: area/tests, lgtm, size/XS, kind/flaky-test, cla: yes

#1698 docs: Update release process doc with new docker image bump steps
  docs/contributor/releasing.md
Labels: lgtm, area/documentation, size/S, cla: yes, kind/docs

#1702 test: Fix flaky telemetry test (Pt. 2)
  test/e2e/telemetry_test.go
Labels: area/tests, lgtm, kind/flaky-test, size/S, cla: yes

#1697 docs: Update OTTL ADR with multi tranform/filter processor API
  docs/contributor/arch/016-transform-filter-support-for-telemetry-pipelines.md
Labels: lgtm, size/M, area/documentation, cla: yes, kind/docs
