Repository kyma-project/telemetry-manager, pull requests merged in 2024-06, with the labels that each got.

#1134 feat: Set module version in instrumentation scope
  docs/contributor/releasing.md
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/set_instrumentation_scope_test.go
  internal/otelcollector/config/metric/agent/set_instrumention_scope.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  internal/version/version.go
  main.go
  test/e2e/metrics_multi_pipeline_test.go
  test/testkit/matchers/metric/metric_matchers.go
  test/testkit/matchers/metric/metric_matchers_test.go
Labels: kind/feature, size/L, lgtm, area/manager, cla: yes

#1141 chore: Eliminate unnecessary check in transform processor
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/set_instrumentation_scope_test.go
  internal/otelcollector/config/metric/agent/set_instrumention_scope.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
Labels: lgtm, size/S, kind/chore, area/manager, cla: yes

#1144 fix: Set TelemetryFlowHealthy condition to False if the pipeline is non-reconcilable
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/status.go
  test/e2e/logs_mtls_cert_key_pair_dont_match_test.go
  test/e2e/logs_mtls_expired_cert_test.go
  test/e2e/logs_mtls_invalid_cert_test.go
  test/e2e/logs_secret_rotation_test.go
  test/e2e/logs_unsupported_loki_output_test.go
  test/e2e/metrics_mtls_cert_key_pair_dont_match_test.go
  test/e2e/metrics_mtls_expired_cert_test.go
  test/e2e/metrics_mtls_invalid_cert_test.go
  test/e2e/metrics_multi_pipeline_max_pipeline_test.go
  test/e2e/metrics_secret_rotation_test.go
  test/e2e/traces_mtls_cert_key_pair_dont_match_test.go
  test/e2e/traces_mtls_expired_cert_test.go
  test/e2e/traces_mtls_invalid_cert_test.go
  test/e2e/traces_multi_pipeline_max_pipeline_test.go
  test/e2e/traces_secret_rotation_test.go
Labels: kind/bug, lgtm, size/XL, area/logs, area/metrics, area/traces, cla: yes

#1142 feat: Improve self-monitor troubleshooting guides
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/trace_components_checker_test.go
  internal/reconciler/tracepipeline/reconciler_test.go
Labels: kind/feature, size/L, lgtm, area/documentation, cla: yes

#1149 test: Fix instrumentation scope unit tests on release branches
  docs/contributor/releasing.md
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/processors.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/set_instrumentation_scope_test.go
  internal/otelcollector/config/metric/agent/set_instrumention_scope.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/version/version.go
  main.go
Labels: area/tests, lgtm, size/M, kind/failing-test, cla: yes

#1146 docs: Extend flow health ADR
  docs/contributor/arch/010-logging-flow-healthiness-status-api.md
Labels: lgtm, size/XS, area/documentation, area/logs, cla: yes, kind/decision

#1140 fix: Change UI path for telemetry CR back
  config/busola/telemetry_busola_extension_cm.yaml
Labels: kind/bug, lgtm, size/XS, area/manager, cla: yes

#1153 docs: Fix intendation problems in dynatrace guide
  docs/user/integration/dynatrace/README.md
Labels: kind/bug, lgtm, area/documentation, size/S, cla: yes

#1159 fix: Change UI path for telemetry CR back (#1140)
  config/busola/telemetry_busola_extension_cm.yaml
Labels: kind/bug, lgtm, size/XS, area/manager, cla: yes

#1158 feat: Update to otel-collector 0.102.1
  docs/contributor/benchmarks/README.md
  hack/load-tests/run-load-test.sh
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: lgtm, size/S, area/metrics, area/traces, cla: yes

#1162 chore: Run perf tests only for specific images
  .github/workflows/pr-loadtest.yml
Labels: size/L, lgtm, area/ci, kind/chore, cla: yes

#1161 feat: Update to otel-collector 0.102.1 (#1158)
  docs/contributor/benchmarks/README.md
  hack/load-tests/run-load-test.sh
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: lgtm, area/dependency, size/S, area/metrics, area/traces, cla: yes

#1163 feat: Update to otel-collector 0.102.1 (#1158)
  docs/contributor/benchmarks/README.md
  hack/load-tests/run-load-test.sh
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: lgtm, area/dependency, size/S, area/metrics, area/traces, cla: yes

#1165 chore: Fixed skip logic in perf test
  .github/workflows/pr-loadtest.yml
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1166 chore: Update images for telemetry-manager 1.6.2
  .env
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1167 chore: Update images for telemetry-manager 1.17.1
  .env
  config/manager/kustomization.yaml
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/set_instrumentation_scope_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  internal/version/version.go
  sec-scanners-config.yaml
Labels: lgtm, size/M, kind/chore, cla: yes, area/release

#1154 fix: Log load test metric fetch
  hack/load-tests/log-fluentbit-test-setup.yaml
  hack/load-tests/run-load-test.sh
Labels: kind/bug, area/tests, lgtm, area/logs, cla: yes

#1169 feat: Update to fluent-bit 3.0.7
  Dockerfile
  docs/contributor/benchmarks/README.md
  main.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/S, area/logs, cla: yes

#1174 chore: Make status conditions independent of each other
  internal/reconciler/logpipeline/status.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/tracepipeline/status.go
Labels: lgtm, size/M, kind/chore, area/logs, area/metrics, area/traces, cla: yes

#1175 chore: Update to istio module 1.7.0
  .env
Labels: area/tests, lgtm, size/XS, kind/chore, cla: yes

#1176 chore: Update base image for manager build to newest debian release
  Dockerfile
  main.go
Labels: lgtm, kind/chore, area/manager, cla: yes

#1177 docs: Removed outdated strategy links from README
  README.md
  docs/contributor/installation.md
  docs/user/integration/jaeger/values.yaml
Labels: kind/bug, lgtm, area/documentation, size/S, cla: yes

#1186 chore: Bump images for 1.18.0 release
  .env
  config/manager/kustomization.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, cla: yes, area/release

#1181 fix: Clean up resources when all TracePipelines are non-reconcilable
  .testcoverage.yml
  internal/k8sutils/utils.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/tracepipeline/mocks/gateway_applier.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  test/e2e/traces_resources_test.go
Labels: kind/bug, lgtm, size/XL, area/traces, cla: yes

#1180 chore: Fix spelling of OTel acronym
  apis/telemetry/v1alpha1/tracepipeline_types.go
  apis/telemetry/v1beta1/tracepipeline_types.go
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  docs/contributor/arch/001-otel-collector-metric-based-pipeline-status.md
  docs/contributor/pocs/otlp-logs.md
  docs/user/resources/04-tracepipeline.md
Labels: lgtm, area/documentation, size/S, kind/cleanup, kind/chore, cla: yes

#1191 fix: Wrong github action load test cluster name
  .github/workflows/pr-loadtest.yml
Labels: area/tests, lgtm, size/XS, kind/chore, cla: yes

#1193 fix: CA as optional TLS parameter
  internal/tlscert/tls_cert_validator.go
  internal/tlscert/tls_cert_validator_test.go
Labels: kind/bug, lgtm, size/M, area/logs, area/metrics, area/traces, cla: yes

#1190 fix: Remove labeldrop from self-monitor scrape config
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/testdata/config.yaml
Labels: kind/bug, lgtm, size/XS, area/manager, cla: yes

#1197 fix: CA as optional TLS parameter
  internal/tlscert/tls_cert_validator.go
  internal/tlscert/tls_cert_validator_test.go
Labels: kind/bug, lgtm, size/M, area/logs, area/metrics, area/traces, cla: yes

#1198 deps: Update golang to 1.22.4
  Dockerfile
  go.mod
Labels: lgtm, size/XS, area/dependency, kind/chore, cla: yes

#1199 fix: Remove labeldrop from self-monitor scrape config
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/testdata/config.yaml
Labels: kind/bug, lgtm, size/XS, area/manager, cla: yes

#1202 chore: Bump images for 1.18.1 release
  .env
  config/manager/kustomization.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, cla: yes, area/release

#1179 fix: Ensure UnsupportedMode print column in LogPipeline is not empty
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  docs/user/02-logs.md
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  test/e2e/logs_basic_v1alpha1_test.go
  test/e2e/logs_basic_v1beta1_test.go
  test/e2e/logs_custom_output_test.go
  test/testkit/assert/logs.go
Labels: kind/bug, lgtm, size/M, area/logs, cla: yes

#1203 test: Add TracePipeline reconciler unit test when all TracePipelines are non-reconcilable
  .testcoverage.yml
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/stubs/gateway_resources_handler.go
Labels: lgtm, size/M, kind/missing-test, area/traces, cla: yes

#1201 fix: Clean up resources when all MetricPipelines are non-reconcilable
  .testcoverage.yml
  internal/reconciler/metricpipeline/mocks/agent_applier.go
  internal/reconciler/metricpipeline/mocks/gateway_applier.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/stubs/agent_resources_handler.go
  internal/reconciler/metricpipeline/stubs/gateway_resources_handler.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/gateway_test.go
  test/e2e/metrics_resources_test.go
  test/e2e/metrics_runtime_input_test.go
  test/testkit/kyma/common_names.go
Labels: kind/bug, lgtm, size/XXL, area/metrics, cla: yes

#1194 fix: Clean up resources when all LogPipelines are non-reconcilable
  .testcoverage.yml
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/sync.go
  internal/resources/fluentbit/resources.go
  test/e2e/logs_resources_test.go
Labels: kind/bug, size/L, lgtm, area/logs, cla: yes

#1188 feat: Improved messages for secret missing reasons
  .testcoverage.yml
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/reconciler/telemetry/metric_components_checker.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/status_utils.go
  internal/reconciler/telemetry/trace_components_checker.go
  internal/reconciler/telemetry/trace_components_checker_test.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/status.go
  internal/secretref/secret_ref.go
  internal/secretref/secret_ref_test.go
  test/e2e/telemetry_test.go
Labels: kind/feature, lgtm, size/XXL, area/manager, cla: yes

#1204 chore: Cleanup Fluent Bit config generation
  internal/reconciler/logpipeline/reconciler.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  webhook/dryrun/file_writer.go
Labels: lgtm, size/S, kind/chore, area/logs, cla: yes

#1211 fix: Highlights for badges
  config/busola/logpipeline_busola_extension_cm.yaml
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/busola/telemetry_busola_extension_cm.yaml
  config/busola/tracepipeline_busola_extension_cm.yaml
Labels: kind/feature, lgtm, size/M, area/manager, cla: yes

#1195 feat: Update of self monitor to prometheus 2.53.0
  docs/contributor/benchmarks/README.md
  hack/load-tests/run-load-test.sh
  main.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, area/documentation, size/S, area/manager, cla: yes

#1212 chore: Align naming in otelcollector and selfmonitor packages
  internal/reconciler/metricpipeline/mocks/agent_applier_deleter.go
  internal/reconciler/metricpipeline/mocks/gateway_applier_deleter.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/stubs/agent_resources_handler.go
  internal/reconciler/metricpipeline/stubs/gateway_resources_handler.go
  internal/reconciler/tracepipeline/mocks/gateway_applier_deleter.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/stubs/gateway_resources_handler.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  internal/resources/selfmonitor/resources.go
Labels: lgtm, size/XXL, kind/chore, area/metrics, area/traces, cla: yes

#1208 chore: Change self monitor retention size configuration from 80MB to 50MB
  internal/resources/selfmonitor/resources.go
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#1209 chore: Update istio dependency to 1.8.0
  .env
Labels: area/tests, lgtm, size/XS, kind/chore, cla: yes

#1216 chore: Bump linter
  .env
  .github/workflows/pr-code-checks.yml
  .golangci.yaml
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1214 feat: Remove legacy Running and Pending conditions
  .testcoverage.yml
  config/busola/logpipeline_busola_extension_cm.yaml
  config/busola/tracepipeline_busola_extension_cm.yaml
  docs/user/resources/02-logpipeline.md
  docs/user/resources/03-logparser.md
  docs/user/resources/04-tracepipeline.md
  internal/conditions/conditions.go
  internal/conditions/legacy.go
  internal/conditions/legacy_test.go
  internal/reconciler/logparser/reconciler.go
  internal/reconciler/logparser/status.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/reconciler/telemetry/status_test.go
  internal/reconciler/telemetry/trace_components_checker_test.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/status.go
  test/e2e/logs_basic_v1alpha1_test.go
  test/e2e/logs_basic_v1beta1_test.go
  test/e2e/logs_mtls_about_to_expire_cert_test.go
  test/e2e/logs_mtls_cert_key_pair_dont_match_test.go
  test/e2e/logs_mtls_expired_cert_test.go
  test/e2e/logs_mtls_invalid_ca_test.go
  test/e2e/logs_mtls_invalid_cert_test.go
  test/e2e/logs_secret_rotation_test.go
  test/e2e/logs_unsupported_loki_output_test.go
  test/e2e/traces_basic_v1alpha1_test.go
  test/e2e/traces_basic_v1beta1_test.go
  test/e2e/traces_mtls_about_to_expire_cert_test.go
  test/e2e/traces_mtls_cert_key_pair_dont_match_test.go
  test/e2e/traces_mtls_expired_cert_test.go
  test/e2e/traces_mtls_invalid_ca_test.go
  test/e2e/traces_mtls_invalid_cert_test.go
  test/e2e/traces_multi_pipeline_max_pipeline_test.go
  test/e2e/traces_secret_rotation_test.go
  test/testkit/assert/logs.go
  test/testkit/assert/traces.go
Labels: kind/feature, lgtm, size/XXL, area/logs, area/traces, cla: yes

#1221 chore: Upload loadtest results as artifacts
  .github/workflows/pr-loadtest.yml
Labels: lgtm, size/XS, cla: yes

#1220 chore: Migrate tools to go mod
  .env
  .github/dependabot.yml
  .github/template/prepare-test/action.yaml
  .github/template/setup-golang/action.yaml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-lifecycle.yml
  Makefile
  hack/deploy-module.sh
  hack/make/dependencies.mk
  hack/make/provision.mk
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: lgtm, area/ci, size/XXL, kind/chore, cla: yes

#1225 chore: Remove kyma dependency from Gardener deprovision
  hack/make/provision.mk
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#1196 fix: Self monitor load test
  docs/contributor/benchmarks/README.md
  hack/load-tests/run-load-test.sh
  hack/load-tests/self-monitor-test-setup.yaml
Labels: area/tests, lgtm, size/M, area/documentation, kind/chore, cla: yes
