Repository kyma-project/telemetry-manager, pull requests merged in 2024-04, with the labels that each got.

#923 feat: Update to otel-collector 0.97. with updated resty lib
  docs/contributor/telemetry-load-test/README.md
  hack/load-tests/run-load-test.sh
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: kind/feature, lgtm, size/S, area/metrics, area/traces, cla: yes

#914 feat: Add LogPipeline TLS Certificate Validation
  .gitleaksignore
  docs/user/resources/02-logpipeline.md
  internal/conditions/conditions.go
  internal/reconciler/logpipeline/mocks/daemon_set_annotator.go
  internal/reconciler/logpipeline/mocks/daemon_set_prober.go
  internal/reconciler/logpipeline/mocks/tls_cert_validator.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/status.go
  internal/tls/cert/tls_cert_validator.go
  internal/tls/cert/tls_cert_validator_test.go
Labels: kind/feature, lgtm, size/XL, area/documentation, area/logs, area/manager, cla: yes

#941 test: Add Gitleaks workflow
  .github/workflows/pr-code-checks.yml
  .gitleaks.toml
Labels: lgtm, size/XXL, cla: yes

#931 test: Telemetry OTLP-based components error/warning logs
  .github/workflows/pr-integration.yml
  test/e2e/telemetry_logs_analysis_test.go
  test/integration/istio/metrics_istio_input_test.go
  test/testkit/k8s/log_pipeline_v1alpha1.go
  test/testkit/matchers/log/log_matcher_test.go
  test/testkit/matchers/log/log_matchers.go
  test/testkit/mocks/trafficgen/trafficgen.go
Labels: size/L, lgtm, cla: yes

#943 chore: Bump Istio module to 1.5.0 for integration tests
  .env
Labels: lgtm, size/XS, cla: yes

#942 chore: Update directory-size-exporter to use Golang 1.22.2
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#944 chore: Extend telemetrygen pkg
  test/e2e/telemetry_logs_analysis_test.go
  test/integration/istio/metrics_otlp_input_test.go
  test/testkit/mocks/servicenamebundle/service_name_bundle.go
  test/testkit/mocks/telemetrygen/telemetrygen.go
Labels: lgtm, size/M, cla: yes

#940 test: Migrate to telmetry gen for metrics
  go.mod
  go.sum
  test/e2e/metrics_basic_v1alpha1_test.go
  test/e2e/metrics_basic_v1beta1_test.go
  test/e2e/metrics_mtls_test.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_runtime_input_test.go
  test/e2e/metrics_service_name_test.go
  test/e2e/traces_basic_v1alpha1_test.go
  test/e2e/traces_basic_v1beta1_test.go
  test/e2e/traces_mtls_test.go
  test/e2e/traces_multi_pipeline_test.go
  test/e2e/traces_noisy_span_filter_test.go
  test/e2e/traces_service_name_test.go
  test/integration/istio/access_logs_test.go
  test/integration/istio/traces_test.go
  test/testkit/matchers/metric/metric_matchers_test.go
  test/testkit/mocks/urlprovider/urlprovider.go
  test/testkit/otel/metrics/exporter.go
  test/testkit/otel/metrics/helpers.go
  test/testkit/otel/metrics/metrics.go
  test/testkit/otel/traces/helpers.go
  test/testkit/verifiers/traces.go
Labels: area/tests, lgtm, size/XL, kind/cleanup, cla: yes

#949 fix: Set content-security-policy header in webhook handler
  internal/selfmonitor/webhook/handler.go
  internal/selfmonitor/webhook/handler_test.go
Labels: lgtm, size/XS, cla: yes

#948 feat: Add self-monitor Fluent Bit alert rules
  internal/reconciler/logpipeline/reconciler.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/config.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  internal/selfmonitor/alertrules/fluent_bit_rule_builder.go
  internal/selfmonitor/alertrules/otelcol_rule_builder.go
  internal/selfmonitor/alertrules/pipeline_type.go
  internal/selfmonitor/alertrules/rules.go
  internal/selfmonitor/alertrules/rules_test.go
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/testdata/config.yaml
  main.go
Labels: kind/feature, size/L, lgtm, area/logs, cla: yes

#953 fix: Certificater/key should be sanitized always
  .gitleaksignore
  internal/otelcollector/config/otlpexporter/env_vars.go
  internal/reconciler/logpipeline/sync.go
  internal/tls/cert/tls_cert_validator.go
  internal/tls/cert/tls_cert_validator_test.go
  internal/tls/validate.go
  internal/tls/validate_test.go
Labels: kind/bug, size/L, lgtm, area/logs, area/metrics, area/traces, cla: yes

#954 chore: Prepare release 1.13.0
  .env
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#958 chore: Update generated code
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  docs/contributor/governance.md
Labels: lgtm, size/M, cla: yes

#960 fix: Flakiness in the logppipeline tests
  test/e2e/logs_basic_v1alpha1_test.go
  test/e2e/logs_basic_v1beta1_test.go
Labels: kind/bug, lgtm, size/XS, kind/failing-test, cla: yes

#959 fix: Invocation order for setting the status
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/status.go
Labels: lgtm, size/M, cla: yes

#961 fix: Invocation order for setting the status (#959)
  docs/contributor/governance.md
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/status.go
Labels: kind/bug, lgtm, size/M, area/manager, cla: yes

#964 feat: Add GOMEMLIMIT configuration for all telemetry components
  config/manager/manager.yaml
  docs/contributor/telemetry-load-test/README.md
  internal/otelcollector/config/env.go
  internal/otelcollector/config/metric/agent/processors.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/trace/gateway/processors.go
  internal/otelcollector/config/trace/gateway/processors_test.go
  internal/otelcollector/config/trace/gateway/testdata/config.yaml
  internal/resources/common/resources.go
  internal/resources/common/resources_test.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  internal/resources/selfmonitor/resources.go
Labels: kind/feature, size/L, lgtm, area/documentation, area/metrics, area/traces, area/manager, cla: yes

#967 chore: Update kubernetes version for integration tests
  .env
  .github/workflows/branch-integration.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#970 test: Add e2e test for LogPipeline health condition
  .github/workflows/pr-integration.yml
  test/e2e/logs_self_monitor_basic_test.go
Labels: size/L, lgtm, kind/missing-test, area/logs, cla: yes

#936 chore: Bump go to 1.22
  .github/template/setup-golang/action.yaml
  .testcoverage.yml
  go.mod
Labels: lgtm, size/XS, cla: yes

#969 docs: Add pipeline health condition docs
  docs/user/02-logs.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
Labels: lgtm, size/M, cla: yes

#975 feat: Introduce a pipeline_name label to simplify pipeline matching in self-monitor
  controllers/telemetry/logpipeline_controller_test.go
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/output.go
  internal/fluentbit/config/builder/output_test.go
  internal/resources/fluentbit/resources.go
  internal/selfmonitor/alertrules/expr_builder.go
  internal/selfmonitor/alertrules/fluent_bit_rule_builder.go
  internal/selfmonitor/alertrules/otelcol_rule_builder.go
  internal/selfmonitor/alertrules/rules.go
  internal/selfmonitor/alertrules/rules_test.go
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/testdata/config.yaml
  internal/selfmonitor/prober/log_pipeline_prober_test.go
  internal/selfmonitor/prober/otel_pipeline_prober_test.go
  internal/selfmonitor/webhook/handler_test.go
  webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
Labels: kind/feature, size/L, lgtm, area/logs, area/metrics, area/traces, cla: yes

#977 chore: Update Istio module to 1.5.2 for integration tests
  .env
Labels: lgtm, size/XS, cla: yes

#981 feat: Enable pprof for metric agent
  internal/otelcollector/config/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/trace/gateway/config_builder.go
Labels: kind/feature, size/L, lgtm, area/metrics, cla: yes

#983 feat: Enable pprof for metric agent (#981) [Backport for 1.13]
  internal/otelcollector/config/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/trace/gateway/config_builder.go
Labels: size/L, lgtm, cla: yes

#982 feat: Whitelist metrics scraped by self-monitor
  internal/reconciler/telemetry/reconciler.go
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/expr_builder.go
  internal/selfmonitor/config/fluent_bit_rule_builder.go
  internal/selfmonitor/config/otelcol_rule_builder.go
  internal/selfmonitor/config/rules.go
  internal/selfmonitor/config/rules_test.go
  internal/selfmonitor/config/testdata/config.yaml
  internal/selfmonitor/prober/log_pipeline_prober.go
  internal/selfmonitor/prober/otel_pipeline_prober.go
  internal/selfmonitor/webhook/handler.go
Labels: kind/feature, size/L, lgtm, area/logs, area/metrics, area/traces, cla: yes

#984 fix: Revert the changes to invocation order as more corner cases have been identified
  docs/contributor/governance.md
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/status.go
Labels: kind/bug, lgtm, size/M, area/manager, cla: yes

#985 chore: Bump images for 1.13.1 release
  .env
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#986 chore: Switch lint config from disable-all to enable-all
  .golangci.yaml
  go.mod
Labels: lgtm, size/M, cla: yes

#991 chore: Use go.mod in actions
  .github/template/setup-golang/action.yaml
Labels: lgtm, size/XS, cla: yes

#955 test: Telemetry FluentBit-based components error/warning logs
  internal/fluentbit/config/builder/config_builder.go
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/input.go
  internal/fluentbit/config/builder/input_test.go
  internal/overrides/config.go
  internal/reconciler/logpipeline/sync.go
  test/e2e/overrides_test.go
  test/e2e/telemetry_logs_analysis_test.go
  test/testkit/k8s/log_pipeline_v1alpha1.go
  test/testkit/k8s/overrides.go
  webhook/dryrun/file_writer.go
Labels: size/L, lgtm, cla: yes

#992 chore: Enable more linters
  .golangci.yaml
  apis/telemetry/v1alpha1/secret_refs_test.go
  apis/telemetry/v1beta1/secret_refs_test.go
  controllers/telemetry/logpipeline_controller_test.go
  internal/k8sutils/daemonset.go
  internal/k8sutils/daemonset_test.go
  internal/k8sutils/deployment.go
  internal/k8sutils/deployment_test.go
  internal/k8sutils/utils.go
  internal/logger/logger.go
  internal/otelcollector/config/otlpexporter/config_builder.go
  internal/reconciler/logparser/reconciler.go
  internal/reconciler/logparser/status.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/sync.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/telemetry/status.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/status.go
  internal/resources/otelcollector/config.go
  internal/selfmonitor/config/config_builder.go
  internal/webhookcert/ca_cert_provider.go
  internal/webhookcert/server_cert_provider.go
  test/testkit/k8s/objects.go
  test/testkit/matchers/log/log_matchers.go
  test/testkit/matchers/metric/metric_matchers.go
  test/testkit/matchers/trace/trace_matchers.go
  test/testkit/matchers/unmarshal.go
  test/testkit/mocks/backend/backend.go
Labels: size/L, lgtm, cla: yes

#994 feat: Reflect LogPipeline flow health status in the Telemetry status
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/reconciler/telemetry/reconciler.go
  internal/selfmonitor/config/expr_builder.go
  internal/selfmonitor/config/fluent_bit_rule_builder.go
  internal/selfmonitor/config/rules_test.go
  internal/selfmonitor/prober/common.go
  internal/selfmonitor/prober/log_pipeline_prober.go
  internal/selfmonitor/prober/otel_pipeline_prober.go
  internal/selfmonitor/webhook/handler.go
Labels: kind/feature, size/L, lgtm, area/logs, cla: yes

#996 fix: Improve TLS cert validation for LogPipeline
  .gitleaksignore
  docs/user/resources/02-logpipeline.md
  internal/conditions/conditions.go
  internal/conditions/tls_cert_conditions.go
  internal/conditions/tls_cert_conditions_test.go
  internal/reconciler/logpipeline/mocks/tls_cert_validator.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/reconciler/telemetry/status_utils.go
  internal/tls/cert/tls_cert_validator_test.go
  internal/tlscert/tls_cert_validator.go
  internal/tlscert/tls_cert_validator_test.go
Labels: kind/feature, lgtm, size/XXL, area/manager, cla: yes

#1010 chore: Bump telemetry-manager image for 1.14.0 release
  .env
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#956 docs: Fix inconsistencies
  docs/user/03-traces.md
  docs/user/04-metrics.md
Labels: lgtm, size/XS, cla: yes

#1014 feat: Adjusted the FlowHealthy status condition messages
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/trace_components_checker_test.go
Labels: kind/feature, lgtm, size/M, area/logs, area/metrics, area/traces, cla: yes

#1004 fix: Always clear conditions list for TracePipelines, LogPipelines, and LogParsers in first reconciliation
  internal/reconciler/logparser/reconciler.go
  internal/reconciler/logparser/status.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
  test/e2e/logs_basic_v1alpha1_test.go
  test/e2e/logs_basic_v1beta1_test.go
  test/e2e/traces_basic_v1alpha1_test.go
  test/e2e/traces_basic_v1beta1_test.go
  test/testkit/verifiers/logs.go
  test/testkit/verifiers/traces.go
Labels: kind/bug, size/L, lgtm, area/logs, area/traces, cla: yes

#1017 chore: Get rid of envvar utils package
  internal/fluentbit/config/builder/env_var.go
  internal/fluentbit/config/builder/env_var_test.go
  internal/fluentbit/config/builder/output.go
  internal/otelcollector/config/otlpexporter/env_vars.go
  internal/reconciler/logpipeline/sync.go
Labels: lgtm, size/M, kind/chore, area/logs, area/metrics, area/traces, cla: yes

#1025 docs: Fix dynatrace integration example snippet
  docs/user/integration/dynatrace/README.md
Labels: kind/bug, lgtm, size/XS, area/documentation, cla: yes

#1015 test: Improve unit test coverage for status
  controllers/operator/telemetry_controller_test.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/tracepipeline/status_test.go
  internal/testutils/log_pipeline_builder.go
  internal/testutils/metric_pipeline_builder.go
  internal/testutils/pipeline_opts.go
  internal/testutils/trace_pipeline_builder.go
Labels: lgtm, kind/missing-test, size/XXL, area/manager, cla: yes

#1028 chore: Remove orphaned Network Policies cleanup
  internal/reconciler/telemetry/reconciler.go
Labels: lgtm, size/S, kind/chore, area/manager, cla: yes

#1016 feat: Update open-telemetry image version to 0.99.0
  docs/contributor/telemetry-load-test/README.md
  hack/load-tests/run-load-test.sh
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: lgtm, area/documentation, size/S, area/metrics, area/traces, cla: yes

#1022 feat: Clean up OpenCensus
  README.md
  internal/otelcollector/config/trace/gateway/config.go
  internal/otelcollector/config/trace/gateway/config_builder.go
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/testdata/config.yaml
  internal/otelcollector/ports/ports.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/resources/otelcollector/config.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  main.go
Labels: size/L, lgtm, cla: yes

#995 docs: Add ADR for module status metrics
  docs/contributor/arch/011-kymastatsmetrics.md
Labels: size/L, lgtm, cla: yes
