Repository kyma-project/telemetry-manager, pull requests merged in 2024-07, with the labels that each got.

#1230 chore: Exclude test doubles from whitesource checks
  sec-scanners-config.yaml
Labels: area/tests, lgtm, area/ci, kind/chore, cla: yes

#1217 chore: Fix changelogs for non-sequential releases
  .github/workflows/tag-release.yml
  hack/release.sh
Labels: lgtm, size/S, kind/chore, cla: yes, area/release

#1215 fix: Panic on missing TLS configuration parameters
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/shared_types.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/shared_types.go
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  internal/conditions/tls_cert_conditions.go
  internal/conditions/tls_cert_conditions_test.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/testutils/pipeline_opts.go
  internal/tlscert/tls_cert_validator.go
  internal/tlscert/tls_cert_validator_test.go
  test/e2e/logs_mtls_about_to_expire_cert_test.go
  test/e2e/logs_mtls_cert_key_pair_dont_match_test.go
  test/e2e/logs_mtls_expired_cert_test.go
  test/e2e/logs_mtls_invalid_ca_test.go
  test/e2e/logs_mtls_invalid_cert_test.go
  test/e2e/logs_mtls_missing_values_test.go
  test/e2e/logs_mtls_test.go
  test/e2e/logs_secret_rotation_test.go
  test/e2e/logs_unsupported_loki_output_test.go
  test/e2e/metrics_mtls_about_to_expire_cert_test.go
  test/e2e/metrics_mtls_cert_key_pair_dont_match_test.go
  test/e2e/metrics_mtls_expired_cert_test.go
  test/e2e/metrics_mtls_invalid_ca_test.go
  test/e2e/metrics_mtls_invalid_cert_test.go
  test/e2e/metrics_mtls_missing_values_test.go
  test/e2e/metrics_mtls_test.go
  test/e2e/metrics_secret_rotation_test.go
  test/e2e/telemetry_test.go
  test/e2e/traces_mtls_about_to_expire_cert_test.go
  test/e2e/traces_mtls_cert_key_pair_dont_match_test.go
  test/e2e/traces_mtls_expired_cert_test.go
  test/e2e/traces_mtls_invalid_ca_test.go
  test/e2e/traces_mtls_invalid_cert_test.go
  test/e2e/traces_mtls_missing_values_test.go
  test/e2e/traces_mtls_test.go
  test/e2e/traces_secret_rotation_test.go
  test/integration/istio/logs_self_monitor_backpressure_test.go
  test/integration/istio/logs_self_monitor_outage_test.go
  test/integration/istio/metrics_self_monitor_backpressure_test.go
  test/integration/istio/metrics_self_monitor_outage_test.go
  test/integration/istio/traces_self_monitor_backpressure_test.go
  test/integration/istio/traces_self_monitor_outage_test.go
  test/testkit/assert/telemetry.go
Labels: kind/bug, lgtm, size/XXL, area/logs, area/metrics, area/traces, cla: yes

#1227 feat: Collect loadtest results
  .github/workflows/pr-loadtest.yml
  hack/load-tests/matrix_includes.json
  hack/load-tests/run-load-test.sh
  hack/make/provision.mk
  hack/shoot_gcp.yaml
Labels: size/L, lgtm, cla: yes

#1233 chore: Prepare release 1.19
  .env
  config/manager/kustomization.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, cla: yes, area/release

#1239 chore: Prepare release 1.19
  .env
  config/manager/kustomization.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, area/manager, cla: yes

#1235 chore: Bump directory exporter image
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#1240 fix: Gardener cluster setup
  hack/make/provision.mk
  hack/shoot_gcp.yaml
Labels: lgtm, size/XS, cla: yes

#1237 chore: Validate PR labels
  .github/workflows/pr-github-checks.yml
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1245 chore: Add printout for environment
  hack/make/provision.mk
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1248 chore: Refactor TLS validator logic
  internal/tlscert/tls_cert_validator.go
Labels: lgtm, size/M, kind/chore, area/logs, area/metrics, area/traces, cla: yes

#1246 chore: Update istio module deps to 1.8.1
  .env
Labels: area/tests, lgtm, size/XS, kind/chore, cla: yes

#1231 chore: Do not use env prefix for env variables in otel config
  docs/contributor/pocs/assets/otel-log-agent-values.yaml
  docs/contributor/pocs/assets/otel-log-gateway-values.yaml
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
Labels: lgtm, size/S, kind/chore, area/metrics, area/traces, cla: yes

#1242 feat: Self-monitor logs in JSON format
  .github/workflows/pr-github-checks.yml
  internal/reconciler/telemetry/reconciler.go
  internal/resources/selfmonitor/resources.go
  internal/resources/selfmonitor/resources_test.go
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/config_builder_test.go
  internal/selfmonitor/config/testdata/config.yaml
Labels: kind/feature, lgtm, size/M, area/manager, cla: yes

#1241 feat: Allow disabling pod and/or container metrics for runtime input
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  docs/user/04-metrics.md
  docs/user/resources/05-metricpipeline.md
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/testutils/metric_pipeline_builder.go
  test/e2e/metrics_multi_pipeline_namespace_selector_test.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/metrics_runtime_input_resources_test.go
  test/e2e/metrics_runtime_input_test.go
  test/testkit/otel/kubeletstats/metrics.go
Labels: kind/feature, lgtm, size/XL, area/metrics, cla: yes

#1252 chore: Remove leftover of telemetry-trace-collector-internal noise fi…
  internal/otelcollector/config/trace/gateway/drop_noisy_spans.go
  internal/otelcollector/config/trace/gateway/processors_test.go
  internal/otelcollector/config/trace/gateway/testdata/config.yaml
Labels: lgtm, size/S, kind/chore, area/traces, cla: yes

#1257 docs: Fix missing link in dynatrace integration guide
  docs/user/integration/dynatrace/README.md
Labels: lgtm, size/XS, area/documentation, cla: yes, kind/docs

#1251 chore: Check for warnings/errors in telemetry-self-monitor
  test/e2e/telemetry_logs_analysis_test.go
  test/testkit/suite/suite.go
Labels: size/L, lgtm, kind/chore, area/manager, cla: yes

#1247 chore: Sync Markdown to DITA
  docs/user/01-manager.md
  docs/user/02-logs.md
  docs/user/README.md
  docs/user/gateways.md
  docs/user/resources/01-telemetry.md
Labels: size/L, lgtm, area/documentation, kind/chore, cla: yes

#1258 chore: Update to golang 1.22.5
  Dockerfile
  go.mod
  internal/tools/go.mod
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#1256 chore: Update label prefix mapping
  .github/workflows/pr-github-checks.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1260 chore: Remove legacy pipeline cleanup
  internal/reconciler/logparser/reconciler.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
Labels: lgtm, size/M, kind/chore, area/logs, area/traces, cla: yes

#1263 chore: Update pr template
  .github/pull-request-template.md
Labels: lgtm, size/XS, area/documentation, kind/chore, cla: yes

#1262 chore: Fix dependabot config
  .github/dependabot.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1265 chore: Check if milestone is set
  .github/workflows/pr-github-checks.yml
Labels: lgtm, area/documentation, size/S, kind/chore, cla: yes

#1269 chore: Refactor dependency management in LogPipeline/LogParser reconcilers
  .golangci.yaml
  controllers/operator/telemetry_controller.go
  controllers/telemetry/logparser_controller.go
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  internal/reconciler/logparser/reconciler.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  main.go
Labels: size/L, lgtm, kind/chore, area/logs, cla: yes

#1232 feat: Update to kyma-otel-collector 0.104.0-1.20.0
  docs/contributor/benchmarks/README.md
  hack/load-tests/run-load-test.sh
  hack/make/provision.mk
  internal/otelcollector/config/metric/agent/relabel_configs.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  internal/resources/otelcollector/core_pod_spec.go
  main.go
  sec-scanners-config.yaml
  test/testkit/assert/logs.go
  test/testkit/assert/metrics.go
  test/testkit/mocks/backend/deployment.go
Labels: kind/feature, size/L, lgtm, area/dependency, area/metrics, area/traces, cla: yes

#1210 feat: Switch to Istio stable APIs
  .golangci.yaml
  docs/contributor/pocs/otlp-logs.md
  docs/user/03-traces.md
  docs/user/integration/dynatrace/README.md
  docs/user/integration/jaeger/README.md
  docs/user/integration/opentelemetry-demo/README.md
  docs/user/integration/sap-cloud-logging/README.md
  hack/deploy-istio.sh
  hack/load-tests/log-fluentbit-backpressure-config.yaml
  hack/load-tests/metric-agent-backpressure-config.yaml
  hack/load-tests/metric-backpressure-config.yaml
  hack/load-tests/self-monitor-test-setup.yaml
  hack/load-tests/trace-backpressure-config.yaml
  internal/k8sutils/utils.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  main.go
  test/integration/istio/suite_test.go
  test/testkit/k8s/peer_authentication.go
  test/testkit/k8s/virtual_service.go
Labels: kind/feature, size/L, lgtm, area/manager, cla: yes

#1274 chore: Update pr-template
  .github/pull-request-template.md
Labels: lgtm, area/documentation, kind/chore, cla: yes

#1273 chore: Remove test exclusion for ENVvar expansion
  test/e2e/telemetry_logs_analysis_test.go
Labels: area/tests, lgtm, size/XS, kind/chore, cla: yes

#1277 chore: Simplify overrides handler
  controllers/telemetry/logparser_controller.go
  controllers/telemetry/logpipeline_controller.go
  internal/overrides/handler.go
  internal/overrides/handler_test.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  main.go
Labels: size/L, lgtm, kind/chore, area/logs, area/metrics, area/traces, area/manager, cla: yes

#1266 test: Provide better error messages in assertions
  test/e2e/logs_resources_test.go
  test/e2e/logs_self_monitor_healthy_test.go
  test/e2e/metrics_resources_test.go
  test/e2e/metrics_secret_rotation_test.go
  test/e2e/metrics_self_monitor_healthy_test.go
  test/e2e/metrics_service_name_test.go
  test/e2e/suite_test.go
  test/e2e/telemetry_logs_analysis_test.go
  test/e2e/traces_resources_test.go
  test/e2e/traces_secret_rotation_test.go
  test/e2e/traces_self_monitor_healthy_test.go
  test/integration/istio/access_logs_test.go
  test/integration/istio/metrics_otlp_input_test.go
  test/integration/istio/metrics_self_monitor_outage_test.go
  test/integration/istio/traces_test.go
  test/testkit/assert/daemon_set.go
  test/testkit/assert/deployment.go
  test/testkit/assert/secret.go
  test/testkit/assert/traces.go
Labels: size/L, lgtm, kind/flaky-test, area/ci, cla: yes

#1283 chore: Include information about OCC repository in release process
  docs/contributor/releasing.md
Labels: lgtm, size/XS, area/documentation, area/dependency, kind/chore, cla: yes

#1282 chore: Bump images for releasing version 1.20.0
  .env
  config/manager/kustomization.yaml
  hack/load-tests/run-load-test.sh
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: lgtm, size/S, kind/chore, area/manager, cla: yes

#1255 chore: Sync markdown to DITA, volume 2
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/README.md
  docs/user/gateways.md
  docs/user/integration/jaeger/README.md
  docs/user/integration/opentelemetry-demo/README.md
  docs/user/integration/sap-cloud-logging/README.md
Labels: lgtm, size/XXL, area/documentation, kind/chore, cla: yes

#1285 chore: Improve pipeline healthiness assertions in e2e testkit
  test/testkit/assert/logs.go
  test/testkit/assert/metrics.go
  test/testkit/assert/traces.go
Labels: area/tests, lgtm, size/M, kind/chore, cla: yes

#1281 chore: Refactor dependency management in TracePipeline reconciler
  controllers/telemetry/tracepipeline_controller.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/status.go
  main.go
Labels: size/L, lgtm, kind/chore, area/traces, cla: yes

#1284 feat: Use latest kyma-otel-collector image on main branch
  hack/load-tests/run-load-test.sh
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: kind/feature, lgtm, size/XS, area/dependency, cla: yes

#1290 chore: Refactor dependency management in MetricPipeline reconciler
  controllers/telemetry/metricpipeline_controller.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  main.go
Labels: lgtm, size/XL, kind/chore, area/metrics, cla: yes

#1276 chore: Refactor pipeline validation
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/conditions/conditions_test.go
  internal/conditions/tls_cert_conditions.go
  internal/conditions/tls_cert_conditions_test.go
  internal/errortypes/error_types.go
  internal/errortypes/error_types_test.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/stubs/secret_ref_validator.go
  internal/reconciler/logpipeline/validator.go
  internal/reconciler/metricpipeline/mocks/pipeline_lock.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/metricpipeline/stubs/secret_ref_validator.go
  internal/reconciler/metricpipeline/validator.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/trace_components_checker_test.go
  internal/reconciler/tracepipeline/mocks/pipeline_lock.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/stubs/secret_ref_validator.go
  internal/reconciler/tracepipeline/validator.go
  internal/resourcelock/lock.go
  internal/resourcelock/lock_test.go
  internal/secretref/secret_ref.go
  internal/secretref/secret_ref_test.go
Labels: lgtm, size/XXL, kind/chore, area/manager, cla: yes

#1291 chore: Refactor dependency management in Telemetry reconciler
  .mockery.yaml
  controllers/operator/telemetry_controller.go
  internal/reconciler/telemetry/mocks/self_monitor_applier_deleter.go
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/telemetry/status_test.go
  internal/resources/selfmonitor/resources.go
  internal/resources/selfmonitor/resources_test.go
  main.go
Labels: size/L, lgtm, kind/chore, area/manager, cla: yes

#1268 feat: Drop log body after record successfully parsed
  Dockerfile
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1beta1/logpipeline_types.go
  config/busola/logpipeline_busola_extension_cm.yaml
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  docs/user/resources/02-logpipeline.md
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/kubernetes_filter.go
  internal/fluentbit/config/builder/kubernetes_filter_test.go
  webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
Labels: kind/feature, lgtm, size/M, area/documentation, area/logs, cla: yes

#1296 chore: Group dependency bumps into single PR per project
  .github/dependabot.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1254 docs: Improved and consistent diagrams
  docs/user/01-manager.md
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/README.md
  docs/user/assets/gateways-istio.drawio.svg
  docs/user/assets/logs-arch.drawio.svg
  docs/user/assets/logs-pipelines.drawio.svg
  docs/user/assets/logs-resources.drawio.svg
  docs/user/assets/manager-arch.drawio.svg
  docs/user/assets/manager-lifecycle.drawio.svg
  docs/user/assets/manager-resources.drawio.svg
  docs/user/assets/metrics-arch.drawio.svg
  docs/user/assets/metrics-resources.drawio.svg
  docs/user/assets/telemetry-arch.drawio.svg
  docs/user/assets/telemetry-components.drawio.svg
  docs/user/assets/telemetry-stages.drawio.svg
  docs/user/assets/traces-arch.drawio.svg
  docs/user/assets/traces-intro.drawio.svg
  docs/user/assets/traces-resources.drawio.svg
Labels: lgtm, size/XXL, area/documentation, cla: yes, kind/docs

#1304 docs: Edit diagrams
  docs/user/01-manager.md
  docs/user/assets/gateways-istio.drawio.svg
  docs/user/assets/logs-arch.drawio.svg
  docs/user/assets/logs-pipelines.drawio.svg
  docs/user/assets/logs-resources.drawio.svg
  docs/user/assets/manager-arch.drawio.svg
  docs/user/assets/manager-resources.drawio.svg
  docs/user/assets/metrics-arch.drawio.svg
  docs/user/assets/metrics-resources.drawio.svg
  docs/user/assets/telemetry-arch.drawio.svg
  docs/user/assets/telemetry-stages.drawio.svg
  docs/user/assets/traces-arch.drawio.svg
  docs/user/assets/traces-resources.drawio.svg
Labels: lgtm, size/XXL, area/documentation, cla: yes, kind/docs

#1308 chore: Print meaningful runname for load tests
  .github/workflows/pr-loadtest.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1295 feat: Bump OTel Collector to 0.105.0
  docs/contributor/benchmarks/README.md
  hack/load-tests/run-load-test.sh
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: kind/feature, lgtm, size/M, area/metrics, area/traces, cla: yes

#1302 feat: Rename navigation node in kyma dashboard to "telemetry"
  config/busola/logpipeline_busola_extension_cm.yaml
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/busola/tracepipeline_busola_extension_cm.yaml
Labels: kind/feature, lgtm, size/XS, area/manager, cla: yes

#1313 docs: Change enable and disable to add and delete in the telemetry repo
  docs/user/integration/aws-cloudwatch/README.md
  docs/user/integration/dynatrace/README.md
  docs/user/integration/jaeger/README.md
  docs/user/integration/loki/README.md
  docs/user/integration/opentelemetry-demo/README.md
Labels: lgtm, area/documentation, size/S, cla: yes, kind/docs

#1312 chore: Bump images for 1.21.0 release
  .env
  config/manager/kustomization.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, cla: yes, area/release

#1314 docs: Fix minor errors
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
Labels: lgtm, area/documentation, size/S, cla: yes, kind/docs

#1315 docs: Fix typo in diagram
  docs/user/assets/logs-flow.drawio.svg
Labels: lgtm, size/XS, area/documentation, cla: yes, kind/docs

#1316 docs: Fix diagrams
  docs/user/assets/logs-arch.drawio.svg
  docs/user/assets/logs-resources.drawio.svg
  docs/user/assets/metrics-arch.drawio.svg
  docs/user/assets/metrics-resources.drawio.svg
  docs/user/assets/traces-resources.drawio.svg
Labels: lgtm, area/documentation, size/S, cla: yes, kind/docs
