Repository kyma-project/telemetry-manager, pull requests merged in 2024-01, with the labels that each got.

#680 test: Add Telemetry Module integration test for metric and trace gateway endpoints in status
  controllers/operator/telemetry_controller_test.go
Labels: lgtm, size/M, cla: yes

#681 test: Bump Istio module for integration tests
  Makefile
Labels: lgtm, size/XS, cla: yes

#674 feat: Disable scrape metrics by default
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  docs/user/04-metrics.md
  docs/user/resources/05-metricpipeline.md
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processor_drop_filter.go
  internal/otelcollector/config/metric/gateway/processor_drop_filter_test.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/ottlexpr/expressions.go
  internal/testutils/metric_pipeline_builder.go
  test/e2e/metrics_prometheus_input_diagnostic_metric_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/integration/istio/metrics_istio_input_test.go
  test/testkit/kyma/telemetry/metric/pipeline.go
Labels: lgtm, size/XL, area/metrics, cla: yes

#682 feat: Add custom HTTP header prefix for Metric and Trace pipeline OTLP output
  apis/telemetry/v1alpha1/shared_types.go
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/busola/tracepipeline_busola_extension_cm.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  controllers/telemetry/metricpipeline_controller_test.go
  controllers/telemetry/otel_test_helpers.go
  controllers/telemetry/tracepipeline_controller_test.go
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/otelcollector/config/otlpexporter/env_vars.go
Labels: size/L, lgtm, area/metrics, area/traces, cla: yes

#675 fix: Validate and sanitize certificate for logpipeline
  .gitleaksignore
  internal/otelcollector/config/otlpexporter/env_vars.go
  internal/reconciler/logpipeline/sync.go
  internal/tls/validate.go
  internal/tls/validate_test.go
Labels: kind/bug, size/L, lgtm, area/logs, cla: yes

#683 feat: Enrich the service.name attribute if its value follows the "unknown_service:<process.executable.name>" pattern
  docs/user/gateways.md
  internal/otelcollector/config/gatewayprocs/resolve_service_name_proc.go
  internal/otelcollector/config/gatewayprocs/resolve_service_name_proc_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/trace/gateway/testdata/config.yaml
  test/e2e/metrics_service_name_test.go
  test/e2e/traces_service_name_test.go
  test/integration/istio/metrics_otlp_input_test.go
  test/testkit/mocks/servicenamebundle/service_name_bundle.go
  test/testkit/mocks/telemetrygen/telemetrygen.go
Labels: kind/feature, size/L, lgtm, area/metrics, area/traces, cla: yes

#684 chore: Improve release workflow
  .github/workflows/post-release.yml
  Makefile
  config/manager/kustomization.yaml
  docs/contributor/releasing.md
  sec-scanners-config.yaml
Labels: lgtm, size/M, kind/chore, cla: yes, area/release

#687 fix: Restart Fluent Bit after mTLS certificate changed
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
Labels: kind/bug, size/L, lgtm, area/logs, cla: yes

#688 fix: Restart Fluent Bit after mTLS certificate changed
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
Labels: kind/bug, size/L, lgtm, area/logs, cla: yes

#693 test: Fix noisy span filter E2E test
  test/e2e/traces_noisy_span_filter_test.go
  test/testkit/otlp/traces/helpers.go
Labels: area/tests, lgtm, kind/failing-test, size/S, area/traces, cla: yes

#694 fix: Update user docs with new MetricPipeline status
  docs/user/resources/01-telemetry.md
  docs/user/resources/05-metricpipeline.md
Labels: lgtm, size/M, area/documentation, area/metrics, cla: yes

#695 docs: Fixed intendation in istio tracing example
  docs/user/03-traces.md
  docs/user/04-metrics.md
Labels: kind/bug, lgtm, area/documentation, area/metrics, cla: yes

#696 chore: Bump telemetry-manager image for releasing version 1.6.1
  Makefile
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, cla: yes, area/release

#699 chore: Fix dependabot labelling
  .github/dependabot.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#700 feat: Improve regexp for detecting the unknown_service pattern in the service.name attribute
  docs/user/gateways.md
  internal/otelcollector/config/gatewayprocs/resolve_service_name_proc.go
  internal/otelcollector/config/gatewayprocs/resolve_service_name_proc_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/trace/gateway/testdata/config.yaml
  test/e2e/metrics_service_name_test.go
  test/e2e/traces_service_name_test.go
  test/testkit/mocks/servicenamebundle/service_name_bundle.go
Labels: kind/feature, size/L, lgtm, area/metrics, area/traces, cla: yes

#706 docs: Refer to module sizing table on HP
  docs/user/README.md
Labels: kind/feature, lgtm, area/documentation, size/S, cla: yes

#703 docs: Add Integrate Prometheus with Telemetry Manager using Alerting ADR
  docs/contributor/arch/002-fluent-bit-without-file-system-buffer.md
  docs/contributor/arch/003-integrate-prometheus-with-telemetry-manager-using-alerting.md
  docs/contributor/pocs/integrate-prometheus-with-telemetry-manager-using-alerting.md
Labels: size/L, lgtm, area/metrics, area/traces, cla: yes, kind/decision

#709 test: Fix flaky E2E metrics tests (missing Secret)
  test/e2e/metrics_secret_rotation_test.go
  test/e2e/traces_secret_rotation_test.go
Labels: lgtm, kind/flake, size/S, area/metrics, cla: yes

#710 docs: Add alert setup for SAP Cloud Logging
  .mlc.config.json
  docs/user/integration/sap-cloud-logging/README.md
  docs/user/integration/sap-cloud-logging/alert-access-log-ingestion.json
  docs/user/integration/sap-cloud-logging/alert-app-log-ingestion.json
  docs/user/integration/sap-cloud-logging/alert-health.json
  docs/user/integration/sap-cloud-logging/alert-metric-ingestion.json
  docs/user/integration/sap-cloud-logging/alert-trace-ingestion.json
Labels: kind/feature, lgtm, size/XL, area/documentation, cla: yes

#717 chore: Bump telemetry-manage image for releasing 1.7.0
  Makefile
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, cla: yes, area/release

#715 docs: Fix broken values.yaml links
  docs/user/integration/jaeger/README.md
  docs/user/integration/loki/README.md
  docs/user/integration/opentelemetry-demo/README.md
Labels: kind/bug, lgtm, area/documentation, size/S, cla: yes

#718 docs: Use non headless service for loki example
  docs/user/integration/loki/README.md
Labels: kind/bug, lgtm, size/XS, area/documentation, area/logs, cla: yes

#721 docs: Add missing space and separate links to integration guides
  docs/user/README.md
  docs/user/integration/README.md
  docs/user/integration/opentelemetry-demo/README.md
Labels: kind/bug, lgtm, area/documentation, size/S, cla: yes

#666 feat: Update to Otel Collector 0.91.0
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: kind/feature, lgtm, size/XS, area/logs, area/metrics, cla: yes

#708 docs: Improve dynatrace documentation
  docs/user/integration/dynatrace/README.md
  docs/user/integration/dynatrace/secret-example.yaml
Labels: lgtm, size/M, area/documentation, area/traces, cla: yes

#726 docs: Manual performance test for tracing
  docs/contributor/performance-tests/traces/README.md
  docs/contributor/performance-tests/traces/assets/run-load-test.sh
  docs/contributor/performance-tests/traces/assets/trace-backpressure-config.yaml
  docs/contributor/performance-tests/traces/assets/trace-load-test-setup.yaml
  docs/contributor/performance-tests/traces/assets/trace-max-pipeline.yaml
  docs/contributor/performance-tests/traces/assets/trace_perf_test_setup.jpeg
  docs/contributor/performance-tests/traces/assets/values.yaml
Labels: lgtm, size/XL, area/documentation, area/traces, cla: yes

#727 test: Increase test coverage for "internal/resources/otelcollector" pkg
  .testcoverage.yml
  internal/resources/otelcollector/config_test.go
Labels: lgtm, size/M, kind/missing-test, area/metrics, area/traces, cla: yes

#734 docs: Add multi pipeline base test results
  docs/contributor/performance-tests/traces/README.md
  docs/contributor/performance-tests/traces/assets/run-load-test.sh
  docs/contributor/performance-tests/traces/assets/trace_perf_test_setup.drawio.svg
  docs/contributor/performance-tests/traces/assets/trace_perf_test_setup.jpeg
Labels: lgtm, size/M, kind/missing-test, area/documentation, area/traces, cla: yes

#735 fix: Too often reconciliations
  .golangci.yaml
  .testcoverage.yml
  controllers/operator/telemetry_controller.go
  controllers/telemetry/logparser_controller.go
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  internal/k8sutils/daemonset.go
  internal/overrides/handler.go
  internal/overrides/handler_test.go
  internal/predicate/predicates.go
  internal/predicate/predicates_test.go
  internal/reconciler/logparser/reconciler.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/setup/predicates.go
Labels: size/L, lgtm, cla: yes

#741 docs: Remove unintended caption from logpipeline figure
  docs/user/assets/logs-pipelines.drawio.svg
Labels: kind/bug, lgtm, size/XS, area/documentation, cla: yes

#719 feat: Support running in an environment in which all ingress and egress traffic are denied
  .github/workflows/pull-lifecycle.yml
  config/networking/networkpolicy.yaml
  controllers/operator/suite_test.go
  docs/contributor/pocs/integrate-prometheus-with-telemetry-manager-using-alerting.md
  internal/fluentbit/ports/ports.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/telemetry/reconciler.go
  internal/resources/common/resources.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/gateway_test.go
  test/e2e/manager_test.go
  test/e2e/metrics_basic_test.go
  test/e2e/suite_test.go
  test/e2e/telemetry_test.go
  test/e2e/traces_basic_test.go
  test/integration/istio/metrics_otlp_input_test.go
  test/integration/istio/suite_test.go
  test/integration/istio/traces_test.go
  test/testkit/k8s/network_policy.go
  test/testkit/kyma/common_names.go
Labels: kind/feature, size/L, lgtm, area/manager, cla: yes

#742 chore: Switch to stale bot
  .github/stale.yml
  .github/workflows/branch-integration.yml
  .github/workflows/periodic-github-checks.yaml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-github-checks.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-lifecycle.yml
  .github/workflows/slack-message.json
  .github/workflows/tag-release.yml
Labels: size/L, lgtm, area/ci, kind/chore, cla: yes

#744 chore: Bump directory-size-exporter
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, area/logs, cla: yes

#746 test: Fix upgrade test
  .github/workflows/pr-lifecycle.yml
  Makefile
Labels: lgtm, size/XS, kind/failing-test, area/manager, cla: yes

#747 chore: Remove workflow duplicate
  .github/workflows/pull-lifecycle.yml
Labels: lgtm, size/M, kind/chore, area/manager, cla: yes

#748 test: Remove Flake attempts
  Makefile
Labels: lgtm, size/XS, kind/failing-test, area/logs, cla: yes

#749 docs: Fix links
  docs/contributor/governance.md
  docs/user/integration/dynatrace/README.md
Labels: lgtm, size/XS, cla: yes

#723 feat: Upgrade otel image to 0.92.0
  docs/contributor/performance-tests/metrics/README.md
  docs/contributor/performance-tests/traces/README.md
  docs/contributor/performance-tests/traces/assets/style.css
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: kind/feature, lgtm, size/M, area/metrics, area/traces, cla: yes

#750 docs: Update links
  docs/contributor/governance.md
Labels: kind/bug, lgtm, size/XS, cla: yes

#752 docs: Update links
  docs/user/03-traces.md
Labels: kind/bug, lgtm, size/XS, cla: yes

#756 docs: Replace html tags with docsify toggles
  docs/user/integration/loki/README.md
Labels: lgtm, area/documentation, area/logs, cla: yes

#760 chore: Bump istio module to 1.3.0
  Makefile
Labels: area/tests, lgtm, kind/chore, cla: yes
