Repository kyma-project/telemetry-manager, pull requests merged in 2024-09, with the labels that each got.

#1411 docs: Fix some code indentation
  docs/user/integration/sap-cloud-logging/README.md
Labels: lgtm, size/XS, area/documentation, cla: yes, kind/docs

#1398 chore: Prevent kustomization file changes on main branch
  .github/workflows/pr-github-checks.yml
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1416 docs: Update the contributing file
  CONTRIBUTING.md
Labels: lgtm, size/XS, area/documentation, cla: yes, kind/docs

#1413 docs: Improved metrics troubleshooting
  docs/user/04-metrics.md
  docs/user/assets/logs-arch.drawio.svg
Labels: lgtm, size/XL, area/documentation, cla: yes, kind/docs

#1426 feat: Bump OTel image version to 0.108.1
  config/samples/telemetry_v1alpha1_tracepipeline.yaml
  docs/contributor/benchmarks/README.md
  hack/load-tests/metric-load-test-setup.yaml
  hack/load-tests/otel-logs/base/log-generator.yaml
  hack/load-tests/otel-logs/big/log-generator.yaml
  hack/load-tests/run-load-test.sh
  hack/load-tests/self-monitor-test-setup.yaml
  hack/load-tests/trace-load-test-setup.yaml
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
  test/testkit/mocks/telemetrygen/telemetrygen.go
Labels: kind/feature, lgtm, size/M, area/documentation, area/manager, cla: yes

#1420 fix: OTLP endpoint validation for missing or invalid port
  internal/reconciler/logpipeline/stubs/endpoint_validator.go
  internal/reconciler/logpipeline/validator.go
  internal/reconciler/metricpipeline/stubs/endpoint_validator.go
  internal/reconciler/metricpipeline/validator.go
  internal/reconciler/tracepipeline/stubs/endpoint_validator.go
  internal/reconciler/tracepipeline/validator.go
  internal/validators/endpoint/endpoint_validator.go
  internal/validators/endpoint/endpoint_validator_test.go
  test/e2e/metrics_endpoint_invalid_test.go
  test/e2e/metrics_endpoint_port_test.go
  test/e2e/metrics_endpoint_with_path_test.go
  test/e2e/traces_endpoint_invalid_test.go
  test/e2e/traces_endpoint_port_test.go
  test/e2e/traces_endpoint_with_path_test.go
Labels: kind/bug, lgtm, size/XL, area/metrics, area/traces, cla: yes

#1425 fix: Update fluent-bit-config properly
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/sync.go
Labels: kind/bug, lgtm, size/M, area/logs, cla: yes

#1414 docs: Improve dynatrace config to drop empty attributes and resource attributes
  docs/user/integration/dynatrace/exporter-values.yaml
Labels: lgtm, size/XS, area/metrics, cla: yes, kind/docs

#1404 fix: Flaky fluent-bit load test setup
  docs/contributor/benchmarks/README.md
  hack/load-tests/log-fluentbit-test-setup.yaml
  hack/load-tests/run-load-test.sh
Labels: kind/bug, area/tests, lgtm, size/M, area/documentation, cla: yes

#1409 docs: Add ADR for resource attributes enrichment for non-workload metrics
  docs/contributor/arch/013-resource-attributes-enrichment-for-non-workload-metrics.md
  docs/contributor/assets/connectors.drawio.svg
  docs/contributor/assets/multi_pipeline_gateway_with_connectors.yaml
  docs/contributor/assets/node-metric-with-k8sattributes-processor.png
  docs/contributor/assets/single_pipeline_gateway_with_connectors.yaml
Labels: size/L, lgtm, area/metrics, cla: yes, kind/docs

#1430 chore: Update status consistently in all reconcilers
  Dockerfile
  internal/reconciler/logparser/reconciler.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
Labels: size/L, lgtm, kind/chore, area/manager, cla: yes

#1422 feat: Refactor the config for telemetry manager after kymastats changes
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/receivers.go
  internal/otelcollector/config/metric/gateway/receivers_test.go
  internal/resources/otelcollector/rbac.go
  internal/resources/otelcollector/rbac_test.go
  test/e2e/metrics_kyma_input_test.go
  test/testkit/periodic/periodic.go
Labels: kind/feature, size/L, lgtm, area/manager, cla: yes

#1436 docs: ADR Self Monitor Storage
  docs/contributor/arch/014-telemetry-self-monitor-storage.md
Labels: lgtm, area/documentation, size/S, area/manager, cla: yes, kind/docs

#1437 feat: Remove LogPipeline loki output
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/logpipeline_types_test.go
  apis/telemetry/v1alpha1/logpipeline_validation.go
  apis/telemetry/v1alpha1/secret_refs.go
  apis/telemetry/v1alpha1/secret_refs_test.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/logpipeline_types_test.go
  apis/telemetry/v1beta1/logpipeline_validation.go
  apis/telemetry/v1beta1/secret_refs.go
  apis/telemetry/v1beta1/secret_refs_test.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/busola/logpipeline_busola_extension_cm.yaml
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  internal/conditions/conditions.go
  internal/fluentbit/config/builder/rewritetag_filter.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/validator.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/testutils/log_pipeline_builder.go
  test/e2e/logs_unsupported_loki_output_test.go
Labels: kind/feature, area/tests, lgtm, size/XL, area/documentation, area/logs, cla: yes

#1438 chore: Unify Telemetry status reconciliation with the rest of reconcilers
  internal/reconciler/telemetry/reconciler.go
Labels: lgtm, size/M, kind/chore, area/manager, cla: yes

#1441 feat: Split metric OTel pipeline into 3 sub-pipelines using connectors
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/connectors.go
  internal/otelcollector/config/metric/gateway/connectors_test.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/service.go
  internal/otelcollector/config/metric/gateway/service_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/metric/gateway/testdata/config_otlp_disabled.yaml
  internal/otelcollector/config/metric/shared_attributes.go
Labels: kind/feature, lgtm, size/XXL, area/metrics, cla: yes

#1439 chore: Implement allcheckspassed GHA
  .github/workflows/build-image.yml
  .github/workflows/pr-allcheckspassed.yml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-github-checks.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-lifecycle.yml
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1445 chore: Await build-image instead of Build-Image-Success job
  hack/await_workflow.sh
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1449 chore: Rename build-image check name
  hack/await_workflow.sh
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1448 docs: Add load tests results for metric gateway using connectors
  docs/contributor/benchmarks/README.md
Labels: lgtm, size/M, area/metrics, cla: yes, kind/docs

#1447 chore: Ensure naming consistency for GHAs
  .github/workflows/periodic-github-checks.yml
  .github/workflows/pr-all-checks-passed.yml
  .github/workflows/pr-loadtest.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1433 feat: Increase the rsa key size
  config/manager/manager.yaml
  internal/webhookcert/ca_cert_generator.go
  internal/webhookcert/ca_cert_provider.go
  internal/webhookcert/ca_cert_provider_test.go
  internal/webhookcert/key_length_checker.go
  internal/webhookcert/key_length_checker_test.go
Labels: kind/feature, size/L, lgtm, area/manager, cla: yes

#1451 chore: Move self-monitor build to the repo
  .github/workflows/branch-integration.yml
  .github/workflows/build-image.yml
  .github/workflows/build-telemetry-self-monitor-image.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-lifecycle.yml
  dependencies/telemetry-self-monitor/Dockerfile
  dependencies/telemetry-self-monitor/README.md
  dependencies/telemetry-self-monitor/envs
  dependencies/telemetry-self-monitor/plugins.yml
Labels: size/L, lgtm, area/ci, kind/chore, cla: yes

#1446 chore: Bump go to 1.23.1
  Dockerfile
  go.mod
  internal/logger/logger.go
  internal/tools/go.mod
  main.go
Labels: lgtm, size/M, area/dependency, kind/chore, cla: yes

#1452 fix: Reduce CPU memory usage caused by Istio existence check
  .golangci.yaml
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  internal/istiostatus/istio_status_checker.go
  internal/istiostatus/istio_status_checker_test.go
  internal/reconciler/logpipeline/reconciler.go
  main.go
Labels: kind/bug, size/L, lgtm, area/manager, cla: yes

#1455 chore: Update to k8s 1.29
  .env
  .github/workflows/branch-integration.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1460 chore: Replace changed-files with path-filter
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-lifecycle.yml
Labels: size/L, lgtm, area/ci, kind/chore, cla: yes

#1459 chore: Update to fluentbit 3.1.8
  docs/contributor/benchmarks/README.md
  internal/resources/fluentbit/resources.go
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/M, area/dependency, kind/chore, cla: yes

#1461 chore: Improve await_workflow script output
  .github/workflows/build-image.yml
  hack/await_workflow.sh
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1466 docs: Fixed namespaceSelector for dynatrace tutorial
  docs/user/integration/dynatrace/README.md
Labels: lgtm, area/documentation, size/S, cla: yes, kind/docs

#1467 chore: Cleanup unused crd functions
  config/rbac/role.yaml
  controllers/telemetry/metricpipeline_controller.go
  main.go
Labels: lgtm, size/S, kind/chore, area/manager, cla: yes

#1472 chore: Fix workflow not sleeping after output results
  hack/await_workflow.sh
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1458 docs: Add description for acceptable benchmark test results
  docs/contributor/benchmarks/README.md
Labels: area/tests, lgtm, area/documentation, size/S, cla: yes, kind/docs

#1465 feat: Bump OTel image version to 0.109.0
  config/samples/telemetry_v1alpha1_tracepipeline.yaml
  docs/contributor/benchmarks/README.md
  hack/load-tests/metric-load-test-setup.yaml
  hack/load-tests/otel-logs/base/log-generator.yaml
  hack/load-tests/otel-logs/big/log-generator.yaml
  hack/load-tests/run-load-test.sh
  hack/load-tests/self-monitor-test-setup.yaml
  hack/load-tests/trace-load-test-setup.yaml
  main.go
  sec-scanners-config.yaml
  test/e2e/telemetry_logs_analysis_test.go
  test/testkit/mocks/backend/deployment.go
  test/testkit/mocks/telemetrygen/telemetrygen.go
Labels: kind/feature, lgtm, area/documentation, size/S, area/manager, cla: yes

#1473 chore: Convert Istio status checker mocks into stubs
  .mockery.yaml
  internal/reconciler/logpipeline/mocks/istio_status_checker.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/stubs/istio_status_checker.go
  internal/reconciler/metricpipeline/mocks/istio_status_checker.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/stubs/istio_status_checker.go
  internal/reconciler/tracepipeline/mocks/istio_status_checker.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/stubs/istio_status_checker.go
Labels: area/tests, size/L, lgtm, kind/chore, cla: yes

#1474 chore: Bump images for 1.24.0 release
  .env
  config/manager/kustomization.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, cla: yes, area/release

#1471 fix: Revert removal of drop kyma resource attributes
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/service.go
  internal/otelcollector/config/metric/gateway/service_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/metric/gateway/testdata/config_otlp_disabled.yaml
Labels: kind/bug, lgtm, size/M, area/metrics, cla: yes

#1469 feat: Make v1alpha1 LogPipeline input disableable
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  docs/user/resources/02-logpipeline.md
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/testutils/log_pipeline_builder.go
  test/e2e/logs_disabled_input_test.go
Labels: kind/feature, size/L, lgtm, area/logs, cla: yes

#1453 feat: Enable resource status for telemetry resources
  config/development/kustomization.yaml
  controllers/telemetry/metricpipeline_controller.go
  docs/user/04-metrics.md
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/receivers_test.go
  internal/otelcollector/config/metric/gateway/service.go
  internal/otelcollector/config/metric/gateway/service_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/metric/gateway/testdata/config_otlp_disabled.yaml
  internal/reconciler/commonstatus/checker.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/resources/otelcollector/rbac.go
  internal/resources/otelcollector/rbac_test.go
  main.go
  test/e2e/metrics_kyma_input_test.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/metrics_runtime_input_test.go
  test/testkit/assert/metrics.go
  test/testkit/otel/kymastats/metrics.go
Labels: kind/feature, lgtm, size/XL, area/ci, area/metrics, cla: yes

#1450 feat: Add a selector for runtime node metrics
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  docs/user/04-metrics.md
  docs/user/resources/05-metricpipeline.md
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/processors.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/receivers.go
  internal/otelcollector/config/metric/gateway/receivers_test.go
  internal/otelcollector/config/metric/gateway/service.go
  internal/otelcollector/config/metric/gateway/service_test.go
  internal/otelcollector/config/processors.go
  internal/testutils/metric_pipeline_builder.go
  test/e2e/metrics_multi_pipeline_namespace_selector_test.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/metrics_runtime_input_resources_test.go
  test/e2e/metrics_runtime_input_test.go
  test/testkit/matchers/metric/metric_matchers.go
  test/testkit/metrics/runtime/container.go
  test/testkit/metrics/runtime/default.go
  test/testkit/metrics/runtime/node.go
  test/testkit/metrics/runtime/pod.go
  test/testkit/otel/k8scluster/metrics.go
  test/testkit/otel/kubeletstats/metrics.go
  test/testkit/otel/kymastats/metrics.go
Labels: kind/feature, lgtm, size/XXL, area/metrics, cla: yes

#1477 feat: Add Node metrics selector to the UI
  config/busola/metricpipeline_busola_extension_cm.yaml
Labels: kind/feature, lgtm, size/XS, area/metrics, cla: yes

#1463 feat: Add conversion webhook config to dev CRD variant
  .testcoverage.yml
  apis/telemetry/v1alpha1/logpipeline_conversion.go
  apis/telemetry/v1alpha1/logpipeline_conversion_test.go
  apis/telemetry/v1beta1/logpipeline_conversion.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/logpipeline_types_test.go
  apis/telemetry/v1beta1/logpipeline_validation.go
  apis/telemetry/v1beta1/logpipeline_validation_test.go
  apis/telemetry/v1beta1/secret_refs_test.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/crd/patches/cainjection_in_logpipelines.yaml
  config/crd/patches/cainjection_in_operator_telemetries.yaml
  config/crd/patches/cainjection_in_telemetry_logparsers.yaml
  config/crd/patches/cainjection_in_telemetry_metricpipelines.yaml
  config/crd/patches/cainjection_in_telemetry_tracepipelines.yaml
  config/crd/patches/webhook_in_telemetry_logparsers.yaml
  config/crd/patches/webhook_in_telemetry_logpipelines.yaml
  config/crd/patches/webhook_in_telemetry_metricpipelines.yaml
  config/crd/patches/webhook_in_telemetry_tracepipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/kustomization.yaml
  config/rbac/role.yaml
  go.mod
  internal/webhookcert/resources.go
  internal/webhookcert/webhook_cert.go
  internal/webhookcert/webhook_cert_test.go
  main.go
  test/e2e/logs_basic_v1beta1_test.go
  test/e2e/logs_version_conversion_test.go
Labels: kind/feature, lgtm, size/XXL, area/logs, cla: yes

#1478 chore: Add a check for adjusting Busola in the PR template
  .github/pull-request-template.md
Labels: lgtm, size/XS, area/documentation, kind/chore, cla: yes
