Repository kyma-project/telemetry-manager, pull requests merged in 2024-11, with the labels that each got.

#1586 fix: Bump memory limit for directory size exporter
  internal/resources/fluentbit/resources.go
Labels: kind/bug, lgtm, size/XS, area/logs, cla: yes

#1578 chore: Secretrefs refactoring
  .golangci.yaml
  .testcoverage.yml
  apis/telemetry/v1alpha1/secret_refs.go
  apis/telemetry/v1alpha1/secret_refs_test.go
  apis/telemetry/v1beta1/secret_refs.go
  apis/telemetry/v1beta1/secret_refs_test.go
  docs/user/integration/sap-cloud-logging/README.md
  internal/reconciler/logpipeline/fluentbit/sync.go
  internal/reconciler/logpipeline/fluentbit/validator.go
  internal/reconciler/logpipeline/stubs/secret_ref_validator.go
  internal/reconciler/metricpipeline/stubs/secret_ref_validator.go
  internal/reconciler/metricpipeline/validator.go
  internal/reconciler/tracepipeline/stubs/secret_ref_validator.go
  internal/reconciler/tracepipeline/validator.go
  internal/validators/secretref/secret_ref.go
  internal/validators/secretref/secret_ref_test.go
Labels: lgtm, size/XXL, kind/chore, area/logs, area/metrics, area/traces, cla: yes

#1589 chore: Bump images for 1.27.0 release
  .env
  config/manager/kustomization.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, area/manager, cla: yes

#1591 chore: Build image for prometheus 2.53.3
  dependencies/telemetry-self-monitor/envs
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#1590 docs: Update outdated variable name in release process
  docs/contributor/releasing.md
Labels: size/XS, cla: yes, area/release, kind/docs

#1575 feat: Remove app-pods-secure scrape job
  docs/user/04-metrics.md
  internal/otelcollector/config/metric/agent/prometheus_receiver.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  test/integration/istio/metrics_prometheus_input_test.go
  test/testkit/mocks/prommetricgen/metric_producer.go
Labels: kind/feature, size/L, lgtm, area/metrics, cla: yes

#1594 chore: Refactor logpipeline and logparser validators
  .golangci.yaml
  .testcoverage.yml
  Makefile
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/logpipeline_validation_test.go
  apis/telemetry/v1alpha1/mode_string.go
  apis/telemetry/v1beta1/logpipeline_validation.go
  apis/telemetry/v1beta1/logpipeline_validation_test.go
  apis/telemetry/v1beta1/mode_string.go
  internal/fluentbit/config/builder/config_builder.go
  internal/reconciler/logpipeline/fluentbit/reconciler.go
  internal/reconciler/logpipeline/otel/reconciler.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/utils/pipelines/logpipeline_mode.go
  internal/utils/pipelines/logpipelinemode_string.go
  webhook/logparser/validation/spec_validator.go
  webhook/logparser/webhook.go
  webhook/logpipeline/validation/spec_validator.go
  webhook/logpipeline/validation/validator_test.go
  webhook/logpipeline/webhook.go
Labels: lgtm, size/XXL, kind/chore, area/logs, cla: yes

#1597 chore: Move remaining api-specific logic to the utils package
  .golangci.yaml
  .testcoverage.yml
  Makefile
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/logpipeline_types_test.go
  apis/telemetry/v1alpha1/shared_types.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/logpipeline_types_test.go
  apis/telemetry/v1beta1/shared_types.go
  controllers/telemetry/logpipeline_controller.go
  internal/fluentbit/config/builder/config_builder.go
  internal/fluentbit/config/builder/output.go
  internal/fluentbit/config/builder/rewritetag_filter.go
  internal/otelcollector/config/otlpexporter/config_builder.go
  internal/otelcollector/config/otlpexporter/env_vars.go
  internal/reconciler/logpipeline/fluentbit/reconciler.go
  internal/reconciler/logpipeline/fluentbit/reconciler_test.go
  internal/reconciler/logpipeline/fluentbit/status.go
  internal/reconciler/logpipeline/fluentbit/sync.go
  internal/reconciler/logpipeline/fluentbit/sync_test.go
  internal/reconciler/logpipeline/otel/reconciler.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/utils/logpipeline/logpipeline.go
  internal/utils/logpipeline/logpipeline_test.go
  internal/utils/logpipeline/mode_string.go
  internal/utils/pipelines/logpipeline_mode.go
  internal/utils/pipelines/logpipelinemode_string.go
  internal/utils/sharedtypes/sharedtypes.go
  webhook/logpipeline/validation/spec_validator.go
  webhook/logpipeline/webhook.go
Labels: lgtm, size/XL, kind/chore, area/logs, area/metrics, area/traces, cla: yes

#1592 chore: Update to prometheus 2.53.3
  docs/contributor/benchmarks/README.md
  main.go
  sec-scanners-config.yaml
Labels: size/XS, kind/chore, area/manager, cla: yes

#1601 fix: Bump CPU limit for the directory size exporter container
  internal/resources/fluentbit/resources.go
Labels: kind/bug, lgtm, area/logs

#1596 docs: Add ADR for leader elector as extension
  docs/contributor/arch/013-leader-receiver-creator-as-extension.md
Labels: lgtm, size/M, area/metrics, cla: yes, kind/docs

#1607 chore: Flatten validating webhook packages
  .golangci.yaml
  .mockery.yaml
  internal/utils/test/log_pipeline_builder.go
  main.go
  webhook/logparser/spec_validator.go
  webhook/logparser/webhook.go
  webhook/logpipeline/files_validator.go
  webhook/logpipeline/files_validator_test.go
  webhook/logpipeline/handler.go
  webhook/logpipeline/handler_test.go
  webhook/logpipeline/max_pipelines_validator.go
  webhook/logpipeline/max_pipelines_validator_test.go
  webhook/logpipeline/spec_validator.go
  webhook/logpipeline/spec_validator_test.go
  webhook/logpipeline/validation/files_validator_test.go
  webhook/logpipeline/validation/max_pipelines_validator.go
  webhook/logpipeline/validation/max_pipelines_validator_test.go
  webhook/logpipeline/validation/mocks/files_validator.go
  webhook/logpipeline/validation/mocks/max_pipelines_validator.go
  webhook/logpipeline/validation/mocks/variables_validator.go
  webhook/logpipeline/validation/validator_test.go
  webhook/logpipeline/validation/variable_validator_test.go
  webhook/logpipeline/variable_validator.go
  webhook/logpipeline/variable_validator_test.go
  webhook/logpipeline/webhook.go
  webhook/logpipeline/webhook_test.go
Labels: lgtm, size/XXL, kind/chore, area/logs, cla: yes

#1608 feat: Enable by default all resource metrics when runtime input in enabled in MetricPipeline
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  docs/user/04-metrics.md
  docs/user/resources/05-metricpipeline.md
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  internal/otelcollector/config/metric/gateway/service_test.go
  internal/otelcollector/config/metric/input_enabled.go
  internal/utils/test/metric_pipeline_builder.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_runtime_input_resources_test.go
  test/e2e/metrics_runtime_input_test.go
  test/testkit/metrics/runtime/default.go
Labels: kind/feature, lgtm, size/XXL, area/documentation, area/metrics, cla: yes

#1612 fix: Adjusted noisy trace filter to new istio reality
  internal/otelcollector/config/trace/gateway/drop_noisy_spans.go
  internal/otelcollector/config/trace/gateway/testdata/config.yaml
  test/e2e/traces_noisy_span_filter_test.go
  test/integration/istio/traces_test.go
Labels: kind/bug, lgtm, size/M, area/traces, cla: yes

#1618 chore: Bump images for 1.28.0 release
  .env
  config/manager/kustomization.yaml
  main.go
  sec-scanners-config.yaml
Labels: size/S, kind/chore, cla: yes, area/release

#1520 docs: Custom OTTL with OpenTelemetry-based Telemetry Pipelines
  docs/contributor/arch/016-transform-filter-support-for-telemetry-pipelines.md
Labels: size/L, lgtm, area/documentation, area/metrics, area/traces, cla: yes, kind/docs

#1606 chore: Separate RBAC declarations by component for clearer access requirements
  internal/resources/otelcollector/rbac.go
  internal/resources/otelcollector/rbac_test.go
Labels: size/L, kind/chore, area/metrics, area/traces, cla: yes

#1623 docs: Replace Remedy with Solution
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
Labels: size/M, area/documentation, cla: yes, kind/docs

#1613 feat: Add mutating webhook and defaulter for all signal types
  .golangci.yaml
  .testcoverage.yml
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/shared_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/shared_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/development/kustomization.yaml
  config/development/webhook-patches.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/operator/telemetry_controller.go
  internal/reconciler/telemetry/reconciler.go
  internal/utils/test/metric_pipeline_builder.go
  internal/webhookcert/resources.go
  internal/webhookcert/webhook_cert.go
  internal/webhookcert/webhook_cert_test.go
  main.go
  webhook/logparser/v1alpha1/spec_validator.go
  webhook/logparser/v1alpha1/webhook.go
  webhook/logpipeline/v1alpha1/defaulter.go
  webhook/logpipeline/v1alpha1/defaulter_test.go
  webhook/logpipeline/v1alpha1/files_validator.go
  webhook/logpipeline/v1alpha1/files_validator_test.go
  webhook/logpipeline/v1alpha1/handler.go
  webhook/logpipeline/v1alpha1/handler_test.go
  webhook/logpipeline/v1alpha1/max_pipelines_validator.go
  webhook/logpipeline/v1alpha1/max_pipelines_validator_test.go
  webhook/logpipeline/v1alpha1/spec_validator.go
  webhook/logpipeline/v1alpha1/spec_validator_test.go
  webhook/logpipeline/v1alpha1/variable_validator.go
  webhook/logpipeline/v1alpha1/variable_validator_test.go
  webhook/logpipeline/v1beta1/defaulter.go
  webhook/logpipeline/v1beta1/defaulter_test.go
  webhook/metricpipeline/v1alpha1/defaulter.go
  webhook/metricpipeline/v1alpha1/defaulter_test.go
  webhook/metricpipeline/v1beta1/defaulter.go
  webhook/metricpipeline/v1beta1/defaulter_test.go
  webhook/tracepipeline/v1alpha1/defaulter.go
  webhook/tracepipeline/v1alpha1/defaulter_test.go
  webhook/tracepipeline/v1beta1/defaulter.go
  webhook/tracepipeline/v1beta1/defaulter_test.go
Labels: kind/feature, lgtm, size/XXL, area/logs, area/metrics, area/traces, area/manager, cla: yes

#1633 chore: Simplify admission webhook setup
  .testcoverage.yml
  main.go
  webhook/logparser/v1alpha1/setup.go
  webhook/logparser/v1alpha1/validate_handler.go
  webhook/logpipeline/v1alpha1/defaulter.go
  webhook/logpipeline/v1alpha1/defaulter_test.go
  webhook/logpipeline/v1alpha1/files_validator_test.go
  webhook/logpipeline/v1alpha1/max_pipelines_validator_test.go
  webhook/logpipeline/v1alpha1/setup.go
  webhook/logpipeline/v1alpha1/spec_validator_test.go
  webhook/logpipeline/v1alpha1/validate_handler.go
  webhook/logpipeline/v1alpha1/validate_handler_test.go
  webhook/logpipeline/v1alpha1/variable_validator_test.go
  webhook/logpipeline/v1beta1/defaulter.go
  webhook/logpipeline/v1beta1/defaulter_test.go
  webhook/logpipeline/v1beta1/setup.go
  webhook/metricpipeline/v1alpha1/defaulter.go
  webhook/metricpipeline/v1alpha1/defaulter_test.go
  webhook/metricpipeline/v1alpha1/setup.go
  webhook/metricpipeline/v1beta1/defaulter.go
  webhook/metricpipeline/v1beta1/defaulter_test.go
  webhook/metricpipeline/v1beta1/setup.go
  webhook/tracepipeline/v1alpha1/defaulter.go
  webhook/tracepipeline/v1alpha1/defaulter_test.go
  webhook/tracepipeline/v1alpha1/setup.go
  webhook/tracepipeline/v1beta1/defaulter.go
  webhook/tracepipeline/v1beta1/defaulter_test.go
  webhook/tracepipeline/v1beta1/setup.go
Labels: size/L, lgtm, kind/chore, area/manager, cla: yes

#1639 chore: Make all-checks-passed run on re-requesting jobs
  .github/workflows/pr-all-checks-passed.yml
Labels: size/XS, area/ci, kind/chore, cla: yes

#1632 feat: Bump OTel image version to 0.114.0
  config/samples/telemetry_v1alpha1_tracepipeline.yaml
  docs/contributor/benchmarks/README.md
  hack/deploy-istio.sh
  hack/load-tests/log-fluentbit-test-setup.yaml
  hack/load-tests/metric-agent-test-setup.yaml
  hack/load-tests/metric-load-test-setup.yaml
  hack/load-tests/otel-logs/base/log-generator.yaml
  hack/load-tests/otel-logs/big/log-generator.yaml
  hack/load-tests/prometheus-setup.yaml
  hack/load-tests/run-load-test.sh
  hack/load-tests/self-monitor-test-setup.yaml
  hack/load-tests/trace-load-test-setup.yaml
  hack/load-tests/values.yaml
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
  test/testkit/mocks/telemetrygen/telemetrygen.go
Labels: kind/feature, size/L, lgtm, area/metrics, area/traces, area/manager, cla: yes

#1642 chore: Update prometheus to 3.0.1
  dependencies/telemetry-self-monitor/envs
Labels: size/XS, kind/chore, area/manager, cla: yes

#1643 chore: Update self-monitor to prometheus 3.0.1
  docs/contributor/benchmarks/README.md
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#1645 chore: Update fluentbit image to 3.2.2
  external-images.yaml
Labels: lgtm, size/XS, kind/chore, area/logs, cla: yes
