Repository kyma-project/telemetry-manager, pull requests merged in 2024-02, with the labels that each got.

#757 docs: Add manual metric load test
  docs/contributor/performance-tests/metrics/README.md
  docs/contributor/performance-tests/traces/README.md
  docs/contributor/performance-tests/traces/assets/run-load-test.sh
  docs/contributor/performance-tests/traces/assets/trace-backpressure-config.yaml
  docs/contributor/telemetry-load-test/README.md
  docs/contributor/telemetry-load-test/assets/metric-agent-test-setup.yaml
  docs/contributor/telemetry-load-test/assets/metric-backpressure-config.yaml
  docs/contributor/telemetry-load-test/assets/metric-load-test-setup.yaml
  docs/contributor/telemetry-load-test/assets/metric-max-pipeline.yaml
  docs/contributor/telemetry-load-test/assets/metric_perf_test_setup.drawio.svg
  docs/contributor/telemetry-load-test/assets/run-load-test.sh
  docs/contributor/telemetry-load-test/assets/style.css
  docs/contributor/telemetry-load-test/assets/trace-backpressure-config.yaml
  docs/contributor/telemetry-load-test/assets/trace-load-test-setup.yaml
  docs/contributor/telemetry-load-test/assets/trace-max-pipeline.yaml
  docs/contributor/telemetry-load-test/assets/trace_perf_test_setup.drawio.svg
  docs/contributor/telemetry-load-test/assets/values.yaml
Labels: lgtm, size/XXL, area/documentation, area/metrics, cla: yes

#761 docs: ADR: Consolidate Telemetry Pipeline Statuses
  docs/contributor/arch/004-consolidate-pipeline-statuses.md
Labels: lgtm, size/M, area/logs, area/traces, cla: yes, kind/decision

#762 docs: Add OTLP Logs PoC documentation
  docs/contributor/assets/otel-logs-values.yaml
  docs/contributor/pocs/otlp-logs.md
Labels: size/L, lgtm, cla: yes

#764 docs: ADR LogPipeline OTLP Output
  docs/contributor/arch/007-log-pipeline-otlp-output.md
Labels: lgtm, size/M, area/logs, cla: yes, kind/decision

#758 docs: ADR: Do not make prometheus part of the Istio service mesh
  docs/contributor/arch/005-do-not-make-prometheus-part of-the-istio-service-mesh.md
Labels: lgtm, size/M, area/logs, area/metrics, area/traces, cla: yes, kind/decision

#766 docs: Fix minor errors
  docs/user/01-manager.md
  docs/user/README.md
Labels: kind/bug, lgtm, size/XS, area/documentation, area/metrics, cla: yes

#768 chore: Simplify pprof server set up
  main.go
Labels: lgtm, size/S, kind/chore, area/manager, cla: yes

#754 chore: Test compatibility with next k8s version 1.28
  .github/workflows/branch-integration.yml
  Makefile
Labels: lgtm, area/dependency, size/S, kind/chore, cla: yes

#774 chore: Fix length of cluster for gardener integration test
  Makefile
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#775 chore: Fix env variable injection for gardener integration test
  .github/workflows/branch-integration.yml
  Makefile
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#759 docs: Add integration guide for Amazon CloudWatch and AWS X-Ray
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/integration/README.md
  docs/user/integration/assets/cloudwatch.drawio.svg
  docs/user/integration/aws-cloudwatch/README.md
  docs/user/integration/aws-cloudwatch/aws-otel.yaml
  docs/user/integration/jaeger/README.md
  docs/user/integration/loki/README.md
  docs/user/integration/opentelemetry-demo/README.md
Labels: kind/feature, size/L, lgtm, area/documentation, cla: yes

#773 chore: Update OTEL image version to 0.93
  docs/contributor/telemetry-load-test/README.md
  docs/contributor/telemetry-load-test/assets/metric-agent-backpressure-config.yaml
  docs/contributor/telemetry-load-test/assets/run-load-test.sh
  internal/otelcollector/config/metric/agent/processors.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: size/L, lgtm, area/documentation, area/metrics, area/traces, cla: yes

#779 fix: Exclude system namespaces correctly
  internal/fluentbit/config/builder/input.go
  internal/fluentbit/config/builder/input_test.go
  test/e2e/logs_exclude_namespaces_test.go
  test/e2e/logs_include_namespaces_test.go
  test/testkit/k8s/log_pipeline.go
  test/testkit/kyma/common_names.go
  test/testkit/matchers/log/log_matchers.go
Labels: size/L, lgtm, cla: yes

#784 docs: Fix a link
  docs/user/integration/aws-cloudwatch/README.md
Labels: kind/bug, lgtm, size/XS, cla: yes

#751 docs: Add Cloud Logging Dashboards for metrics
  docs/user/integration/sap-cloud-logging/README.md
  docs/user/integration/sap-cloud-logging/dashboard-istio.ndjson
  docs/user/integration/sap-cloud-logging/dashboard-runtime.ndjson
Labels: kind/feature, lgtm, size/M, area/documentation, cla: yes

#785 chore: Update pr-docu-checks.yml
  .github/workflows/pr-docu-checks.yml
Labels: lgtm, size/S, cla: yes

#790 docs: Fix link to Dynatrace docs about aggregation temporality
  docs/user/integration/dynatrace/README.md
Labels: lgtm, size/XS, cla: yes

#791 chore: Bump operator image for 1.9.0 release
  Makefile
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#794 feat: Update Fluent-Bit image version to 2.2.2
  config/samples/http-mockserver.yaml
  main.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/XS, area/logs, cla: yes

#795 chore: Bump Istio module to 1.3.1 for integration tests
  Makefile
Labels: lgtm, area/dependency, kind/chore, cla: yes

#788 docs: Manual performance test for logs
  docs/contributor/pocs/performance-tests/metrics/assets/agent-multi-receiver-accepted.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/agent-multi-receiver-cpu.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/agent-multi-receiver-memory.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/agent-multi-receiver-refused.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/max-pod-agent-accepted-metrics.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/max-pod-agent-cpu.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/max-pod-agent-memory.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/max-pod-gateway-accepted-metrics.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/max-pod-gateway-sent-metrics.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/max-pod-k8s-api.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/overall-peak-cpu.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/overall-peak-memory.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/overall-peak-metric-point-refused.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/overall-peak-metric-point.jpg
  docs/contributor/pocs/performance-tests/metrics/assets/single-target-peak-metric-point.jpg
  docs/contributor/pocs/performance-tests/metrics/metrics.md
  docs/contributor/telemetry-load-test/README.md
  docs/contributor/telemetry-load-test/assets/log-fluentbit-backpressure-config.yaml
  docs/contributor/telemetry-load-test/assets/log-fluentbit-max-pipeline.yaml
  docs/contributor/telemetry-load-test/assets/log-fluentbit-test-setup.yaml
  docs/contributor/telemetry-load-test/assets/log_perf_test_setup.drawio.svg
  docs/contributor/telemetry-load-test/assets/run-load-test.sh
Labels: lgtm, kind/missing-test, size/XL, area/documentation, area/logs, cla: yes

#796 feat: Update OTEL image version to 0.94.0
  docs/contributor/telemetry-load-test/README.md
  docs/contributor/telemetry-load-test/assets/log-fluentbit-test-setup.yaml
  docs/contributor/telemetry-load-test/assets/metric-agent-test-setup.yaml
  docs/contributor/telemetry-load-test/assets/metric-load-test-setup.yaml
  docs/contributor/telemetry-load-test/assets/trace-load-test-setup.yaml
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: lgtm, area/documentation, size/S, kind/chore, area/metrics, area/traces, cla: yes

#803 feat: Align existing status API of TracePipeline, LogPipeline and LogParser with syntactical Kubernetes conventions
  apis/telemetry/v1alpha1/logparser_types.go
  apis/telemetry/v1alpha1/logparsers_types_test.go
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/logpipeline_types_test.go
  apis/telemetry/v1alpha1/tracepipeline_types.go
  apis/telemetry/v1alpha1/tracepipeline_types_test.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/telemetry.kyma-project.io_logparsers.yaml
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  controllers/operator/telemetry_controller_test.go
  controllers/telemetry/logpipeline_controller_test.go
  docs/user/resources/02-logpipeline.md
  docs/user/resources/03-logparser.md
  docs/user/resources/04-tracepipeline.md
  internal/conditions/conditions.go
  internal/reconciler/logparser/status.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/trace_components_checker.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
  internal/testutils/log_pipeline_builder.go
  internal/testutils/trace_pipeline_builder.go
  test/integration/istio/access_logs_test.go
  test/testkit/verifiers/logs.go
  test/testkit/verifiers/traces.go
Labels: kind/feature, lgtm, size/XXL, area/logs, area/traces, cla: yes

#810 docs: Say IN a cluster not ON a cluster
  docs/contributor/pocs/performance-tests/metrics/metrics.md
  docs/user/integration/dynatrace/README.md
  docs/user/integration/opentelemetry-demo/README.md
Labels: lgtm, size/XS, cla: yes

#793 docs: Document GOMEMLIMIT with telemetry components
  docs/contributor/pocs/assets/with-gomemlimit-oom.jpg
  docs/contributor/pocs/assets/with-gomemlimit.jpg
  docs/contributor/pocs/assets/without-gomemlimit.jpg
  docs/contributor/pocs/gomemlimit-telemetry-memory.md
Labels: lgtm, size/M, area/documentation, cla: yes

#811 feat: Rename telemetry-operator to telemetry-manager
  .github/template/finalize-test/action.yaml
  .github/template/prepare-test/action.yaml
  .github/workflows/pr-lifecycle.yml
  Makefile
  README.md
  config/default/kustomization.yaml
  config/development/kustomization.yaml
  config/manager/manager.yaml
  config/manager/metrics_service.yaml
  config/networking/networkpolicy.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/operator_v1alpha1_telemetry.yaml
  config/samples/telemetry_v1alpha1_metricpipeline.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  docs/contributor/arch/005-do-not-make-prometheus-part of-the-istio-service-mesh.md
  docs/contributor/pocs/integrate-prometheus-with-telemetry-manager-using-alerting.md
  docs/contributor/pocs/performance-tests/metrics/metrics.md
  docs/contributor/troubleshooting.md
  docs/user/assets/logs-resources.drawio.svg
  docs/user/assets/manager-lifecycle.drawio.svg
  docs/user/assets/metrics-resources.drawio.svg
  docs/user/assets/traces-resources.drawio.svg
  internal/reconciler/telemetry/reconciler.go
  internal/webhookcert/webhook_cert.go
  internal/webhookcert/webhook_cert_test.go
  main.go
  test/e2e/assets/tracing-tests.svg
  test/e2e/manager_test.go
  test/e2e/overrides_test.go
  test/e2e/telemetry_test.go
  test/testkit/kyma/common_names.go
Labels: kind/feature, size/L, lgtm, area/documentation, area/manager, cla: yes

#815 feat: Update OTEL collector image version to 0.95
  docs/contributor/telemetry-load-test/README.md
  docs/contributor/telemetry-load-test/assets/log-fluentbit-test-setup.yaml
  docs/contributor/telemetry-load-test/assets/metric-agent-test-setup.yaml
  docs/contributor/telemetry-load-test/assets/metric-load-test-setup.yaml
  docs/contributor/telemetry-load-test/assets/trace-load-test-setup.yaml
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: area/tests, lgtm, area/documentation, size/S, kind/chore, area/metrics, area/traces, cla: yes

#802 docs: ADR: Telemetry Flow Healthiness Status API
  docs/contributor/arch/008-telemetry-flow-healthiness-status-api.md
  docs/contributor/assets/otel-collector-data-flow.svg
Labels: size/L, lgtm, cla: yes

#814 docs: Highlight the need for Istio configuration to get access logs
  docs/user/integration/sap-cloud-logging/README.md
Labels: kind/bug, lgtm, size/XS, area/documentation, cla: yes

#827 fix: Change manager deployment name in upgrade test
  .github/workflows/pr-lifecycle.yml
Labels: area/tests, lgtm, kind/failing-test, size/S, cla: yes

#829 docs: Add an empty line before tables
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
Labels: lgtm, size/XS, cla: yes

#828 docs: Fix warning and other rendering errors
  docs/user/integration/sap-cloud-logging/README.md
Labels: kind/bug, lgtm, area/documentation, size/S, area/logs, cla: yes

#835 fix: Increase Fluent Bit Kubernetes filter buffer
  controllers/telemetry/logpipeline_controller_test.go
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/kubernetes_filter.go
  internal/fluentbit/config/builder/kubernetes_filter_test.go
  webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
Labels: kind/bug, lgtm, size/XS, area/logs, cla: yes

#816 feat: Deploy self-monitor via telemetry manager
  .testcoverage.yml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/operator/suite_test.go
  internal/k8sutils/utils.go
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/relabel_configs.go
  internal/prometheus/config.go
  internal/reconciler/telemetry/reconciler.go
  internal/resources/common/resources.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/core_pod_spec.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  internal/resources/selfmonitor/resources.go
  internal/resources/selfmonitor/resources_test.go
  internal/selfmonitor/config/config.go
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/config_builder_test.go
  internal/selfmonitor/config/testdata/config.yaml
  internal/selfmonitor/ports/ports.go
  main.go
Labels: kind/feature, lgtm, size/XXL, area/logs, area/metrics, area/traces, cla: yes

#837 fix: Change manager deployment name in upgrade test
  .github/workflows/pr-lifecycle.yml
Labels: area/tests, lgtm, kind/failing-test, size/S, cla: yes

#836 fix: Increase Fluent Bit Kubernetes filter buffer
  controllers/telemetry/logpipeline_controller_test.go
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/kubernetes_filter.go
  internal/fluentbit/config/builder/kubernetes_filter_test.go
  webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
Labels: kind/bug, lgtm, size/XS, area/logs, cla: yes
