Repository kyma-project/telemetry-manager, pull requests merged in 2024-10, with the labels that each got.

#1480 chore: Improve error handling in main function
  main.go
Labels: size/L, lgtm, kind/chore, area/manager, cla: yes

#1481 chore: Simplified filter expression
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/ottlexpr/expressions.go
Labels: lgtm, size/M, kind/chore, area/metrics, cla: yes

#1482 fix: Adjust Self Monitor storage size
  docs/contributor/arch/014-telemetry-self-monitor-storage.md
  internal/resources/selfmonitor/resources.go
Labels: kind/bug, lgtm, area/documentation, area/manager, cla: yes

#1485 chore: Introduce do not merge check
  .github/workflows/pr-github-checks.yml
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1488 chore: Fix label check
  .github/workflows/pr-github-checks.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1491 chore: Fix label check
  .github/workflows/pr-github-checks.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1492 fix: Endpoint validation with path and port scenario
  internal/validators/endpoint/endpoint_validator.go
  internal/validators/endpoint/endpoint_validator_test.go
Labels: kind/bug, size/S, area/metrics, area/traces, cla: yes

#1487 feat: Add proper categories for CRDs
  apis/operator/v1alpha1/telemetry_types.go
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/tracepipeline_types.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/tracepipeline_types.go
  config/crd/bases/operator.kyma-project.io_telemetries.yaml
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/development/crd/bases/operator.kyma-project.io_telemetries.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
Labels: kind/feature, lgtm, size/M, area/manager, cla: yes

#1498 chore: Update istio dependency to 1.9.0
  .env
Labels: lgtm, size/XS, area/dependency, kind/chore, cla: yes

#1476 chore: Improve traces e2e test outputs with FlatTrace
  test/e2e/traces_service_name_test.go
  test/integration/istio/traces_test.go
  test/testkit/assert/traces.go
  test/testkit/matchers/metric/metric_matchers.go
  test/testkit/matchers/metric/metric_matchers_test.go
  test/testkit/matchers/trace/ptrace_utils.go
  test/testkit/matchers/trace/trace_matchers.go
  test/testkit/matchers/trace/trace_matchers_test.go
Labels: area/tests, size/L, lgtm, kind/chore, cla: yes

#1501 docs: Sync markdown and dita
  docs/user/04-metrics.md
Labels: lgtm, size/M, area/metrics, cla: yes, kind/docs

#1500 feat: Enable all memory metrics for nodes
  docs/user/04-metrics.md
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  test/testkit/metrics/runtime/node.go
Labels: kind/feature, lgtm, size/S, area/metrics, cla: yes

#1497 feat: Bump OTel image version to 0.111.0
  config/samples/telemetry_v1alpha1_tracepipeline.yaml
  docs/contributor/benchmarks/README.md
  hack/load-tests/metric-load-test-setup.yaml
  hack/load-tests/otel-logs/base/log-generator.yaml
  hack/load-tests/otel-logs/big/log-generator.yaml
  hack/load-tests/run-load-test.sh
  hack/load-tests/self-monitor-test-setup.yaml
  hack/load-tests/trace-load-test-setup.yaml
  internal/otelcollector/config/config.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/metric/gateway/testdata/config_otlp_disabled.yaml
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/testdata/config.yaml
  main.go
  sec-scanners-config.yaml
  test/e2e/telemetry_logs_analysis_test.go
  test/testkit/mocks/backend/deployment.go
  test/testkit/mocks/telemetrygen/telemetrygen.go
Labels: kind/feature, size/L, lgtm, area/documentation, area/manager, cla: yes

#1504 chore: Bump images to prepare for 1.25.0 release
  .env
  config/manager/kustomization.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, cla: yes, area/release

#1505 feat: Add workflows for external image syncing
  .github/workflows/branch-integration.yml
  .github/workflows/build-image.yml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-lifecycle.yml
  .github/workflows/sync-external-images.yml
  external-images.yaml
Labels: kind/feature, lgtm, size/M, area/ci, cla: yes

#1427 feat: Add dummy LogPipeline OTLP output
  .golangci.yaml
  .testcoverage.yml
  Makefile
  apis/telemetry/v1alpha1/logpipeline_conversion.go
  apis/telemetry/v1alpha1/logpipeline_conversion_test.go
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  controllers/telemetry/logpipeline_controller.go
  internal/reconciler/logpipeline/fluentbit/finalizer.go
  internal/reconciler/logpipeline/fluentbit/finalizer_test.go
  internal/reconciler/logpipeline/fluentbit/reconciler.go
  internal/reconciler/logpipeline/fluentbit/reconciler_test.go
  internal/reconciler/logpipeline/fluentbit/status.go
  internal/reconciler/logpipeline/fluentbit/sync.go
  internal/reconciler/logpipeline/fluentbit/sync_test.go
  internal/reconciler/logpipeline/fluentbit/validator.go
  internal/reconciler/logpipeline/otel/reconciler.go
  internal/reconciler/logpipeline/outputtype_string.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/testutils/log_pipeline_builder.go
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: kind/feature, lgtm, size/XXL, area/manager, cla: yes

#1499 chore: Rename trace-collector to trace-gateway
  .testcoverage.yml
  config/manager/manager.yaml
  docs/contributor/arch/013-resource-attributes-enrichment-for-non-workload-metrics.md
  docs/user/03-traces.md
  docs/user/assets/manager-resources.drawio.svg
  docs/user/assets/traces-resources.drawio.svg
  docs/user/integration/aws-cloudwatch/README.md
  docs/user/integration/dynatrace/README.md
  docs/user/integration/jaeger/README.md
  hack/load-tests/run-load-test.sh
  internal/otelcollector/config/metric/agent/drop_internal_communication.go
  internal/otelcollector/config/metric/agent/drop_internal_communication_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/trace/gateway/drop_noisy_spans.go
  internal/otelcollector/config/trace/gateway/testdata/config.yaml
  internal/reconciler/tracepipeline/reconciler.go
  internal/selfmonitor/config/rules.go
  internal/selfmonitor/config/rules_test.go
  internal/testutils/pod_builder.go
  main.go
  test/e2e/assets/tracing-tests.svg
  test/e2e/overrides_test.go
  test/e2e/traces_basic_v1alpha1_test.go
  test/e2e/traces_noisy_span_filter_test.go
  test/integration/istio/traces_test.go
  test/testkit/kyma/common_names.go
Labels: size/L, kind/chore, area/traces, cla: yes

#1507 feat: Disable node network metrics
  docs/user/04-metrics.md
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  test/e2e/metrics_runtime_input_resources_test.go
  test/testkit/metrics/runtime/node.go
Labels: kind/feature, lgtm, size/M, area/metrics, cla: yes

#1495 chore: Unify TLS settings for logpipeline beta1
  apis/telemetry/v1alpha1/logpipeline_conversion.go
  apis/telemetry/v1alpha1/logpipeline_conversion_test.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/secret_refs.go
  apis/telemetry/v1beta1/shared_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  test/e2e/logs_basic_v1beta1_test.go
  test/e2e/logs_version_conversion_test.go
Labels: size/L, lgtm, kind/chore, area/logs, cla: yes

#1519 chore: Dont fail concurrent loadtests
  .github/workflows/pr-loadtest.yml
Labels: size/XS, area/ci, kind/chore, cla: yes

#1486 feat: Add a selector for runtime volume metrics
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/rbac/role.yaml
  docs/user/04-metrics.md
  docs/user/assets/metrics-arch.drawio.svg
  docs/user/resources/05-metricpipeline.md
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/processors.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/service.go
  internal/otelcollector/config/metric/gateway/service_test.go
  internal/otelcollector/config/metric/input_enabled.go
  internal/otelcollector/config/ottlexpr/expressions.go
  internal/resources/otelcollector/rbac.go
  internal/resources/otelcollector/rbac_test.go
  internal/testutils/metric_pipeline_builder.go
  main.go
  test/e2e/metrics_runtime_input_resources_test.go
  test/testkit/metrics/runtime/volume.go
Labels: kind/feature, size/XL, area/metrics, cla: yes

#1514 chore: Change workflows to wait for image in registry
  .github/template/prepare-test/action.yaml
  .github/workflows/pr-lifecycle.yml
  hack/await_image.sh
  hack/await_workflow.sh
Labels: size/L, lgtm, area/ci, kind/chore, cla: yes

#1509 feat: Move k8s cluster receiver to agent
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/processors.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  internal/otelcollector/config/metric/config.go
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/receivers.go
  internal/otelcollector/config/metric/gateway/receivers_test.go
  internal/otelcollector/config/metric/gateway/service.go
  internal/otelcollector/config/metric/gateway/service_test.go
  internal/otelcollector/config/metric/set_instrumentation_scope_test.go
  internal/otelcollector/config/metric/set_instrumention_scope.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/resources/otelcollector/rbac.go
  internal/resources/otelcollector/rbac_test.go
Labels: kind/feature, lgtm, size/XL, area/metrics, cla: yes

#1524 chore: Remove unused OTLPTLS struct
  apis/telemetry/v1beta1/shared_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  internal/fluentbit/config/builder/input.go
  internal/testutils/pod_builder.go
Labels: lgtm, size/M, kind/chore, area/logs, cla: yes

#1528 docs: Add new cloud logging dashboard for k8s volumes
  docs/user/integration/sap-cloud-logging/README.md
  docs/user/integration/sap-cloud-logging/dashboard-nodes.ndjson
  docs/user/integration/sap-cloud-logging/dashboard-volumes.ndjson
Labels: area/documentation, size/S, area/metrics, cla: yes, kind/docs

#1527 feat: Remove unneeded operator flags
  apis/telemetry/v1alpha1/logpipeline_validation.go
  apis/telemetry/v1alpha1/logpipeline_validation_test.go
  apis/telemetry/v1alpha1/shared_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/logpipeline_validation.go
  apis/telemetry/v1beta1/logpipeline_validation_test.go
  apis/telemetry/v1beta1/shared_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/manager/manager.yaml
  config/samples/telemetry_v1alpha1_metricpipeline.yaml
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/status.go
  main.go
  webhook/logpipeline/webhook.go
  webhook/logpipeline/webhook_test.go
Labels: kind/feature, lgtm, size/XL, area/manager, cla: yes

#1533 chore: Improve e2e test stability
  .env
  .github/workflows/pr-integration.yml
  Makefile
  hack/make/provision.mk
  hack/provision-k3d.sh
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
  test/e2e/manager_test.go
  test/e2e/metrics_basic_v1alpha1_test.go
  test/e2e/metrics_basic_v1beta1_test.go
  test/e2e/metrics_endpoint_invalid_test.go
  test/e2e/metrics_endpoint_path_validation_test.go
  test/e2e/metrics_endpoint_port_test.go
  test/e2e/metrics_endpoint_with_path_test.go
  test/e2e/metrics_kyma_input_test.go
  test/e2e/metrics_mtls_about_to_expire_cert_test.go
  test/e2e/metrics_mtls_cert_key_pair_dont_match_test.go
  test/e2e/metrics_mtls_expired_cert_test.go
  test/e2e/metrics_mtls_invalid_ca_test.go
  test/e2e/metrics_mtls_invalid_cert_test.go
  test/e2e/metrics_mtls_missing_values_test.go
  test/e2e/metrics_mtls_test.go
  test/e2e/metrics_multi_pipeline_broken_pipeline_test.go
  test/e2e/metrics_multi_pipeline_namespace_selector_test.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_otlp_input_test.go
  test/e2e/metrics_prometheus_input_diagnostic_metric_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/metrics_resources_test.go
  test/e2e/metrics_runtime_input_resources_test.go
  test/e2e/metrics_runtime_input_test.go
  test/e2e/metrics_secret_rotation_test.go
  test/e2e/metrics_self_monitor_healthy_test.go
  test/e2e/metrics_service_name_test.go
  test/testkit/assert/service.go
  test/testkit/k8s/service.go
  test/testkit/mocks/telemetrygen/telemetrygen.go
  test/testkit/suite/suite.go
Labels: area/tests, lgtm, size/XL, kind/chore, cla: yes

#1534 chore: Fix await image script not working on push triggers
  .github/template/prepare-test/action.yaml
  .github/workflows/branch-integration.yml
  .github/workflows/pr-lifecycle.yml
  .github/workflows/tag-release.yml
  hack/await_image.sh
Labels: area/ci, size/S, kind/chore, cla: yes

#1539 docs: Updated deprecated otel docs link
  docs/contributor/arch/003-integrate-prometheus-with-telemetry-manager-using-alerting.md
Labels: lgtm, size/XS, area/documentation, cla: yes, kind/docs

#1536 chore: Add comments to prometheus receiver config generation and improve var names
  internal/otelcollector/config/metric/agent/prometheus_receiver.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/relabel_configs.go
Labels: lgtm, size/XL, kind/chore, area/metrics, cla: yes

#1532 feat: Reduced resource requests for several components
  config/manager/manager.yaml
  internal/resources/fluentbit/resources.go
  internal/resources/selfmonitor/resources.go
Labels: kind/feature, lgtm, size/S, area/manager, cla: yes

#1540 docs: Fix MetricPipeline input docs
  apis/telemetry/v1alpha1/metricpipeline_types.go
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  docs/user/resources/05-metricpipeline.md
Labels: area/documentation, size/S, area/metrics, cla: yes, kind/docs

#1547 chore: Bump images for 1.26.0 release
  .env
  config/manager/kustomization.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, cla: yes, area/release

#1531 chore: Trigger all-checks-passed after e2e tests
  .github/workflows/pr-all-checks-passed.yml
  .github/workflows/pr-integration.yml
Labels: area/ci, size/S, kind/chore, cla: yes

#1538 chore: Introduce FlatMetricFamily struct to flatten prometheus metric output
  test/e2e/logs_self_monitor_healthy_test.go
  test/e2e/metrics_self_monitor_healthy_test.go
  test/e2e/traces_self_monitor_healthy_test.go
  test/testkit/assert/monitoring.go
  test/testkit/matchers/prometheus/prometheus_matcher.go
  test/testkit/matchers/prometheus/prometheus_matcher_test.go
  test/testkit/matchers/prometheus/prommetric_utils.go
Labels: area/tests, size/L, lgtm, kind/chore, cla: yes

#1548 fix: Get rid of spammy RBAC log
  config/rbac/role.yaml
  main.go
Labels: kind/bug, lgtm, area/manager

#1543 test: Fix flakiness in metrics e2e tests
  test/e2e/metrics_runtime_input_resources_test.go
  test/integration/istio/access_logs_test.go
  test/integration/istio/traces_test.go
  test/testkit/assert/daemon_set.go
  test/testkit/assert/deployment.go
  test/testkit/assert/pod.go
Labels: size/M, kind/flaky-test, area/metrics, cla: yes

#1550 chore: Cherry pick RBAC errors and bump version to 1.26.1
  .env
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, cla: yes, area/release

#1544 docs: Istio proxy metric merge ADR
  docs/contributor/arch/015-impact-of-istio-prometheus-merge-on-metric-pipelines.md
Labels: lgtm, size/M, area/metrics, cla: yes, kind/docs

#1553 docs: Update Istio metric merge ADR
  docs/contributor/arch/015-impact-of-istio-prometheus-merge-on-metric-pipelines.md
Labels: lgtm, size/XS, area/metrics, kind/docs

#1551 chore: Build tools only once in CI
  .github/template/prepare-test/action.yaml
  .github/template/setup-golang/action.yaml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-integration.yml
  Makefile
Labels: size/M, area/ci, kind/chore, cla: yes

#1556 chore: Store k3d config in file
  .k3d-kyma.yaml
  hack/make/provision.mk
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1558 chore: Bump directory-size-exporter image
  main.go
  sec-scanners-config.yaml
Labels: size/XS, kind/chore, area/logs, cla: yes

#1542 feat: Optional application/runtime/otlp input
  .gitignore
  Makefile
  apis/telemetry/v1alpha1/logpipeline_conversion.go
  apis/telemetry/v1alpha1/logpipeline_conversion_test.go
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/logpipeline_validation.go
  apis/telemetry/v1alpha1/logpipeline_validation_test.go
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/mode_string.go
  apis/telemetry/v1alpha1/shared_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/logpipeline_validation.go
  apis/telemetry/v1beta1/logpipeline_validation_test.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/mode_string.go
  apis/telemetry/v1beta1/shared_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/kustomization.yaml
  docs/contributor/arch/009-makefile-architecture.md
  docs/user/resources/05-metricpipeline.md
  internal/featureflags/featureflag_string.go
  internal/featureflags/featureflags.go
  internal/featureflags/featureflags_test.go
  internal/fluentbit/config/builder/config_builder.go
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/input.go
  internal/fluentbit/config/builder/input_test.go
  internal/fluentbit/config/builder/kubernetes_filter.go
  internal/fluentbit/config/builder/kubernetes_filter_test.go
  internal/fluentbit/config/builder/rewritetag_filter.go
  internal/fluentbit/config/builder/rewritetag_filter_test.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/reconciler/logpipeline/fluentbit/reconciler.go
  internal/reconciler/logpipeline/otel/reconciler.go
  internal/reconciler/logpipeline/outputtype_string.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/testutils/log_pipeline_builder.go
  internal/testutils/metric_pipeline_builder.go
  main.go
  test/testkit/matchers/metric/pmetric_utils.go
  webhook/logpipeline/webhook_test.go
Labels: kind/feature, lgtm, size/XXL, area/logs, cla: yes

#1552 chore: Rename Otlp to OTLP
  Makefile
  apis/telemetry/v1alpha1/logpipeline_conversion.go
  apis/telemetry/v1alpha1/logpipeline_conversion_test.go
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/logpipeline_validation.go
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/secret_refs.go
  apis/telemetry/v1alpha1/secret_refs_test.go
  apis/telemetry/v1alpha1/shared_types.go
  apis/telemetry/v1alpha1/tracepipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/service.go
  internal/otelcollector/config/metric/input_enabled.go
  internal/otelcollector/config/metric/shared_attributes.go
  internal/otelcollector/config/otlpexporter/config_builder.go
  internal/otelcollector/config/otlpexporter/config_builder_test.go
  internal/otelcollector/config/otlpexporter/env_vars.go
  internal/otelcollector/config/trace/gateway/config_builder.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/validator.go
  internal/reconciler/tracepipeline/validator.go
  internal/testutils/log_pipeline_builder.go
  internal/testutils/metric_pipeline_builder.go
  internal/testutils/pipeline_opts.go
  internal/testutils/trace_pipeline_builder.go
  internal/validators/endpoint/endpoint_validator.go
  internal/validators/endpoint/endpoint_validator_test.go
  test/e2e/metrics_mtls_missing_values_test.go
  test/e2e/traces_mtls_missing_values_test.go
  webhook/logpipeline/webhook_test.go
Labels: size/XL, kind/chore, area/manager, cla: yes

#1564 chore: Sort telemetry.kyma-project.io API types (v1alpha1 and v1beta1)
  apis/telemetry/v1alpha1/logparser_types.go
  apis/telemetry/v1alpha1/logpipeline_conversion.go
  apis/telemetry/v1alpha1/logpipeline_conversion_test.go
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/logpipeline_types_test.go
  apis/telemetry/v1alpha1/logpipeline_validation.go
  apis/telemetry/v1alpha1/logpipeline_validation_test.go
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/secret_refs.go
  apis/telemetry/v1alpha1/secret_refs_test.go
  apis/telemetry/v1alpha1/shared_types.go
  apis/telemetry/v1alpha1/tracepipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/logpipeline_validation_test.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/shared_types.go
  apis/telemetry/v1beta1/tracepipeline_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/custom_filter_test.go
  internal/fluentbit/config/builder/input_test.go
  internal/fluentbit/config/builder/kubernetes_filter.go
  internal/fluentbit/config/builder/kubernetes_filter_test.go
  internal/fluentbit/config/builder/output.go
  internal/fluentbit/config/builder/output_test.go
  internal/fluentbit/config/builder/rewritetag_filter.go
  internal/fluentbit/config/builder/rewritetag_filter_test.go
  internal/reconciler/logpipeline/fluentbit/finalizer_test.go
  internal/reconciler/logpipeline/fluentbit/sync.go
  internal/reconciler/logpipeline/fluentbit/sync_test.go
  internal/reconciler/logpipeline/fluentbit/validator.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/testutils/log_pipeline_builder.go
  internal/testutils/metric_pipeline_builder.go
  internal/testutils/pipeline_opts.go
  test/e2e/logs_mtls_missing_values_test.go
  test/e2e/logs_version_conversion_test.go
  webhook/logpipeline/validation/files_validator_test.go
  webhook/logpipeline/validation/variable_validator.go
  webhook/logpipeline/validation/variable_validator_test.go
  webhook/logpipeline/webhook_test.go
Labels: lgtm, size/XXL, kind/chore, area/logs, area/metrics, area/traces, cla: yes

#1530 feat: Add support for all workloads: Deployment, Daemonset, Jobs, Statefulsets
  .golangci.yaml
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  docs/user/04-metrics.md
  docs/user/resources/05-metricpipeline.md
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/processors.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/service.go
  internal/otelcollector/config/metric/gateway/service_test.go
  internal/otelcollector/config/metric/input_enabled.go
  internal/testutils/metric_pipeline_builder.go
  test/e2e/metrics_runtime_input_resources_test.go
  test/testkit/assert/jobs.go
  test/testkit/assert/stateful_set.go
  test/testkit/metrics/runtime/daemonset.go
  test/testkit/metrics/runtime/deployment.go
  test/testkit/metrics/runtime/job.go
  test/testkit/metrics/runtime/statefulset.go
Labels: kind/feature, lgtm, size/XXL, area/metrics, cla: yes

#1568 chore: Extract operator ports into constants
  main.go
Labels: lgtm, size/S, kind/chore, area/manager, cla: yes

#1569 fix: Fix otel backend configuration in sample manifests
  config/samples/telemetry_v1alpha1_metricpipeline.yaml
  config/samples/telemetry_v1alpha1_tracepipeline.yaml
Labels: kind/bug, size/S, area/metrics, area/traces, cla: yes

#1559 fix: Dont drop clusterscoped metrics
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/ottlexpr/expressions.go
  test/e2e/metrics_runtime_node_namespace_test.go
Labels: kind/bug, size/L, lgtm, area/metrics, cla: yes

#1560 feat: Improve printColumns for telemetry CRD
  apis/operator/v1alpha1/telemetry_types.go
  config/crd/bases/operator.kyma-project.io_telemetries.yaml
  config/development/crd/bases/operator.kyma-project.io_telemetries.yaml
  test/e2e/telemetry_logs_analysis_test.go
Labels: kind/feature, lgtm, size/M, area/manager, cla: yes

#1573 docs: Improve runtime resources metrics example
  docs/user/04-metrics.md
Labels: area/documentation, size/S, area/metrics, cla: yes, kind/docs

#1574 chore: Revert telemetry manager log test
  test/e2e/telemetry_logs_analysis_test.go
Labels: size/M, kind/chore, area/manager, cla: yes

#1582 docs: Fix broken links
  docs/user/03-traces.md
  docs/user/integration/sap-cloud-logging/README.md
Labels: lgtm, size/XS, area/documentation, cla: yes, kind/docs

#1583 chore: Prepare images for 1.26.2 release
  .env
  config/manager/kustomization.yaml
  docs/user/03-traces.md
  docs/user/integration/sap-cloud-logging/README.md
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, cla: yes, area/release
