Repository kyma-project/telemetry-manager, pull requests merged in 2024-08, with the labels that each got.

#1311 feat: Adjust RBAC configurations for Metric Gateway in development variant
  config/development/kustomization.yaml
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  internal/resources/otelcollector/rbac.go
  internal/resources/otelcollector/rbac_test.go
  main.go
Labels: kind/feature, lgtm, size/XL, area/metrics, cla: yes

#1275 feat: Improve agent/gateway status detection
  .golangci.yaml
  .mockery.yaml
  config/manager/manager.yaml
  controllers/telemetry/logparser_controller.go
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/conditions/error_to_message.go
  internal/conditions/error_to_message_test.go
  internal/k8sutils/daemonset.go
  internal/k8sutils/daemonset_test.go
  internal/k8sutils/deployment_test.go
  internal/reconciler/commonstatus/checker.go
  internal/reconciler/commonstatus/checker_test.go
  internal/reconciler/logparser/mocks/daemon_set_prober.go
  internal/reconciler/logparser/reconciler.go
  internal/reconciler/logparser/status.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/mocks/daemon_set_prober.go
  internal/reconciler/logpipeline/mocks/error_to_message_converter.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/metricpipeline/mocks/daemon_set_prober.go
  internal/reconciler/metricpipeline/mocks/deployment_prober.go
  internal/reconciler/metricpipeline/mocks/error_to_message_converter.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/tracepipeline/mocks/deployment_prober.go
  internal/reconciler/tracepipeline/mocks/error_to_message_converter.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/status.go
  internal/testutils/pod_builder.go
  internal/workloadstatus/daemonset.go
  internal/workloadstatus/daemonset_test.go
  internal/workloadstatus/deployment.go
  internal/workloadstatus/deployment_test.go
  internal/workloadstatus/errortypes.go
  internal/workloadstatus/errortypes_test.go
  internal/workloadstatus/pods.go
  internal/workloadstatus/pods_test.go
  main.go
Labels: kind/feature, lgtm, size/XXL, area/manager, cla: yes

#1299 chore: Update self-monitor to prometheus 2.53.1
  docs/contributor/benchmarks/README.md
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#1320 test: Add KeepOriginalBody E2E tests
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/kubernetes_filter.go
  internal/fluentbit/config/builder/kubernetes_filter_test.go
  internal/testutils/log_pipeline_builder.go
  test/e2e/logs_drop_labels_test.go
  test/e2e/logs_keep_annotation_test.go
  test/e2e/logs_keep_original_body_test.go
  test/testkit/matchers/log/log_matchers.go
  test/testkit/mocks/backend/fluentd/config_map.go
  test/testkit/mocks/loggen/log_producer.go
  webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
Labels: area/tests, size/L, lgtm, kind/missing-test, area/logs, cla: yes

#1322 fix: Add a new reason for the pipelines
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/conditions/error_to_message_test.go
  internal/reconciler/commonstatus/checker.go
  internal/reconciler/commonstatus/checker_test.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/tracepipeline/reconciler_test.go
Labels: kind/bug, lgtm, size/M, area/manager, cla: yes

#1324 chore: Move from mocks to stubs
  .golangci.yaml
  .mockery.yaml
  internal/reconciler/commonstatus/checker_test.go
  internal/reconciler/commonstatus/stubs/daemon_set_prober.go
  internal/reconciler/commonstatus/stubs/deployment_set_prober.go
  internal/reconciler/logparser/mocks/daemon_set_prober.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/mocks/daemon_set_prober.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/mocks/daemon_set_prober.go
  internal/reconciler/metricpipeline/mocks/deployment_prober.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/tracepipeline/mocks/deployment_prober.go
  internal/reconciler/tracepipeline/reconciler_test.go
Labels: lgtm, size/XL, kind/chore, area/manager, cla: yes

#1323 docs: Implement TW Review
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/integration/sap-cloud-logging/README.md
Labels: lgtm, area/documentation, size/S, cla: yes, kind/docs

#1288 chore: Improve test output
  config/manager/kustomization.yaml
  hack/provision-k3d.sh
  test/e2e/logs_exclude_container_test.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_prometheus_input_diagnostic_metric_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/metrics_runtime_input_resources_test.go
  test/e2e/metrics_runtime_input_test.go
  test/e2e/suite_test.go
  test/testkit/assert/metrics.go
  test/testkit/matchers/metric/metric_matchers.go
  test/testkit/matchers/metric/pmetric_utils.go
  test/testkit/mocks/prommetricgen/metric_producer.go
Labels: area/tests, size/L, lgtm, kind/chore, cla: yes

#1327 chore: Revert kustomization.yaml and provision-k3d.sh
  config/manager/kustomization.yaml
  hack/provision-k3d.sh
Labels: area/tests, lgtm, size/XS, kind/chore, cla: yes

#1326 chore: Update docs to correspond to new release workflow
  docs/contributor/releasing.md
Labels: lgtm, size/XS, area/documentation, kind/chore, cla: yes

#1330 chore: Add unexported-return linter
  .golangci.yaml
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  internal/resources/otelcollector/rbac.go
  internal/testutils/pod_builder.go
Labels: lgtm, size/M, kind/chore, area/manager, cla: yes

#1321 feat: Allow collecting Telemetry module status metrics in development variant
  .github/workflows/pr-integration.yml
  controllers/telemetry/metricpipeline_controller.go
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/processors.go
  internal/otelcollector/config/metric/agent/set_instrumention_scope.go
  internal/otelcollector/config/metric/config.go
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/receivers.go
  internal/otelcollector/config/metric/gateway/receivers_test.go
  internal/otelcollector/config/metric/set_instrumentation_scope_test.go
  internal/otelcollector/config/metric/set_instrumention_scope.go
  internal/otelcollector/config/metric/shared_attributes.go
  internal/reconciler/metricpipeline/mocks/gateway_config_builder.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/testutils/metric_pipeline_builder.go
  main.go
  test/e2e/logs_basic_v1beta1_test.go
  test/e2e/metrics_basic_v1beta1_test.go
  test/e2e/metrics_kyma_input_test.go
  test/e2e/metrics_resources_test.go
  test/e2e/traces_basic_v1beta1_test.go
  test/testkit/kyma/common_names.go
  test/testkit/matchers/metric/pmetric_utils.go
  test/testkit/suite/suite.go
Labels: kind/feature, lgtm, size/XXL, area/metrics, cla: yes

#1334 test: Flaky self-monitor metric outage tests
  test/integration/istio/metrics_self_monitor_outage_test.go
  test/testkit/mocks/telemetrygen/telemetrygen.go
Labels: area/tests, lgtm, size/XS, kind/flaky-test, cla: yes

#1335 feat: Add required RBAC for k8s cluster receiver
  config/development/kustomization.yaml
  config/rbac/role.yaml
  controllers/telemetry/metricpipeline_controller.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/resources/otelcollector/rbac.go
  internal/resources/otelcollector/rbac_test.go
  main.go
Labels: kind/feature, size/L, lgtm, area/metrics, cla: yes

#1336 chore: Prepare checks for repo rule
  .github/workflows/build-image.yml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-github-checks.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-lifecycle.yml
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1340 feat: Add indication to look at container logs
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/conditions/error_to_message.go
  internal/conditions/error_to_message_test.go
  internal/reconciler/commonstatus/checker_test.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/tracepipeline/reconciler_test.go
  webhook/dryrun/testdata/expected/pipelines/dynamic/logpipeline-1.conf
Labels: kind/feature, lgtm, size/M, area/logs, cla: yes

#1318 chore: Perf test for otel logging
  .github/workflows/pr-loadtest.yml
  docs/contributor/benchmarks/load-test-logs.md
  hack/load-tests/convert-results.py
  hack/load-tests/matrix_includes.json
  hack/load-tests/otel-logs/base/base.env
  hack/load-tests/otel-logs/base/config/receiver.yaml
  hack/load-tests/otel-logs/base/config/relay.yaml
  hack/load-tests/otel-logs/base/kustomization.yaml
  hack/load-tests/otel-logs/base/log-gateway.yaml
  hack/load-tests/otel-logs/base/log-generator.yaml
  hack/load-tests/otel-logs/base/log-receiver.yaml
  hack/load-tests/otel-logs/base/namespace.yaml
  hack/load-tests/otel-logs/batch/config/receiver.yaml
  hack/load-tests/otel-logs/batch/config/relay.yaml
  hack/load-tests/otel-logs/batch/kustomization.yaml
  hack/load-tests/otel-logs/big/kustomization.yaml
  hack/load-tests/otel-logs/big/log-generator.yaml
  hack/load-tests/run-load-test.sh
Labels: lgtm, size/XXL, area/documentation, kind/chore, area/logs, cla: yes

#1344 chore: Implement pr-prevent-kustomization GHA
  .github/workflows/pr-github-checks.yml
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1342 chore: Clean up Dockerfile after removing `dry-run` feature
  Dockerfile
  config/manager/manager.yaml
Labels: lgtm, area/dependency, size/S, kind/chore, cla: yes

#1329 fix: Invalid URL endpoint propagation
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/endpoint/endpoint_validator.go
  internal/endpoint/endpoint_validator_test.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/stubs/endpoint_validator.go
  internal/reconciler/logpipeline/validator.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/metricpipeline/stubs/endpoint_validator.go
  internal/reconciler/metricpipeline/validator.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/stubs/endpoint_validator.go
  internal/reconciler/tracepipeline/validator.go
  test/e2e/logs_endpoint_validation_test.go
  test/e2e/metrics_endpoint_validation_test.go
  test/e2e/traces_endpoint_validation_test.go
Labels: kind/bug, lgtm, size/XL, area/logs, area/metrics, area/traces, cla: yes

#1349 chore: Add commit SHA tag for unique PR tags
  .github/workflows/build-image.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1361 chore: Update istio dependency in tests to 1.8.2
  .env
Labels: lgtm, kind/chore, area/metrics, area/traces, cla: yes

#1364 feat: Update to fluent-bit 3.1.6
  docs/contributor/benchmarks/README.md
  main.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/XS, area/logs, cla: yes

#1376 chore: Unblock docs-only PRs
  .github/workflows/skip-on-docu-paths.yml
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1365 chore: Collect JUnit reports as part of gingko executions
  .github/template/finalize-test/action.yaml
  .github/workflows/branch-integration.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-lifecycle.yml
  hack/gardener-integration-test.sh
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1377 chore: Fix gha workflow
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-skip-on-docu-paths.yml
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1378 chore: Fix gardener integration job
  .github/workflows/branch-integration.yml
  hack/deploy-istio.sh
  hack/wait-for-namespaces.sh
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1338 docs: Add styleguide and document error handling
  docs/contributor/styleguide/README.md
  docs/contributor/styleguide/error_handling.md
Labels: lgtm, size/M, area/documentation, cla: yes, kind/docs

#1372 docs: Update LogPipeline OTLP output ADR
  docs/contributor/arch/007-log-pipeline-otlp-output.md
Labels: lgtm, size/XS, area/logs, cla: yes, kind/docs

#1379 chore: Update istio dependency to 1.8.3
  .env
Labels: lgtm, size/XS, area/dependency, kind/chore, cla: yes

#1381 chore: Delete non-working GHA workflow
  .github/workflows/pr-skip-on-docu-paths.yml
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1382 chore: Replace workflow path filter with changed-files
  .github/workflows/pr-code-checks.yml
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1383 chore: Replace workflow path filter with changed-files (pt. 2)
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-lifecycle.yml
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1373 fix: Self Monitor storage volume fill-up despite retention rules
  internal/resources/selfmonitor/resources.go
Labels: kind/bug, lgtm, size/XS, area/manager, cla: yes

#1360 chore: Change await sha instead of pr tag
  .github/template/prepare-test/action.yaml
  .github/workflows/pr-lifecycle.yml
  hack/await_workflow.sh
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1363 chore: Update self-monitor prometheus to 2.53.2
  docs/contributor/benchmarks/README.md
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#1355 test: Add additional tests for logs/metrics/traces if pods are up and running
  test/e2e/logs_basic_v1alpha1_test.go
  test/e2e/logs_basic_v1beta1_test.go
  test/e2e/logs_custom_output_test.go
  test/e2e/logs_dedot_test.go
  test/e2e/logs_drop_labels_test.go
  test/e2e/logs_exclude_container_test.go
  test/e2e/logs_keep_annotation_test.go
  test/e2e/logs_keep_original_body_test.go
  test/e2e/logs_mtls_about_to_expire_cert_test.go
  test/e2e/logs_mtls_test.go
  test/e2e/logs_multi_pipeline_broken_pipeline_test.go
  test/e2e/logs_multi_pipeline_namespace_filter_test.go
  test/e2e/logs_multi_pipeline_test.go
  test/e2e/logs_parser_test.go
  test/e2e/logs_resources_test.go
  test/e2e/logs_self_monitor_healthy_test.go
  test/e2e/metrics_mtls_about_to_expire_cert_test.go
  test/e2e/metrics_mtls_test.go
  test/e2e/metrics_multi_pipeline_namespace_selector_test.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/metrics_runtime_input_resources_test.go
  test/e2e/metrics_runtime_input_test.go
  test/e2e/metrics_self_monitor_healthy_test.go
  test/e2e/metrics_service_name_test.go
  test/e2e/telemetry_logs_analysis_test.go
  test/e2e/traces_mtls_about_to_expire_cert_test.go
  test/e2e/traces_multi_pipeline_test.go
  test/e2e/traces_noisy_span_filter_test.go
  test/e2e/traces_self_monitor_healthy_test.go
  test/integration/istio/access_logs_test.go
  test/integration/istio/logs_self_monitor_backpressure_test.go
  test/integration/istio/logs_self_monitor_outage_test.go
  test/integration/istio/metrics_istio_input_test.go
  test/integration/istio/metrics_prometheus_input_test.go
  test/integration/istio/metrics_self_monitor_backpressure_test.go
  test/integration/istio/metrics_self_monitor_outage_test.go
  test/integration/istio/traces_self_monitor_backpressure_test.go
  test/integration/istio/traces_self_monitor_outage_test.go
  test/testkit/kyma/common_names.go
Labels: area/tests, size/L, lgtm, kind/flaky-test, cla: yes

#1362 feat: Bump OTel image version to 0.107.0
  config/samples/telemetry_v1alpha1_tracepipeline.yaml
  docs/contributor/benchmarks/README.md
  hack/load-tests/metric-load-test-setup.yaml
  hack/load-tests/otel-logs/base/log-gateway.yaml
  hack/load-tests/otel-logs/base/log-generator.yaml
  hack/load-tests/otel-logs/big/log-generator.yaml
  hack/load-tests/run-load-test.sh
  hack/load-tests/self-monitor-test-setup.yaml
  hack/load-tests/trace-load-test-setup.yaml
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/set_instrumentation_scope_test.go
  internal/otelcollector/config/metric/set_instrumention_scope.go
  internal/resources/otelcollector/core_pod_spec.go
  internal/selfmonitor/config/expr_builder.go
  internal/selfmonitor/config/otelcol_rule_builder.go
  internal/selfmonitor/config/rules_test.go
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
  test/testkit/mocks/telemetrygen/telemetrygen.go
Labels: kind/feature, size/L, lgtm, area/documentation, area/manager, cla: yes

#1386 docs: Remove Kyma from user README title
  docs/user/README.md
Labels: lgtm, size/XS, area/documentation, cla: yes, kind/docs

#1387 chore: Only run upgrade tests if a source file is changed
  .github/workflows/pr-lifecycle.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1380 chore: Group tlscert, secretref, and endpoint validators under the same folder
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  internal/conditions/tls_cert_conditions.go
  internal/conditions/tls_cert_conditions_test.go
  internal/otelcollector/config/otlpexporter/env_vars.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/stubs/secret_ref_validator.go
  internal/reconciler/logpipeline/stubs/tls_cert_validator.go
  internal/reconciler/logpipeline/validator.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/metricpipeline/stubs/secret_ref_validator.go
  internal/reconciler/metricpipeline/stubs/tls_cert_validator.go
  internal/reconciler/metricpipeline/validator.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/stubs/secret_ref_validator.go
  internal/reconciler/tracepipeline/stubs/tls_cert_validator.go
  internal/reconciler/tracepipeline/validator.go
  internal/validators/endpoint/endpoint_validator.go
  internal/validators/endpoint/endpoint_validator_test.go
  internal/validators/secretref/secret_ref.go
  internal/validators/secretref/secret_ref_test.go
  internal/validators/tlscert/tls_cert_validator.go
  internal/validators/tlscert/tls_cert_validator_test.go
Labels: lgtm, size/M, kind/chore, area/logs, area/metrics, area/traces, cla: yes

#1343 feat: Add K8s cluster receiver
  config/development/kustomization.yaml
  controllers/telemetry/metricpipeline_controller.go
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processor_drop_filter.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/receivers.go
  internal/otelcollector/config/metric/gateway/receivers_test.go
  internal/otelcollector/config/metric/set_instrumentation_scope_test.go
  internal/otelcollector/config/metric/set_instrumention_scope.go
  internal/otelcollector/config/metric/shared_attributes.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/resources/otelcollector/rbac.go
  internal/resources/otelcollector/rbac_test.go
  main.go
  test/e2e/metrics_multi_pipeline_namespace_selector_test.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/metrics_runtime_input_resources_test.go
  test/testkit/mocks/prommetricgen/metric_producer.go
  test/testkit/otel/k8scluster/metrics.go
Labels: kind/feature, lgtm, size/XL, area/metrics, cla: yes

#1393 chore: Revert "chore: Implement pr-prevent-kustomization GHA"
  .github/workflows/pr-github-checks.yml
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1394 chore: Revert "chore: Implement pr-prevent-kustomization GHA"
  .github/workflows/pr-github-checks.yml
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1390 chore: Prepare release 1.22.0
  .env
  config/manager/kustomization.yaml
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, cla: yes, area/release

#1399 test: Revert the err check for namespace deletion
  hack/wait-for-namespaces.sh
Labels: lgtm, size/XS, kind/flaky-test, area/manager, cla: yes

#1405 chore: Run hack script from the current branch from which PR has been created
  .github/workflows/pr-lifecycle.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1397 fix: False positive NoLogsDelivered LogPipeline status reason
  internal/selfmonitor/config/expr_builder.go
  internal/selfmonitor/config/fluent_bit_rule_builder.go
  internal/selfmonitor/config/rules.go
  internal/selfmonitor/config/rules_test.go
  internal/selfmonitor/prober/log_pipeline_prober.go
  internal/selfmonitor/prober/log_pipeline_prober_test.go
  internal/selfmonitor/prober/otel_pipeline_prober_test.go
Labels: kind/bug, size/L, lgtm, area/logs, cla: yes

#1374 docs: Use extension mechanism for dashboard nodes in integration guides
  docs/user/integration/dynatrace/README.md
  docs/user/integration/dynatrace/kyma-dashboard-configmap.yaml
  docs/user/integration/jaeger/README.md
  docs/user/integration/loki/README.md
  docs/user/integration/loki/dashboard-configmap.yaml
  docs/user/integration/loki/kyma-dashboard-configmap.yaml
  docs/user/integration/loki/loki-values.yaml
  docs/user/integration/opentelemetry-demo/README.md
  docs/user/integration/sap-cloud-logging/README.md
  docs/user/integration/sap-cloud-logging/configmap-deeplinks.yaml
  docs/user/integration/sap-cloud-logging/configmap-navigation.yaml
  docs/user/integration/sap-cloud-logging/kyma-dashboard-configmap.yaml
Labels: size/L, lgtm, area/documentation, cla: yes, kind/docs
