Repository kyma-project/telemetry-manager, pull requests merged in 2024-05, with the labels that each got.

#1031 test: Migrate Telemetry env tests to e2e tests
  controllers/operator/suite_test.go
  controllers/operator/telemetry_controller_test.go
  test/e2e/logs_webhook_test.go
  test/e2e/suite_test.go
  test/e2e/telemetry_test.go
  test/testkit/k8s/log_pipeline_v1alpha1.go
  test/testkit/kyma/common_names.go
Labels: area/tests, lgtm, size/XL, kind/chore, cla: yes

#1035 feat: Update to prometheus 2.45.5 in self-monitor
  main.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/XS, area/manager, cla: yes

#858 docs: Fix wrong list type in documentation
  docs/contributor/arch/002-fluent-bit-without-file-system-buffer.md
Labels: lgtm, size/S, kind/chore, cla: yes

#1044 chore: Bump telemetry-manager image for 1.15.0 release
  .env
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1042 feat: Add support to configure metric gateway replicas in Kyma Dashboard
  config/busola/telemetry_busola_extension_cm.yaml
Labels: kind/feature, lgtm, size/M, area/metrics, cla: yes

#1045 docs: Add self-monitor to architecture figures
  docs/user/01-manager.md
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/README.md
  docs/user/assets/logs-arch.drawio.svg
  docs/user/assets/manager-lifecycle.drawio.svg
  docs/user/assets/metrics-arch.drawio.svg
  docs/user/assets/telemetry-components.drawio.svg
  docs/user/assets/traces-arch.drawio.svg
Labels: lgtm, size/XXL, area/documentation, cla: yes

#1050 chore: Rename tracing to traces in dashboard extension
  config/busola/telemetry_busola_extension_cm.yaml
Labels: kind/bug, lgtm, size/XS, area/traces, cla: yes

#1052 feat: Enable sidecar injection for Fluent Bit by default
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
Labels: kind/feature, lgtm, size/S, area/logs, cla: yes

#1058 chore: Fix lint
  apis/operator/v1alpha1/telemetry_types.go
  apis/telemetry/v1alpha1/logparser_types.go
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/tracepipeline_types.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/tracepipeline_types.go
  hack/make/dependencies.mk
  main.go
  test/testkit/mocks/loggen/log_producer.go
Labels: lgtm, size/S, cla: yes

#1051 chore: Update istio module dependency to 1.6.2
  .env
Labels: area/tests, lgtm, size/XS, area/dependency, cla: yes

#1057 test: Migrate traces and metrics env tests to e2e tests
  controllers/telemetry/metricpipeline_controller_test.go
  controllers/telemetry/otel_test_helpers.go
  controllers/telemetry/suite_test.go
  controllers/telemetry/tracepipeline_controller_test.go
  test/e2e/metrics_authentication_test.go
  test/e2e/metrics_resources_test.go
  test/e2e/traces_authentication_test.go
  test/e2e/traces_resources_test.go
  test/testkit/k8s/metric_pipeline_v1alpha1.go
  test/testkit/k8s/metric_pipeline_v1beta1.go
  test/testkit/k8s/secret.go
  test/testkit/k8s/trace_pipeline_v1alpha1.go
  test/testkit/k8s/trace_pipeline_v1beta1.go
  test/testkit/kyma/common_names.go
  test/testkit/verifiers/config_map.go
  test/testkit/verifiers/deployment.go
  test/testkit/verifiers/objects.go
Labels: area/tests, lgtm, size/XXL, kind/chore, cla: yes

#1059 chore: Fix gardener provisioning script
  hack/make/provision.mk
Labels: kind/bug, lgtm, size/XS, kind/chore, cla: yes

#1061 test: Fix flaky e2e test, test max pipelines in an isolated environment
  .github/workflows/pr-integration.yml
  test/e2e/logs_multi_pipeline_max_pipeline_test.go
  test/e2e/logs_webhook_test.go
  test/e2e/metrics_multi_pipeline_max_pipeline_test.go
  test/e2e/traces_multi_pipeline_max_pileline_test.go
  test/testkit/suite/suite.go
Labels: area/tests, lgtm, size/S, cla: yes

#1062 test: Improve check for existence of OwnerReference in e2e tests
  test/testkit/assert/objects.go
Labels: area/tests, lgtm, kind/failing-test, size/S, cla: yes

#1064 chore: Reuse testutil.LogPipelineBuilder in E2E tests
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status_test.go
  internal/testutils/log_pipeline_builder.go
  internal/testutils/pipeline_opts.go
  test/e2e/logs_annotation_test.go
  test/e2e/logs_basic_v1alpha1_test.go
  test/e2e/logs_basic_v1beta1_test.go
  test/e2e/logs_custom_output_test.go
  test/e2e/logs_dedot_test.go
  test/e2e/logs_exclude_container_test.go
  test/e2e/logs_label_test.go
  test/e2e/logs_mtls_about_to_expire_cert_test.go
  test/e2e/logs_mtls_cert_key_pair_dont_match_test.go
  test/e2e/logs_mtls_expired_cert_test.go
  test/e2e/logs_mtls_invalid_cert_test.go
  test/e2e/logs_mtls_test.go
  test/e2e/logs_multi_pipeline_broken_pipeline_test.go
  test/e2e/logs_multi_pipeline_max_pipeline_test.go
  test/e2e/logs_multi_pipeline_namespace_filter_test.go
  test/e2e/logs_multi_pipeline_test.go
  test/e2e/logs_parser_test.go
  test/e2e/logs_self_monitor_basic_test.go
  test/e2e/logs_webhook_test.go
  test/e2e/overrides_test.go
  test/e2e/telemetry_logs_analysis_test.go
  test/e2e/telemetry_test.go
  test/integration/istio/access_logs_test.go
  test/integration/istio/logs_self_monitor_backpressure_test.go
  test/integration/istio/logs_self_monitor_outage_test.go
  test/testkit/k8s/log_pipeline_v1alpha1.go
  test/testkit/k8s/log_pipeline_v1beta1.go
  test/testkit/mocks/backend/backend.go
  test/testkit/mocks/backend/external_service.go
Labels: area/tests, lgtm, size/XXL, area/logs, cla: yes

#1066 test: Do not execute self-monitor istio tests in Gardener suite
  hack/gardener-integration-test.sh
Labels: lgtm, size/XS, kind/failing-test, cla: yes

#1055 test: Add instrumentation scope e2e
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_runtime_input_test.go
  test/integration/istio/metrics_istio_input_test.go
  test/integration/istio/metrics_prometheus_input_test.go
  test/testkit/matchers/metric/metric_matchers.go
  test/testkit/matchers/metric/metric_matchers_test.go
  test/testkit/matchers/metric/pmetric_utils.go
Labels: size/L, lgtm, kind/missing-test, area/manager, cla: yes

#1068 chore: Reuse testutil.TracePipelineBuilder in E2E tests
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/tracepipeline/status_test.go
  internal/testutils/pipeline_opts.go
  internal/testutils/trace_pipeline_builder.go
  test/e2e/logs_basic_v1beta1_test.go
  test/e2e/overrides_test.go
  test/e2e/telemetry_logs_analysis_test.go
  test/e2e/telemetry_test.go
  test/e2e/traces_basic_v1alpha1_test.go
  test/e2e/traces_basic_v1beta1_test.go
  test/e2e/traces_endpoint_path_validation_test.go
  test/e2e/traces_endpoint_with_path_test.go
  test/e2e/traces_mtls_about_to_expire_cert_test.go
  test/e2e/traces_mtls_cert_key_pair_dont_match_test.go
  test/e2e/traces_mtls_expired_cert_test.go
  test/e2e/traces_mtls_invalid_cert_test.go
  test/e2e/traces_mtls_test.go
  test/e2e/traces_multi_pipeline_broken_pipeline_test.go
  test/e2e/traces_multi_pipeline_max_pipeline_test.go
  test/e2e/traces_multi_pipeline_test.go
  test/e2e/traces_noisy_span_filter_test.go
  test/e2e/traces_resources_test.go
  test/e2e/traces_secret_rotation_test.go
  test/e2e/traces_self_monitor_basic_test.go
  test/e2e/traces_service_name_test.go
  test/integration/istio/traces_test.go
  test/testkit/k8s/secret.go
  test/testkit/k8s/trace_pipeline_v1alpha1.go
  test/testkit/k8s/trace_pipeline_v1beta1.go
Labels: area/tests, lgtm, size/XL, kind/chore, cla: yes

#1070 chore: Reuse testutil.MetricPipelineBuilder in E2E tests
  internal/testutils/metric_pipeline_builder.go
  test/e2e/logs_basic_v1beta1_test.go
  test/e2e/metrics_basic_v1alpha1_test.go
  test/e2e/metrics_basic_v1beta1_test.go
  test/e2e/metrics_endpoint_path_validation_test.go
  test/e2e/metrics_endpoint_with_path_test.go
  test/e2e/metrics_mtls_about_to_expire_cert_test.go
  test/e2e/metrics_mtls_cert_key_pair_dont_match_test.go
  test/e2e/metrics_mtls_expired_cert_test.go
  test/e2e/metrics_mtls_invalid_cert_test.go
  test/e2e/metrics_mtls_test.go
  test/e2e/metrics_multi_pipeline_broken_pipeline_test.go
  test/e2e/metrics_multi_pipeline_max_pipeline_test.go
  test/e2e/metrics_multi_pipeline_namespace_selector_test.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_otlp_input_test.go
  test/e2e/metrics_prometheus_input_diagnostic_metric_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/e2e/metrics_resources_test.go
  test/e2e/metrics_runtime_input_test.go
  test/e2e/metrics_secret_rotation_test.go
  test/e2e/metrics_self_monitor_basic_test.go
  test/e2e/metrics_service_name_test.go
  test/e2e/overrides_test.go
  test/e2e/telemetry_logs_analysis_test.go
  test/e2e/telemetry_test.go
  test/e2e/traces_multi_pipeline_broken_pipeline_test.go
  test/integration/istio/metrics_istio_input_test.go
  test/integration/istio/metrics_otlp_input_test.go
  test/integration/istio/metrics_prometheus_input_test.go
  test/testkit/k8s/label_opts.go
  test/testkit/k8s/label_opts_test.go
  test/testkit/k8s/metric_pipeline_v1alpha1.go
  test/testkit/k8s/metric_pipeline_v1beta1.go
  test/testkit/k8s/objects.go
Labels: area/tests, lgtm, size/XXL, kind/chore, cla: yes

#1071 test: Remove env tests for LogParser
  controllers/telemetry/logparser_controller_test.go
  controllers/telemetry/suite_test.go
Labels: area/tests, size/L, lgtm, kind/chore, cla: yes

#1053 docs: Update release process documentation
  docs/contributor/releasing.md
Labels: lgtm, area/documentation, size/S, cla: yes

#1072 feat: Instrument self-monitoring prober
  controllers/telemetry/logpipeline_controller_test.go
  internal/reconciler/logpipeline/reconciler.go
  internal/selfmonitor/prober/common.go
  internal/selfmonitor/prober/prom_client.go
  test/e2e/logs_self_monitor_basic_test.go
  test/e2e/metrics_basic_v1alpha1_test.go
  test/e2e/metrics_basic_v1beta1_test.go
  test/e2e/metrics_runtime_input_test.go
  test/e2e/metrics_self_monitor_basic_test.go
  test/e2e/traces_basic_v1alpha1_test.go
  test/e2e/traces_basic_v1beta1_test.go
  test/e2e/traces_self_monitor_basic_test.go
  test/testkit/assert/monitoring.go
  test/testkit/assert/self_monitor.go
Labels: kind/feature, size/L, lgtm, area/logs, area/metrics, area/traces, cla: yes

#1067 docs: Fix error in self monitor + adjust diagrams
  docs/user/README.md
  docs/user/assets/logs-arch.drawio.svg
  docs/user/assets/metrics-arch.drawio.svg
  docs/user/assets/telemetry-components.drawio.svg
  docs/user/assets/traces-arch.drawio.svg
Labels: kind/bug, lgtm, area/documentation, size/S, cla: yes

#1054 docs: Improve license warning for loki integration guide
  docs/user/integration/loki/README.md
Labels: lgtm, size/XS, area/documentation, cla: yes

#1027 feat: Update fluent-bit image version to 3.0.3
  config/samples/http-mockserver.yaml
  docs/contributor/telemetry-load-test/README.md
  hack/load-tests/log-fluentbit-test-setup.yaml
  hack/load-tests/run-load-test.sh
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/M, area/documentation, area/logs, cla: yes

#1082 fix: Update telemetry-manager to latest fluent-bit version 3.0.3
  Dockerfile
Labels: kind/bug, lgtm, size/XS, area/manager, cla: yes

#1084 fix: Always set OwnerReference for telemetry-fluent-bit-sections ConfigMap
  internal/reconciler/logpipeline/sync.go
Labels: kind/bug, lgtm, size/XS, area/logs, cla: yes

#1086 chore: Remove OpenCensus cleanup logic
  internal/reconciler/tracepipeline/reconciler.go
Labels: lgtm, size/S, kind/chore, cla: yes

#1089 chore: Ignore dependabot updates for fluent-bit
  .github/dependabot.yml
Labels: lgtm, size/XS, area/dependency, kind/chore, cla: yes

#1038 feat: Synchronize CRs Reasons
  docs/contributor/arch/011-kymastatsmetrics.md
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/conditions/conditions_test.go
  internal/conditions/legacy_test.go
  internal/conditions/tls_cert_conditions.go
  internal/conditions/tls_cert_conditions_test.go
  internal/reconciler/logparser/status.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/reconciler/telemetry/metric_components_checker.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/status.go
  internal/reconciler/telemetry/status_test.go
  internal/reconciler/telemetry/status_utils.go
  internal/reconciler/telemetry/trace_components_checker.go
  internal/reconciler/telemetry/trace_components_checker_test.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
  test/e2e/logs_mtls_about_to_expire_cert_test.go
  test/e2e/logs_mtls_cert_key_pair_dont_match_test.go
  test/e2e/logs_mtls_expired_cert_test.go
  test/e2e/logs_mtls_invalid_cert_test.go
  test/e2e/metrics_mtls_about_to_expire_cert_test.go
  test/e2e/metrics_mtls_cert_key_pair_dont_match_test.go
  test/e2e/metrics_mtls_expired_cert_test.go
  test/e2e/metrics_mtls_invalid_cert_test.go
  test/e2e/telemetry_test.go
  test/e2e/traces_mtls_about_to_expire_cert_test.go
  test/e2e/traces_mtls_cert_key_pair_dont_match_test.go
  test/e2e/traces_mtls_expired_cert_test.go
  test/e2e/traces_mtls_invalid_cert_test.go
  test/integration/istio/logs_self_monitor_backpressure_test.go
  test/integration/istio/logs_self_monitor_outage_test.go
Labels: kind/feature, lgtm, size/XL, area/logs, area/metrics, area/traces, area/manager, cla: yes

#1092 fix: Use different UI path for telemetry module view to not clash with Istio resources
  config/busola/telemetry_busola_extension_cm.yaml
Labels: kind/bug, lgtm, size/XS, area/manager, cla: yes

#1096 chore: Fix linting issues with 1.58.2
  internal/k8sutils/owner_reference_setter.go
Labels: lgtm, size/XS, kind/chore, area/logs, area/metrics, area/traces, area/manager, cla: yes

#1095 fix: Unify CRs' descriptions in Kyma dashboard
  config/busola/logpipeline_busola_extension_cm.yaml
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/busola/telemetry_busola_extension_cm.yaml
  config/busola/tracepipeline_busola_extension_cm.yaml
Labels: lgtm, size/XS, area/documentation, cla: yes

#1098 chore: Bump telemetry-manager image to 1.16.0
  .env
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, cla: yes, area/release

#1009 feat: Introduce crd categories
  apis/operator/v1alpha1/telemetry_types.go
  apis/telemetry/v1alpha1/logparser_types.go
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/tracepipeline_types.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/tracepipeline_types.go
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
Labels: kind/feature, size/L, lgtm, area/manager, cla: yes

#1083 chore: Deprecate kyma provision gardener
  hack/make/provision.mk
  hack/shoot_gcp.yaml
Labels: lgtm, size/M, area/ci, kind/chore, cla: yes

#1104 chore: Fix rendering Gardener shoot spec
  hack/make/provision.mk
Labels: lgtm, size/XS, area/ci, kind/failing-test, cla: yes

#1105 chore: Fix gardener shot provisioning
  .env
  hack/make/provision.mk
Labels: lgtm, area/ci, kind/failing-test, size/S, cla: yes

#1100 docs: Leader Receiver Creator ADR
  docs/contributor/arch/012-leader-receiver-creator.md
Labels: lgtm, size/M, area/metrics, cla: yes, kind/decision

#1107 chore: Make Reconcilers unit-testable
  internal/istiostatus/istio_status_checker.go
  internal/reconciler/logpipeline/mocks/istio_status_checker.go
  internal/reconciler/logpipeline/mocks/overrides_handler.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/sync_test.go
  internal/reconciler/metricpipeline/mocks/istio_status_checker.go
  internal/reconciler/metricpipeline/mocks/overrides_handler.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/telemetry/mocks/overrides_handler.go
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/telemetry/reconciler_test.go
  internal/reconciler/tracepipeline/mocks/configmap_prober.go
  internal/reconciler/tracepipeline/mocks/istio_status_checker.go
  internal/reconciler/tracepipeline/mocks/overrides_handler.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
Labels: lgtm, kind/missing-test, size/XL, area/logs, area/metrics, area/traces, area/manager, cla: yes

#1085 feat: Update to otel-collector 0.100.0 image version
  docs/contributor/telemetry-load-test/README.md
  hack/load-tests/run-load-test.sh
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: kind/feature, lgtm, area/documentation, area/dependency, size/S, cla: yes

#1087 docs: Enhance Dynatrace guide for metric scenario
  docs/user/integration/dynatrace/README.md
  docs/user/integration/dynatrace/exporter-values.yaml
Labels: kind/feature, size/L, lgtm, area/documentation, cla: yes

#1112 chore: Rename ProbingNotReachable reason to ProbingFailed
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
Labels: size/L, lgtm, area/documentation, kind/chore, area/logs, area/metrics, area/traces, area/manager, cla: yes

#1108 feat: Bump Fluent Bit to 3.0.4
  Dockerfile
  docs/contributor/benchmarks/README.md
  docs/contributor/benchmarks/assets/log_perf_test_setup.drawio.svg
  docs/contributor/benchmarks/assets/metric_perf_test_setup.drawio.svg
  docs/contributor/benchmarks/assets/style.css
  docs/contributor/benchmarks/assets/trace_perf_test_setup.drawio.svg
  main.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/S, area/logs, cla: yes

#1113 feat: Bump Fluent Bit to 3.0.4 (#1108)
  Dockerfile
  docs/contributor/benchmarks/README.md
  docs/contributor/benchmarks/assets/log_perf_test_setup.drawio.svg
  docs/contributor/benchmarks/assets/metric_perf_test_setup.drawio.svg
  docs/contributor/benchmarks/assets/style.css
  docs/contributor/benchmarks/assets/trace_perf_test_setup.drawio.svg
  main.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/S, area/logs, cla: yes

#1116 chore: Update telemetry-manager image to 1.16.1
  .env
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#1117 chore: Pin linter version
  .env
  .github/workflows/pr-code-checks.yml
  hack/make/dependencies.mk
Labels: lgtm, size/M, cla: yes

#1110 test: Replace LogPipeline webhook envtests with unit tests
  webhook/logpipeline/webhook_suite_test.go
  webhook/logpipeline/webhook_test.go
Labels: area/tests, lgtm, size/XL, kind/chore, cla: yes

#1109 chore: Rewrite Metric/TracePipeline Reconciler unit tests
  .testcoverage.yml
  internal/reconciler/metricpipeline/mocks/pipeline_lock.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/tracepipeline/mocks/pipeline_lock.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/status_test.go
  internal/resourcelock/lock.go
  internal/resourcelock/lock_test.go
  internal/testutils/trace_pipeline_builder.go
Labels: lgtm, size/XXL, kind/chore, area/metrics, area/traces, cla: yes

#1114 feat: Bump Fluent Bit to 3.0.4 (#1108)
  .golangci.yaml
  Dockerfile
  docs/contributor/benchmarks/README.md
  docs/contributor/benchmarks/assets/log_perf_test_setup.drawio.svg
  docs/contributor/benchmarks/assets/metric_perf_test_setup.drawio.svg
  docs/contributor/benchmarks/assets/style.css
  docs/contributor/benchmarks/assets/trace_perf_test_setup.drawio.svg
  internal/k8sutils/owner_reference_setter.go
  main.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/S, area/logs, cla: yes

#1111 feat: Performance test and optimize self-monitor
  .github/workflows/pr-loadtest.yml
  docs/contributor/benchmarks/README.md
  docs/contributor/benchmarks/assets/log_perf_test_setup.drawio.svg
  docs/contributor/benchmarks/assets/metric_perf_test_setup.drawio.svg
  docs/contributor/benchmarks/assets/selfmonitor_perf_test_setup.drawio.svg
  docs/contributor/benchmarks/assets/trace_perf_test_setup.drawio.svg
  hack/load-tests/metric-load-test-setup.yaml
  hack/load-tests/run-load-test.sh
  hack/load-tests/self-monitor-test-setup.yaml
  hack/load-tests/trace-load-test-setup.yaml
  internal/resources/selfmonitor/resources.go
  internal/selfmonitor/config/config.go
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/testdata/config.yaml
  main.go
Labels: kind/feature, area/tests, lgtm, size/XL, area/documentation, area/logs, area/metrics, area/traces, cla: yes

#1123 chore: Update telemetry-manager image to 1.15.1
  .env
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, cla: yes

#1124 chore: Remove unneeded self-monitoring flags
  internal/reconciler/telemetry/reconciler.go
  internal/resources/common/resources.go
  internal/resources/selfmonitor/config.go
  internal/resources/selfmonitor/resources.go
  internal/resources/selfmonitor/resources_test.go
  main.go
Labels: size/L, lgtm, area/manager, cla: yes

#1121 chore: Rewrite LogPipeline Reconciler unit tests
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/logpipeline/sync_test.go
  internal/testutils/log_pipeline_builder.go
  test/e2e/logs_secret_rotation_test.go
  test/e2e/logs_unsupported_loki_output_test.go
Labels: lgtm, kind/missing-test, size/XXL, area/logs, cla: yes

#1125 fix: Stabilize flaky e2e self-monitoring tests
  test/integration/istio/metrics_self_monitor_outage_test.go
  test/integration/istio/traces_self_monitor_backpressure_test.go
  test/integration/istio/traces_self_monitor_outage_test.go
Labels: lgtm, size/XS, cla: yes

#1126 chore: Improve otelcol resource apply
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/config.go
  internal/resources/otelcollector/config_test.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  internal/resources/selfmonitor/resources.go
  internal/resources/selfmonitor/resources_test.go
Labels: size/L, lgtm, kind/chore, area/metrics, area/traces, cla: yes

#1130 chore: Mockable OTel Collector config builder
  .golangci.yaml
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/trace/gateway/config_builder.go
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/processors_test.go
  internal/reconciler/metricpipeline/mocks/agent_applier.go
  internal/reconciler/metricpipeline/mocks/agent_config_builder.go
  internal/reconciler/metricpipeline/mocks/gateway_applier.go
  internal/reconciler/metricpipeline/mocks/gateway_config_builder.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/tracepipeline/mocks/gateway_applier.go
  internal/reconciler/tracepipeline/mocks/gateway_config_builder.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/resources/otelcollector/agent.go
Labels: lgtm, size/XXL, kind/chore, area/metrics, area/traces, cla: yes

#1131 chore: Change self monitor condition messages
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/tracepipeline/reconciler_test.go
Labels: lgtm, size/M, kind/chore, cla: yes

#1132 chore: Include reconcilers in the test coverage check
  .testcoverage.yml
Labels: area/tests, lgtm, size/S, kind/chore, cla: yes

#1133 chore: Remove lint version check
  .github/workflows/pr-code-checks.yml
  hack/make/dependencies.mk
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1135 docs: Update pull-request-template.md
  .github/pull-request-template.md
Labels: lgtm, area/documentation, size/S, cla: yes

#1136 feat: Enable self monitor
  .github/workflows/pr-integration.yml
  config/development/kustomization.yaml
  config/manager/manager.yaml
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/reconciler/telemetry/metric_components_checker.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/telemetry/trace_components_checker.go
  internal/reconciler/telemetry/trace_components_checker_test.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/reconciler/tracepipeline/status.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/config.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  main.go
  test/e2e/logs_self_monitor_healthy_test.go
  test/e2e/metrics_self_monitor_healthy_test.go
  test/e2e/traces_self_monitor_healthy_test.go
  test/testkit/suite/suite.go
Labels: kind/feature, lgtm, size/XL, area/logs, area/metrics, area/traces, area/manager, cla: yes

#1137 docs: Fix example in the Dynatrace guide
  docs/user/integration/dynatrace/README.md
Labels: kind/bug, lgtm, area/documentation, cla: yes

#1138 feat: Add Flow Healthy print column
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/tracepipeline_types.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/tracepipeline_types.go
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
Labels: kind/feature, size/L, lgtm, area/documentation, area/logs, area/metrics, area/traces, cla: yes
