Repository kyma-project/telemetry-manager, pull requests merged in 2024-03, with the labels that each got.

#826 chore: Update gh action version
  .github/template/setup-golang/action.yaml
  .github/workflows/pr-code-checks.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#841 chore: Update tests to istio 1.3.2
  Makefile
Labels: lgtm, area/dependency, kind/chore, cla: yes

#842 chore: Determine supported gardenlinux version automated for gardener integration test
  Makefile
Labels: area/tests, lgtm, area/ci, cla: yes

#830 fix: Exclude metric scraping from Istio interception
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
Labels: kind/bug, lgtm, size/S, area/metrics, cla: yes

#846 fix: Exclude metric scraping from Istio interception
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
Labels: kind/bug, lgtm, size/S, area/metrics, cla: yes

#843 docs: Describe Otel log gateway PoC
  docs/contributor/pocs/assets/otel-gateway-pvc.yaml
  docs/contributor/pocs/assets/otel-log-agent-values.yaml
  docs/contributor/pocs/assets/otel-log-gateway-values.yaml
  docs/contributor/pocs/assets/otel-logs-values.yaml
  docs/contributor/pocs/assets/otlp-logs.drawio.svg
  docs/contributor/pocs/otlp-logs.md
Labels: size/L, lgtm, cla: yes

#833 feat: Introduce new status API for logs and traces
  apis/telemetry/v1alpha1/logparser_types.go
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/tracepipeline_types.go
  config/busola/logpipeline_busola_extension_cm.yaml
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/busola/tracepipeline_busola_extension_cm.yaml
  config/crd/bases/telemetry.kyma-project.io_logparsers.yaml
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/manager/kustomization.yaml
  controllers/operator/telemetry_controller_test.go
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/03-logparser.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  internal/conditions/conditions.go
  internal/conditions/conditions_test.go
  internal/reconciler/logparser/status.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/reconciler/telemetry/metric_components_checker.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/status.go
  internal/reconciler/telemetry/status_test.go
  internal/reconciler/telemetry/trace_components_checker.go
  internal/reconciler/telemetry/trace_components_checker_test.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
  internal/testutils/log_pipeline_builder.go
  internal/testutils/trace_pipeline_builder.go
  test/e2e/logs_annotation_test.go
  test/e2e/logs_basic_test.go
  test/e2e/logs_custom_output_test.go
  test/e2e/logs_dedot_test.go
  test/e2e/logs_exclude_container_test.go
  test/e2e/logs_exclude_namespaces_test.go
  test/e2e/logs_include_namespaces_test.go
  test/e2e/logs_label_test.go
  test/e2e/logs_mtls_test.go
  test/e2e/logs_parser_test.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_secret_rotation_test.go
  test/e2e/overrides_test.go
  test/e2e/traces_basic_test.go
  test/e2e/traces_mtls_test.go
  test/e2e/traces_multi_pipeline_test.go
  test/e2e/traces_noisy_span_filter_test.go
  test/e2e/traces_secret_rotation_test.go
  test/e2e/traces_service_name_test.go
  test/integration/istio/access_logs_test.go
  test/integration/istio/traces_test.go
  test/testkit/verifiers/logs.go
  test/testkit/verifiers/metrics.go
  test/testkit/verifiers/traces.go
Labels: kind/feature, lgtm, size/XXL, area/logs, area/traces, cla: yes

#851 chore: Prepare release 1.10.1
  Makefile
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#852 chore: Refactor status handling
  config/manager/kustomization.yaml
  internal/conditions/conditions.go
  internal/conditions/conditions_test.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/metric_components_checker.go
  internal/reconciler/telemetry/trace_components_checker.go
  internal/reconciler/tracepipeline/status_test.go
Labels: size/L, lgtm, kind/chore, area/logs, area/metrics, area/traces, cla: yes

#853 chore: Split SelfMonitor and Metric Agent Prometheus Receiver configs
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/relabel_configs.go
  internal/prometheus/config.go
  internal/reconciler/telemetry/reconciler.go
  internal/resources/selfmonitor/config.go
  internal/resources/selfmonitor/resources.go
  internal/resources/selfmonitor/resources_test.go
  internal/selfmonitor/config/config.go
  internal/selfmonitor/config/config_builder.go
  main.go
Labels: size/L, lgtm, kind/chore, area/manager, cla: yes

#832 chore: Simplify Makefile Architecture
  .env
  .github/template/prepare-test/action.yaml
  .github/workflows/branch-integration.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-lifecycle.yml
  .github/workflows/tag-release.yml
  Makefile
  docs/contributor/arch/009-makefile-architecture.md
  docs/contributor/assets/makefile-architecture.jpg
  docs/contributor/assets/makefile-graph-after.jpg
  docs/contributor/assets/makefile-graph-before.png
  docs/contributor/development.md
  docs/contributor/releasing.md
  hack/deploy-istio.sh
  hack/gardener-integration-test.sh
  hack/make/dependencies.mk
  hack/make/provision.mk
  hack/release.sh
  hack/upgrade-test.sh
Labels: lgtm, size/XL, cla: yes

#856 fix: Add priority class and fix network policy
  config/manager/manager.yaml
  internal/reconciler/telemetry/reconciler.go
  internal/resources/selfmonitor/resources.go
  internal/resources/selfmonitor/resources_test.go
  internal/selfmonitor/config/config.go
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/config_builder_test.go
  internal/selfmonitor/config/testdata/config.yaml
  main.go
Labels: kind/bug, lgtm, size/M, area/logs, area/metrics, area/traces, cla: yes

#863 fix: Get the Ginkgo path properly
  hack/gardener-integration-test.sh
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#859 fix: Broken indentation in list
  docs/contributor/arch/006-telemetry-api-v1beta1.md
Labels: lgtm, size/S, cla: yes

#855 feat: Add cpu.usage metrics and disable cpu.utilization metrics
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/testdata/config_istio_active.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_active.yaml
  test/testkit/otel/kubeletstats/metrics.go
Labels: lgtm, size/M, area/metrics, cla: yes

#864 fix: Bug fix manager initialization error handling
  main.go
Labels: kind/bug, lgtm, size/S, area/manager, cla: yes

#875 chore: Change the name of the WORKDIR in Dockerfile
  Dockerfile
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#817 chore: Add manual load test action
  .github/workflows/pr-loadtest.yml
  docs/contributor/telemetry-load-test/README.md
  hack/deploy-telemetry.sh
  hack/load-tests/log-fluentbit-backpressure-config.yaml
  hack/load-tests/log-fluentbit-max-pipeline.yaml
  hack/load-tests/log-fluentbit-test-setup.yaml
  hack/load-tests/metric-agent-backpressure-config.yaml
  hack/load-tests/metric-agent-test-setup.yaml
  hack/load-tests/metric-backpressure-config.yaml
  hack/load-tests/metric-load-test-setup.yaml
  hack/load-tests/metric-max-pipeline.yaml
  hack/load-tests/run-load-test.sh
  hack/load-tests/trace-backpressure-config.yaml
  hack/load-tests/trace-load-test-setup.yaml
  hack/load-tests/trace-max-pipeline.yaml
  hack/load-tests/values.yaml
  hack/make/provision.mk
Labels: size/L, lgtm, cla: yes

#877 chore: Bump images for 1.11 release
  .env
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#878 chore: Fix variables in release script
  .env
  Makefile
  hack/make/dependencies.mk
  hack/release.sh
Labels: lgtm, size/S, kind/chore, area/manager, cla: yes

#861 fix: Remove unnecessary list
  docs/contributor/releasing.md
Labels: lgtm, size/S, cla: yes

#880 chore: Fix release GitHub action
  .github/workflows/tag-release.yml
Labels: lgtm, size/XS, cla: yes

#881 chore: Fix release GitHub action
  .github/workflows/tag-release.yml
Labels: lgtm, size/XS, cla: yes

#883 chore: Fix the load test action
  .github/workflows/pr-loadtest.yml
  hack/deploy-telemetry.sh
Labels: kind/bug, lgtm, area/ci, size/S, cla: yes

#884 chore: Fix the deprovisioning
  .github/workflows/pr-loadtest.yml
Labels: kind/bug, lgtm, size/XS, area/ci, kind/chore, cla: yes

#885 docs: Fix Dynatrace integration guide
  docs/user/integration/dynatrace/README.md
Labels: kind/bug, lgtm, size/XS, area/documentation, cla: yes

#876 feat: Add scrape config for self-monitor
  internal/reconciler/telemetry/reconciler.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/config.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/gateway_test.go
  internal/resources/selfmonitor/config.go
  internal/resources/selfmonitor/resources.go
  internal/resources/selfmonitor/resources_test.go
  internal/selfmonitor/config/config.go
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/testdata/config.yaml
  main.go
Labels: kind/feature, size/L, lgtm, area/logs, area/metrics, area/traces, cla: yes

#860 docs: Remove unnecessary order for test-output documentation
  docs/contributor/telemetry-load-test/README.md
Labels: lgtm, size/M, cla: yes

#888 chore: Fix gardener cluster deployment for load test
  .env
  .github/workflows/pr-loadtest.yml
  hack/make/provision.mk
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#887 fix: Ensure pending condition is always preserved
  internal/conditions/conditions.go
  internal/conditions/conditions_test.go
  internal/reconciler/logparser/status.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
  test/testkit/verifiers/logs.go
  test/testkit/verifiers/traces.go
Labels: kind/bug, size/L, lgtm, area/manager, cla: yes

#869 feat: Introduce v1beta1 API for experimental channel
  Makefile
  apis/telemetry/v1beta1/groupversion_info.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/logpipeline_types_test.go
  apis/telemetry/v1beta1/logpipeline_validation.go
  apis/telemetry/v1beta1/logpipeline_validation_test.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/secret_refs.go
  apis/telemetry/v1beta1/secret_refs_test.go
  apis/telemetry/v1beta1/shared_types.go
  apis/telemetry/v1beta1/tracepipeline_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/development/crd/bases/operator.kyma-project.io_telemetries.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logparsers.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/development/crd/kustomization.yaml
  config/development/crd/kustomizeconfig.yaml
  config/development/kustomization.yaml
Labels: kind/feature, lgtm, size/XXL, area/manager, cla: yes

#891 fix: Ensure pending condition is always preserved
  internal/conditions/conditions.go
  internal/conditions/conditions_test.go
  internal/reconciler/logparser/status.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
  test/testkit/verifiers/logs.go
  test/testkit/verifiers/traces.go
Labels: kind/bug, size/L, lgtm, area/manager, cla: yes

#868 feat: Implement flow health probing
  .golangci.yaml
  controllers/telemetry/suite_test.go
  go.sum
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/status.go
  internal/resources/selfmonitor/config.go
  internal/selfmonitor/config/config.go
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/config_builder_test.go
  internal/selfmonitor/flowhealth/expr_builder.go
  internal/selfmonitor/flowhealth/mocks/alert_getter.go
  internal/selfmonitor/flowhealth/prober.go
  internal/selfmonitor/flowhealth/prober_test.go
  internal/selfmonitor/flowhealth/rules.go
  internal/selfmonitor/flowhealth/rules_test.go
  main.go
Labels: kind/feature, lgtm, size/XL, area/metrics, area/traces, cla: yes

#890 chore: Prepare release 1.11.1
  .env
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#898 chore: Update link for golangci-lint integration
  docs/contributor/governance.md
Labels: lgtm, size/XS, area/documentation, kind/chore, cla: yes

#899 feat: Ensure that auto-generated CRDs for development variant are always up-to-date
  hack/lint-manifests.sh
Labels: kind/feature, lgtm, size/S, area/manager, cla: yes

#897 test: Update test dependencies
  .env
Labels: lgtm, size/XS, cla: yes

#886 fix: Explicitly set previous release tag to fix the auto-generated changelogs
  hack/release.sh
Labels: kind/bug, lgtm, size/S, cla: yes, area/release

#892 feat: Reflect flow health probes in Pipeline status conditions
  controllers/operator/suite_test.go
  internal/conditions/conditions.go
  internal/reconciler/metricpipeline/mocks/daemonset_prober.go
  internal/reconciler/metricpipeline/mocks/flow_health_prober.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/metricpipeline/status_test.go
  internal/reconciler/telemetry/metric_components_checker.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/telemetry/trace_components_checker.go
  internal/reconciler/telemetry/trace_components_checker_test.go
  internal/reconciler/tracepipeline/mocks/deployment_prober.go
  internal/reconciler/tracepipeline/mocks/flow_health_prober.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
  internal/selfmonitor/flowhealth/mocks/alert_getter.go
  internal/selfmonitor/flowhealth/prober.go
  internal/selfmonitor/flowhealth/prober_test.go
  internal/selfmonitor/flowhealth/rules.go
  internal/selfmonitor/flowhealth/rules_test.go
  main.go
Labels: kind/feature, lgtm, size/XL, area/metrics, area/traces, area/manager, cla: yes

#882 chore: Bump otel image to 0.96.0
  docs/contributor/telemetry-load-test/README.md
  hack/load-tests/log-fluentbit-test-setup.yaml
  hack/load-tests/metric-agent-test-setup.yaml
  hack/load-tests/metric-load-test-setup.yaml
  hack/load-tests/run-load-test.sh
  hack/load-tests/trace-load-test-setup.yaml
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/deployment.go
Labels: lgtm, size/M, kind/chore, area/metrics, area/traces, cla: yes

#901 fix: Self-monitor alert matching
  apis/telemetry/v1alpha1/shared_types.go
  apis/telemetry/v1beta1/shared_types.go
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/otlpexporter/config_builder.go
  internal/otelcollector/config/otlpexporter/config_builder_test.go
  internal/otelcollector/config/trace/gateway/config_builder.go
  internal/selfmonitor/flowhealth/prober.go
  internal/selfmonitor/flowhealth/prober_test.go
  test/testkit/k8s/metric_pipeline_v1beta1.go
  test/testkit/k8s/trace_pipeline_v1beta1.go
Labels: kind/bug, size/L, lgtm, area/metrics, area/traces, cla: yes

#894 docs: Add documentation about access logs PoC
  docs/contributor/pocs/otlp-logs.md
Labels: size/L, lgtm, cla: yes

#902 feat: Add default status message to the self-monitor conditions
  internal/conditions/conditions.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/reconciler/telemetry/trace_components_checker_test.go
Labels: kind/feature, lgtm, size/S, area/metrics, area/traces, cla: yes

#905 chore: Improve conditions package
  internal/conditions/conditions.go
  internal/conditions/conditions_test.go
  internal/conditions/legacy.go
  internal/conditions/legacy_test.go
  internal/reconciler/logparser/status.go
  internal/reconciler/logparser/status_test.go
  internal/reconciler/logpipeline/status.go
  internal/reconciler/logpipeline/status_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/telemetry/log_components_checker.go
  internal/reconciler/telemetry/metric_components_checker.go
  internal/reconciler/telemetry/trace_components_checker.go
  internal/reconciler/tracepipeline/status.go
  internal/reconciler/tracepipeline/status_test.go
Labels: lgtm, size/XL, kind/chore, area/logs, area/metrics, area/traces, cla: yes

#911 chore: Unify Controller/Reconciler type names
  controllers/operator/suite_test.go
  controllers/operator/telemetry_controller.go
  controllers/telemetry/logparser_controller.go
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/suite_test.go
  controllers/telemetry/tracepipeline_controller.go
  main.go
Labels: size/L, lgtm, kind/chore, area/manager, cla: yes

#913 fix: Suppress otel-collector warning at startup by using localhost as default
  hack/load-tests/log-fluentbit-test-setup.yaml
  hack/load-tests/metric-agent-test-setup.yaml
  hack/load-tests/metric-load-test-setup.yaml
  hack/load-tests/run-load-test.sh
  hack/load-tests/trace-load-test-setup.yaml
  main.go
  sec-scanners-config.yaml
  test/testkit/mocks/backend/config_map.go
  test/testkit/mocks/backend/deployment.go
Labels: kind/bug, lgtm, size/M, area/metrics, area/traces, cla: yes

#915 test: Allow self-monitor to be deployed in dev mode
  .github/workflows/pr-integration.yml
  config/development/kustomization.yaml
  internal/resources/selfmonitor/resources.go
  main.go
  sec-scanners-config.yaml
  test/e2e/metrics_runtime_input_test.go
  test/e2e/self_monitor_basic_metrics_test.go
  test/e2e/self_monitor_basic_trace_test.go
  test/testkit/kyma/common_names.go
  test/testkit/verifiers/metrics.go
  test/testkit/verifiers/traces.go
Labels: size/L, lgtm, kind/missing-test, area/metrics, area/traces, cla: yes

#924 chore: Prepare release 1.12.0
  .env
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#929 chore: Update istio to 1.4.1
  .env
Labels: lgtm, size/XS, area/dependency, kind/chore, cla: yes

#912 feat: Trigger immediate reconciliation when self-monitor alert state changes
  .golangci.yaml
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/suite_test.go
  controllers/telemetry/tracepipeline_controller.go
  go.mod
  internal/reconciler/telemetry/reconciler.go
  internal/selfmonitor/config/config.go
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/config_builder_test.go
  internal/selfmonitor/config/testdata/config.yaml
  internal/selfmonitor/webhook/handler.go
  internal/selfmonitor/webhook/handler_test.go
  main.go
Labels: size/L, lgtm, cla: yes

#900 chore: Update controller-tools
  .env
  apis/operator/v1alpha1/telemetry_types.go
  config/crd/bases/operator.kyma-project.io_telemetries.yaml
  config/crd/bases/telemetry.kyma-project.io_logparsers.yaml
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/development/crd/bases/operator.kyma-project.io_telemetries.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logparsers.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  config/rbac/role.yaml
  docs/user/resources/01-telemetry.md
Labels: lgtm, size/XXL, cla: yes

#933 docs: Fix unordered lists
  docs/user/gateways.md
Labels: lgtm, size/XS, cla: yes

#932 test: Self-monitor webhook E2E test
  .github/workflows/pr-integration.yml
  .golangci.yaml
  go.mod
  test/e2e/manager_test.go
  test/e2e/metrics_namespace_selector_test.go
  test/e2e/metrics_otlp_input_test.go
  test/e2e/metrics_self_monitor_basic_test.go
  test/e2e/traces_self_monitor_basic_test.go
  test/testkit/kyma/common_names.go
  test/testkit/matchers/prometheus/prometheus_matcher.go
  test/testkit/matchers/prometheus/prometheus_matcher_test.go
  test/testkit/mocks/telemetrygen/telemetrygen.go
  test/testkit/verifiers/metrics.go
  test/testkit/verifiers/monitoring.go
  test/testkit/verifiers/self_monitor.go
  test/testkit/verifiers/telemetry.go
  test/testkit/verifiers/traces.go
Labels: area/tests, size/L, lgtm, cla: yes

#934 docs: Add ADR for LogPipeline health status
  docs/contributor/arch/010-logging-flow-healthiness-status-api.md
  docs/contributor/assets/fluent-bit-data-flow.drawio.svg
Labels: lgtm, size/M, cla: yes
