Repository kyma-project/telemetry-manager, pull requests merged in 2025-02, with the labels that each got.

#1778 feat: Add cloud provider info to the gateways
  .k3d-kyma.yaml
  config/rbac/role.yaml
  docs/contributor/assets/multi_pipeline_gateway_with_connectors.yaml
  docs/contributor/assets/single_pipeline_gateway_with_connectors.yaml
  internal/otelcollector/config/gatewayprocs/k8s_attribute_proc.go
  internal/otelcollector/config/gatewayprocs/k8s_attribute_proc_test.go
  internal/otelcollector/config/gatewayprocs/resource_procs.go
  internal/otelcollector/config/gatewayprocs/resource_procs_test.go
  internal/otelcollector/config/log/gateway/config.go
  internal/otelcollector/config/log/gateway/config_builder.go
  internal/otelcollector/config/log/gateway/config_builder_test.go
  internal/otelcollector/config/log/gateway/processors.go
  internal/otelcollector/config/log/gateway/processors_test.go
  internal/otelcollector/config/log/gateway/testdata/config.yaml
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/service.go
  internal/otelcollector/config/metric/gateway/service_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/metric/gateway/testdata/config_otlp_disabled.yaml
  internal/otelcollector/config/trace/gateway/config.go
  internal/otelcollector/config/trace/gateway/config_builder.go
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/processors.go
  internal/otelcollector/config/trace/gateway/processors_test.go
  internal/otelcollector/config/trace/gateway/testdata/config.yaml
  internal/reconciler/logpipeline/otel/mocks/gateway_config_builder.go
  internal/reconciler/logpipeline/otel/reconciler.go
  internal/reconciler/logpipeline/otel/reconciler_test.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/mocks/gateway_config_builder.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/resources/otelcollector/rbac.go
  internal/resources/otelcollector/testdata/log-gateway.yaml
  internal/resources/otelcollector/testdata/metric-gateway-istio.yaml
  internal/resources/otelcollector/testdata/metric-gateway.yaml
  internal/resources/otelcollector/testdata/trace-gateway.yaml
  internal/utils/k8s/cluster_info_getter.go
  internal/utils/k8s/cluster_info_getter_test.go
  main.go
  test/e2e/metrics_runtime_input_test.go
  test/integration/istio/metrics_cloud_provider_attributes_test.go
  test/testkit/k8s/configmap.go
Labels: kind/feature, area/tests, lgtm, size/XL, area/logs, area/metrics, area/traces, area/manager, cla: yes

#1798 fix: Metric kyma.resource.status.state gets filtered-out by namespace filter
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/service.go
  internal/otelcollector/config/metric/gateway/service_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/metric/gateway/testdata/config_otlp_disabled.yaml
Labels: kind/bug, area/tests, size/L, lgtm, area/metrics, cla: yes

#1804 chore: Prepare images for 1.33.0 release
  .env
  config/manager/kustomization.yaml
  internal/images/images.go
  main.go
  sec-scanners-config.yaml
Labels: size/S, kind/chore, cla: yes, area/release

#1782 chore: Improved Dockerfile of sample-app
  Dockerfile
  docs/user/integration/sample-app/Dockerfile
Labels: size/M, kind/chore, cla: yes, area/release

#1807 chore: Rename operation tests to upgrade tests
  .github/workflows/pr-upgrade.yml
  docs/contributor/assets/test-pyramid.drawio.svg
  docs/contributor/testing.md
  test/e2e/logs_basic_v1alpha1_test.go
  test/e2e/logs_otlp_output_test.go
  test/e2e/metrics_basic_v1alpha1_test.go
  test/e2e/metrics_basic_v1beta1_test.go
  test/e2e/suite_test.go
  test/e2e/traces_basic_v1alpha1_test.go
  test/integration/istio/metrics_self_monitor_outage_test.go
  test/integration/istio/suite_test.go
  test/testkit/suite/suite.go
Labels: area/tests, size/L, lgtm, kind/chore, cla: yes

#1793 feat: Consistent labelling
  config/busola/logpipeline_busola_extension_cm.yaml
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/busola/telemetry_busola_extension_cm.yaml
  config/busola/tracepipeline_busola_extension_cm.yaml
  config/default/kustomization.yaml
  config/development/kustomization.yaml
  config/samples/operator_v1alpha1_telemetry.yaml
  internal/reconciler/logparser/sync.go
  internal/reconciler/logpipeline/fluentbit/reconciler.go
  internal/reconciler/logpipeline/fluentbit/sync.go
  internal/resources/common/annotations.go
  internal/resources/common/labels.go
  internal/resources/common/resources.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/rbac.go
  internal/resources/otelcollector/testdata/log-gateway.yaml
  internal/resources/otelcollector/testdata/metric-agent.yaml
  internal/resources/otelcollector/testdata/metric-gateway-istio.yaml
  internal/resources/otelcollector/testdata/metric-gateway.yaml
  internal/resources/otelcollector/testdata/trace-gateway.yaml
  internal/resources/selfmonitor/config.go
  internal/resources/selfmonitor/resources.go
  internal/resources/selfmonitor/resources_test.go
  internal/resources/selfmonitor/testdata/self-monitor.yaml
  internal/utils/k8s/utils.go
  internal/utils/k8s/utils_test.go
  main.go
Labels: kind/feature, size/XL, area/manager, cla: yes

#1808 chore: Rename security-scanners-config fields
  internal/tools/populateimages/main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, cla: yes, area/release

#1811 chore: Update to golang 1.23.6
  .env
  .github/dependabot.yml
  Dockerfile
  docs/user/integration/sample-app/Dockerfile
  docs/user/integration/sample-app/go.mod
  go.mod
  internal/images/images.go
  internal/tools/go.mod
  sec-scanners-config.yaml
  test/testkit/images.go
Labels: lgtm, size/M, area/dependency, kind/chore, cla: yes

#1786 feat: Add otel log agent
  .mockery.yaml
  apis/telemetry/v1alpha1/logpipeline_types.go
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  controllers/telemetry/logpipeline_controller.go
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  internal/conditions/conditions.go
  internal/otelcollector/config/log/agent/config.go
  internal/otelcollector/config/log/agent/config_builder.go
  internal/otelcollector/config/log/agent/config_builder_test.go
  internal/otelcollector/config/log/agent/extension.go
  internal/otelcollector/config/log/agent/extension_test.go
  internal/otelcollector/config/log/agent/processors.go
  internal/otelcollector/config/log/agent/processors_test.go
  internal/otelcollector/config/log/agent/receivers.go
  internal/otelcollector/config/log/agent/receivers_test.go
  internal/otelcollector/config/log/agent/testdata/config.yaml
  internal/otelcollector/config/log/config.go
  internal/reconciler/logpipeline/fluentbit/reconciler.go
  internal/reconciler/logpipeline/fluentbit/reconciler_test.go
  internal/reconciler/logpipeline/otel/mocks/agent_applier_deleter.go
  internal/reconciler/logpipeline/otel/mocks/agent_config_builder.go
  internal/reconciler/logpipeline/otel/reconciler.go
  internal/reconciler/logpipeline/otel/reconciler_test.go
  internal/reconciler/logpipeline/otel/status.go
  internal/reconciler/telemetry/log_components_checker_test.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/agent_test.go
  internal/resources/otelcollector/core_pod_spec.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/testdata/log-agent.yaml
  internal/utils/test/log_pipeline_builder.go
  main.go
  test/e2e/logs_otlp_runtime_input_test.go
  test/testkit/kyma/common_names.go
  test/testkit/matchers/log/log_otel_matchers.go
  test/testkit/matchers/log/log_otel_matchers_test.go
  test/testkit/matchers/log/plog_otel_utils.go
  webhook/logpipeline/v1alpha1/defaulter.go
  webhook/logpipeline/v1alpha1/defaulter_test.go
  webhook/logpipeline/v1alpha1/setup.go
Labels: kind/feature, lgtm, size/XXL, area/logs, cla: yes

#1806 fix: Delete metric agent resources when no longer needed
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  test/e2e/metrics_no_input_test.go
  test/testkit/assert/daemon_set.go
Labels: kind/bug, size/L, lgtm, area/metrics, cla: yes

#1815 fix: Delete OTLP log agent resources when no longer needed
  docs/contributor/development.md
  internal/reconciler/logpipeline/otel/reconciler.go
  internal/reconciler/logpipeline/otel/reconciler_test.go
  internal/reconciler/metricpipeline/reconciler_test.go
  test/e2e/logs_otlp_no_input_test.go
Labels: kind/bug, size/L, lgtm, area/logs, cla: yes

#1823 docs: Update dynatrace integration to newest otel-collector version
  docs/user/integration/dynatrace/exporter-values.yaml
Labels: lgtm, size/XS, area/documentation, cla: yes, kind/docs

#1827 chore: Synchronize renovate settings from other repositories
  renovate.json
Labels: size/M, area/ci, kind/chore, cla: yes

#1819 feat: Set milestone and kind label automatically
  .github/workflows/pr-github-checks.yml
  .github/workflows/titleprefix_to_label.json
Labels: kind/feature, size/M, area/ci, cla: yes

#1837 chore: checkout code to be accessible in github action
  .github/workflows/pr-github-checks.yml
Labels: lgtm, size/XS, cla: yes

#1838 chore: fix milestone automation and remove project automation
  .github/workflows/pr-github-checks.yml
Labels: size/XS, kind/chore, cla: yes

#1839 chore: use GH_REPO for milestone action
  .github/workflows/pr-github-checks.yml
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1840 chore: replace dependabot by renovate
  .github/dependabot.yml
Labels: size/M, area/dependency, kind/chore, cla: yes

#1844 chore: specify the version of alpine in the build container
  Dockerfile
  docs/user/integration/sample-app/Dockerfile
Labels: size/XS, area/ci, kind/chore, cla: yes

#1814 feat: Add log label support for OTLP log gateway
  .golangci.yaml
  apis/operator/v1alpha1/telemetry_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1beta1/logpipeline_types.go
  config/development/crd/bases/operator.kyma-project.io_telemetries.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  internal/otelcollector/config/gatewayprocs/k8s_attribute_proc.go
  internal/otelcollector/config/gatewayprocs/k8s_attribute_proc_test.go
  internal/otelcollector/config/log/gateway/config_builder.go
  internal/otelcollector/config/log/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/processors.go
  internal/otelcollector/config/trace/gateway/processors.go
  internal/reconciler/logpipeline/otel/reconciler.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/utils/telemetry/utils.go
  internal/utils/telemetry/utils_test.go
  test/e2e/logs_otlp_enrichments_extract_labels_test.go
Labels: kind/feature, size/XL, area/logs, area/manager, cla: yes

#1797 docs: Fault tolerant OTel logging setup ADR
  docs/contributor/arch/017-fault-tolerant-otel-logging-setup.md
  docs/contributor/assets/log-agent-batch-processor-flow.svg
  docs/contributor/assets/log-agent-exporter-batcher-flow.svg
  docs/contributor/assets/log-agent-no-batch-processor-flow.svg
Labels: size/L, lgtm, area/logs, cla: yes, kind/docs

#1846 chore: enable gha update
  renovate.json
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1845 chore: Add e2e metrics test set C and balance-out the 3 sets
  .github/workflows/pr-integration.yml
  test/e2e/metrics_endpoint_invalid_test.go
  test/e2e/metrics_endpoint_path_validation_test.go
  test/e2e/metrics_endpoint_port_test.go
  test/e2e/metrics_endpoint_with_path_test.go
  test/e2e/metrics_multi_pipeline_broken_pipeline_test.go
  test/e2e/metrics_multi_pipeline_namespace_selector_test.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_resources_test.go
  test/e2e/metrics_runtime_node_namespace_test.go
  test/e2e/metrics_secret_rotation_test.go
  test/integration/istio/metrics_cloud_provider_attributes_test.go
  test/testkit/suite/suite.go
Labels: area/tests, lgtm, size/S, kind/chore, cla: yes

#1857 fix: Trigger LogPipeline reconciliation after Telemetry resource updates
  controllers/telemetry/logpipeline_controller.go
Labels: kind/bug, size/M, area/logs, cla: yes

#1863 chore: Bump prometheus image to 3.2.0
  dependencies/telemetry-self-monitor/envs
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1861 docs: improve documentation for prometheus metrics
  docs/user/04-metrics.md
Labels: lgtm, size/XS, area/metrics, cla: yes, kind/docs

#1866 fix: e2e tests no input should not be upgrade tests
  test/e2e/logs_otlp_no_input_test.go
  test/e2e/metrics_no_input_test.go
Labels: kind/bug, area/tests, lgtm, size/S, cla: yes

#1860 chore: Rename logpipeline samples for consistency reasons
  config/samples/telemetry_v1alpha1_logpipeline.yaml
  config/samples/telemetry_v1alpha1_logpipeline_otlp.yaml
Labels: lgtm, size/M, kind/chore, area/logs, cla: yes

#1867 fix: Dont share the hostpath with other deployments
  internal/otelcollector/config/log/agent/extension_test.go
  internal/otelcollector/config/log/agent/testdata/config.yaml
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/testdata/log-agent.yaml
Labels: kind/bug, size/S, area/logs, cla: yes

#1862 fix: Security warning "prone to resource exhaustion"
  internal/selfmonitor/webhook/handler.go
Labels: kind/bug, size/XS, area/manager, cla: yes

#1865 chore: Update self-monitor to prometheus 3.2.0
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#1868 docs: OTel logging agent configuration proposal
  docs/contributor/arch/018-otel-logging-agent-configuration.md
  docs/contributor/assets/logs-otel-agent.drawio.svg
Labels: size/XXL, area/documentation, do-not-merge/hold, cla: yes, kind/docs

#1881 chore: Bump x/oauth2 dependency
  go.mod
  go.sum
Labels: lgtm, size/XS, kind/chore, area/manager, cla: yes

#1876 feat: Update to fluent-bit 3.2.7
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/S, area/logs, cla: yes

#1880 docs: Add a disclaimer to avoid using internal metrics
  docs/user/01-manager.md
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
Labels: area/documentation, size/S, cla: yes, kind/docs

#1884 fix: reset forbidden github actions to allowed values
  .github/workflows/pr-github-checks.yml
Labels: kind/bug, lgtm, size/XS, area/ci, cla: yes

#1883 chore: limit alerts payload size
  internal/selfmonitor/webhook/handler.go
  internal/selfmonitor/webhook/handler_test.go
Labels: lgtm, size/M, kind/chore, area/manager, cla: yes
