Repository kyma-project/telemetry-manager, pull requests merged in 2025-03, with the labels that each got.

#1894 chore: add additional permissions for image builder
  .github/workflows/build-image.yml
  .github/workflows/build-sample-app-image.yml
  .github/workflows/build-telemetry-self-monitor-image.yml
Labels: lgtm, size/M, area/ci, kind/chore

#1897 chore: prepare release-1.35
  .env
  config/manager/kustomization.yaml
  internal/images/images.go
  main.go
  sec-scanners-config.yaml
Labels: lgtm, size/S, kind/chore, area/release

#1895 chore: add permissions to create a release
  .github/workflows/tag-release.yml
Labels: lgtm, size/XS, kind/chore, area/release

#1898 chore: add permissions to create a release (#1895)
  .github/workflows/tag-release.yml
Labels: lgtm, size/XS, area/ci, kind/chore

#1896 docs: Rephrase backward compatibility annotation
  docs/user/resources/01-telemetry.md
Labels: lgtm, area/documentation, size/S, area/manager, kind/docs

#1796 chore: Refactor fluent bit reconciler for golden file unit tests
  .mockery.yaml
  .testcoverage.yml
  controllers/telemetry/logpipeline_controller.go
  internal/reconciler/logpipeline/fluentbit/mocks/agent_applier_deleter.go
  internal/reconciler/logpipeline/fluentbit/reconciler.go
  internal/reconciler/logpipeline/fluentbit/reconciler_test.go
  internal/reconciler/logpipeline/fluentbit/status.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  internal/resources/fluentbit/sync.go
  internal/resources/fluentbit/sync_test.go
  internal/resources/fluentbit/testdata/fluentbit.yaml
  test/e2e/logs_mtls_missing_values_test.go
Labels: area/tests, size/XXL, kind/chore, cla: yes

#1886 chore: limit job execution of the e2e tests
  .github/workflows/pr-integration.yml
Labels: lgtm, area/ci, size/S, kind/chore, cla: yes

#1869 feat: Move log gateway to agent
  controllers/telemetry/logpipeline_controller.go
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/input.go
  internal/fluentbit/config/builder/input_test.go
  internal/otelcollector/config/log/agent/config.go
  internal/otelcollector/config/log/agent/config_builder.go
  internal/otelcollector/config/log/agent/config_builder_test.go
  internal/otelcollector/config/log/agent/processors.go
  internal/otelcollector/config/log/agent/processors_test.go
  internal/otelcollector/config/log/agent/receivers.go
  internal/otelcollector/config/log/agent/receivers_test.go
  internal/otelcollector/config/log/agent/testdata/config.yaml
  internal/otelcollector/config/log/agent/testdata/config_compatibility_enabled.yaml
  internal/otelcollector/config/log/gateway/config_builder.go
  internal/otelcollector/config/log/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/otlpexporter/config_builder.go
  internal/otelcollector/config/processors/k8s_attribute_proc.go
  internal/otelcollector/config/processors/k8s_attribute_proc_test.go
  internal/otelcollector/config/processors/resolve_service_name_proc.go
  internal/otelcollector/config/processors/resolve_service_name_proc_test.go
  internal/otelcollector/config/processors/resource_procs.go
  internal/otelcollector/config/processors/resource_procs_test.go
  internal/otelcollector/config/trace/gateway/processors.go
  internal/reconciler/logpipeline/otel/mocks/agent_config_builder.go
  internal/reconciler/logpipeline/otel/reconciler.go
  internal/reconciler/logpipeline/otel/reconciler_test.go
  internal/resources/common/resources.go
  internal/resources/fluentbit/testdata/fluentbit.yaml
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/rbac.go
  internal/resources/otelcollector/testdata/log-agent.yaml
  internal/selfmonitor/config/rules.go
  internal/utils/test/log_pipeline_builder.go
  test/e2e/logs_otlp_enrichments_extract_labels_test.go
  test/e2e/logs_otlp_multi_pipeline_namespace_selector_test.go
  test/e2e/logs_otlp_multi_pipeline_test.go
  test/integration/istio/log_otlp_self_monitor_backpressure_test.go
  test/integration/istio/log_otlp_self_monitor_outage_test.go
  test/testkit/assert/logs.go
  test/testkit/matchers/log/log_otel_matchers.go
Labels: kind/feature, lgtm, size/XXL, area/logs, cla: yes

#1908 docs: Review language for gateways doc
  docs/user/gateways.md
Labels: lgtm, area/documentation, size/S, kind/docs

#1907 chore: Update to golang 1.24.1
  .env
  go.mod
  internal/images/images.go
  internal/tools/go.mod
  sec-scanners-config.yaml
  test/testkit/mocks/prommetricgen/metric_producer.go
Labels: area/dependency, size/S, kind/chore

#1916 chore: Improve exclude pattern for upgrade test job
  .github/workflows/pr-upgrade.yml
Labels: area/ci, size/S, kind/chore

#1925 chore: Exclude docs from integration test workflows
  .github/workflows/pr-integration.yml
  .github/workflows/pr-upgrade.yml
Labels: area/ci, kind/chore

#1914 docs: Adjust sample-app metric name with otel conventions
  docs/user/integration/sample-app/README.md
  docs/user/integration/sample-app/main.go
Labels: size/XS, area/documentation, kind/docs

#1927 chore: Update x-net and x-tools lib
  go.mod
  go.sum
  internal/tools/go.mod
  internal/tools/go.sum
Labels: area/dependency, kind/chore

#1931 chore: Update x-net and x-tools lib for sample-app
  docs/user/integration/sample-app/go.mod
  docs/user/integration/sample-app/go.sum
Labels: area/dependency, kind/chore

#1934 feat: Update to FLuentBit 3.2.8
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
Labels: kind/feature, area/logs

#1936 docs: Support both HTTP and gRPC OTLP protocols in the sample app
  docs/user/integration/sample-app/go.mod
  docs/user/integration/sample-app/go.sum
  docs/user/integration/sample-app/main.go
  docs/user/integration/sample-app/setup.go
Labels: area/documentation, kind/docs

#1930 docs: Explain in more detail the push URLs for gateways
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/assets/gateways-istio.drawio.svg
  docs/user/assets/gateways-plain.drawio.svg
  docs/user/gateways.md
Labels: area/metrics, area/traces, kind/docs

#1940 docs: Edit gateway doc
  docs/user/assets/gateways-plain.drawio.svg
  docs/user/gateways.md
Labels: area/documentation, kind/docs

#1948 fix: Use version tag for tj-actions/changed-files
  .github/workflows/pr-github-checks.yml
Labels: kind/bug, area/ci

#1941 fix: Add support for EC private key validation
  .gitleaksignore
  internal/conditions/tls_cert_conditions_test.go
  internal/reconciler/logpipeline/fluentbit/reconciler_test.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/validators/tlscert/tls_cert_validator.go
  internal/validators/tlscert/tls_cert_validator_test.go
Labels: kind/bug, area/logs, area/metrics, area/traces

#1954 chore: prepare images for 1.36.0 release
  .env
  config/manager/kustomization.yaml
  internal/images/images.go
  main.go
  sec-scanners-config.yaml
Labels: kind/chore, area/release

#1955 chore: ensure PR titel subject doesn't start with an uppercase character
  .github/workflows/pr-github-checks.yml
Labels: area/ci, kind/chore

#1956 chore(ci): require no scope
  .github/workflows/pr-github-checks.yml
Labels: area/ci, kind/chore

#1905 chore: introduce ConfigBuilder for FluentBit
  .mockery.yaml
  controllers/telemetry/logpipeline_controller.go
  internal/fluentbit/config/builder/config_builder.go
  internal/fluentbit/config/builder/config_builder_test.go
  internal/fluentbit/config/builder/env_var.go
  internal/fluentbit/config/builder/env_var_test.go
  internal/fluentbit/config/builder/files_config_builder.go
  internal/fluentbit/config/builder/output.go
  internal/fluentbit/config/builder/output_test.go
  internal/fluentbit/config/builder/rewritetag_filter.go
  internal/fluentbit/config/builder/rewritetag_filter_test.go
  internal/fluentbit/config/builder/secrets_config_builder.go
  internal/fluentbit/config/builder/sections_config_builder.go
  internal/fluentbit/config/builder/sections_config_builder_test.go
  internal/reconciler/logpipeline/fluentbit/mocks/agent_config_builder.go
  internal/reconciler/logpipeline/fluentbit/reconciler.go
  internal/reconciler/logpipeline/fluentbit/reconciler_test.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  internal/resources/fluentbit/sync.go
  internal/resources/fluentbit/sync_test.go
  internal/resources/fluentbit/testdata/fluentbit.yaml
Labels: size/XXL, kind/chore, area/logs

#1855 docs: proposal for switching gateways to a central agent
  docs/contributor/arch/001-otel-collector-metric-based-pipeline-status.md
  docs/contributor/arch/005-do-not-make-prometheus-part of-the-istio-service-mesh.md
  docs/contributor/arch/008-telemetry-flow-healthiness-status-api.md
  docs/contributor/arch/009-makefile-architecture.md
  docs/contributor/arch/010-logging-flow-healthiness-status-api.md
  docs/contributor/arch/011-kymastatsmetrics.md
  docs/contributor/arch/012a-leader-receiver-creator.md
  docs/contributor/arch/012b-leader-receiver-creator-as-extension.md
  docs/contributor/arch/013-resource-attributes-enrichment-for-non-workload-metrics.md
  docs/contributor/arch/014-telemetry-self-monitor-storage.md
  docs/contributor/arch/015-impact-of-istio-prometheus-merge-on-metric-pipelines.md
  docs/contributor/arch/016-transform-filter-support-for-telemetry-pipelines.md
  docs/contributor/arch/017-fault-tolerant-otel-logging-setup.md
  docs/contributor/arch/018-otel-logging-agent-configuration.md
  docs/contributor/arch/019-switch-from-gateways-to-a-central-agent.md
  docs/contributor/assets/otlp-gateway-new.drawio.svg
  docs/contributor/assets/otlp-gateway-old.drawio.svg
Labels: size/XXL, area/documentation, cla: yes, kind/docs

#1960 chore: use latest sample-app in E2E tests
  test/testkit/mocks/prommetricgen/metric_producer.go
Labels: area/tests, kind/chore

#1959 feat: add support for URL parameter annotations in scraping
  docs/user/integration/sample-app/deployment/deployment-prometheus.yaml
  docs/user/integration/sample-app/main.go
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/prometheus_receiver.go
  internal/otelcollector/config/metric/agent/testdata/config_compatibility_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
Labels: kind/feature, area/metrics

#1939 chore: change optional fields with no built-in nil value to be pointer
  apis/telemetry/v1alpha1/logpipeline_conversion_test.go
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  internal/fluentbit/config/builder/kubernetes_filter.go
  internal/fluentbit/config/builder/kubernetes_filter_test.go
  internal/fluentbit/config/builder/sections_config_builder_test.go
  internal/utils/test/log_pipeline_builder.go
Labels: kind/chore, area/logs

#1963 docs: support for URL parameter annotations in scraping
  docs/user/04-metrics.md
  docs/user/integration/sample-app/main.go
Labels: area/documentation, kind/docs

#1964 chore: exclude sample-app and all docs from security scanning
  internal/tools/populateimages/main.go
  sec-scanners-config.yaml
Labels: area/ci, kind/chore

#1965 chore: add E2E test for URL parameter annotations in scraping
  test/e2e/metrics_multi_pipeline_namespace_selector_test.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/integration/istio/metrics_prometheus_input_test.go
  test/testkit/mocks/prommetricgen/metric_producer.go
Labels: area/tests, kind/chore, area/metrics

#1969 docs: update otel-demo integration guide to latest version
  docs/user/integration/opentelemetry-demo/README.md
  docs/user/integration/opentelemetry-demo/values.yaml
Labels: area/documentation, kind/docs

#1981 chore: bump OTel version to 0.122.1
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
  test/testkit/images.go
Labels: area/documentation, kind/chore, area/metrics, area/traces, area/manager

#1991 chore: update fluentbit image to 3.2.10
  external-images.yaml
Labels: area/ci, kind/chore

#1993 feat: update to fluentbit 3.2.10
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
Labels: kind/feature, area/logs

#1998 docs: fix jaeger integration guide
  docs/user/integration/jaeger/values.yaml
Labels: area/documentation, kind/docs

#1947 docs: add documentation for node local traffic
  config/samples/telemetry_v1alpha1_logpipeline__with_agent_otlp.yaml
  docs/contributor/arch/019-switch-from-gateways-to-a-central-agent.md
  docs/contributor/pocs/node-local-traffic/node-local-traffic.md
  docs/contributor/pocs/node-local-traffic/trace-agent.yaml
  docs/contributor/pocs/node-local-traffic/trace-gen.yaml
Labels: area/documentation, kind/docs

#1973 feat: add service name enrichment processor
  internal/otelcollector/config/config.go
  internal/otelcollector/config/log/agent/config.go
  internal/otelcollector/config/log/agent/config_builder.go
  internal/otelcollector/config/log/agent/config_builder_test.go
  internal/otelcollector/config/log/agent/processors.go
  internal/otelcollector/config/log/agent/testdata/config.yaml
  internal/otelcollector/config/log/agent/testdata/config_compatibility_enabled.yaml
  internal/otelcollector/config/log/gateway/config.go
  internal/otelcollector/config/log/gateway/config_builder.go
  internal/otelcollector/config/log/gateway/config_builder_test.go
  internal/otelcollector/config/log/gateway/processors.go
  internal/otelcollector/config/log/gateway/testdata/config.yaml
  internal/otelcollector/config/log/gateway/testdata/config_compatibility_enabled.yaml
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/service.go
  internal/otelcollector/config/metric/gateway/service_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/metric/gateway/testdata/config_compatibility_enabled.yaml
  internal/otelcollector/config/metric/gateway/testdata/config_otlp_disabled.yaml
  internal/otelcollector/config/processors/k8s_attribute_proc.go
  internal/otelcollector/config/processors/resolve_service_name_proc.go
  internal/otelcollector/config/processors/resolve_service_name_proc_test.go
  internal/otelcollector/config/processors/resource_procs.go
  internal/otelcollector/config/trace/gateway/config.go
  internal/otelcollector/config/trace/gateway/config_builder.go
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/processors.go
  internal/otelcollector/config/trace/gateway/testdata/config.yaml
  internal/otelcollector/config/trace/gateway/testdata/config_compatibility_enabled.yaml
  test/e2e/logs/otel/runtime_input_service_name_test.go
  test/e2e/logs/otel/service_name_test.go
  test/e2e/metrics/service_name_test.go
  test/e2e/traces/service_name_test.go
  test/testkit/mocks/loggen/log_producer.go
  test/testkit/mocks/servicenamebundle/service_name_bundle.go
Labels: kind/feature, area/metrics

#1999 chore: fix lint violations in Istio tests
  .golangci.yaml
  Makefile
  test/integration/istio/access_logs_test.go
  test/integration/istio/metrics_cloud_provider_attributes_test.go
  test/integration/istio/metrics_istio_input_test.go
  test/integration/istio/metrics_otlp_input_test.go
  test/integration/istio/metrics_self_monitor_outage_test.go
  test/integration/istio/suite_test.go
  test/integration/istio/traces_self_monitor_outage_test.go
  test/integration/istio/traces_test.go
Labels: area/tests, kind/chore
