Repository kyma-project/telemetry-manager, pull requests merged in 2025-04, with the labels that each got.

#2006 docs: align GitHub and Help Portal
  docs/user/04-metrics.md
Labels: area/documentation, area/metrics, kind/docs

#1996 feat: expose telemetry compatibility mode metric
  Makefile
  docs/contributor/telemetry-internal-metrics.md
  hack/telemetry-internal-metrics.md.tpl
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/telemetry/telemetry_metric_emitter.go
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: kind/feature, area/documentation, area/logs, area/metrics, area/traces, area/manager

#2009 chore: bump images version to 1.37.0
  .env
  config/manager/kustomization.yaml
  internal/images/images.go
  main.go
  sec-scanners-config.yaml
Labels: kind/chore, area/release

#2011 chore: migrate slack GH action to version 2
  .github/workflows/branch-integration.yml
  .github/workflows/build-image.yml
  .github/workflows/slack-message.json
Labels: area/ci, kind/chore

#1997 feat: set default values for diagnostic and envoy metrics when user not sets
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  docs/user/resources/05-metricpipeline.md
  internal/utils/metricpipeline/metricpipeline.go
  internal/utils/test/metric_pipeline_builder.go
  webhook/metricpipeline/v1alpha1/defaulter.go
  webhook/metricpipeline/v1alpha1/defaulter_test.go
  webhook/metricpipeline/v1alpha1/setup.go
  webhook/metricpipeline/v1beta1/defaulter.go
  webhook/metricpipeline/v1beta1/defaulter_test.go
  webhook/metricpipeline/v1beta1/setup.go
Labels: kind/feature, area/metrics

#2017 chore: update x-net dependency
  go.mod
  go.sum
  internal/tools/go.mod
  internal/tools/go.sum
Labels: area/dependency, kind/chore

#2019 chore: update gh action to proper release versions
  .github/workflows/branch-integration.yml
  .github/workflows/build-image.yml
  .github/workflows/pr-all-checks-passed.yml
  .github/workflows/pr-github-checks.yml
  renovate.json
Labels: area/dependency, kind/chore

#2024 feat: move log body attribute to arributes.log.original
  internal/otelcollector/config/log/agent/receivers.go
  internal/otelcollector/config/log/agent/receivers_test.go
  internal/otelcollector/config/log/agent/testdata/config.yaml
  internal/otelcollector/config/log/agent/testdata/config_compatibility_enabled.yaml
  test/e2e/logs/otel/runtime_input_test.go
Labels: kind/feature, area/logs

#2028 chore: fix refactored fluent-bit tests
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/resources_test.go
  internal/resources/fluentbit/testdata/fluentbit.yaml
Labels: area/tests, kind/chore, area/logs

#2026 docs: fix logs diagram
  docs/user/assets/logs-arch.drawio.svg
Labels: area/documentation, kind/docs

#2027 chore: standardize pod spec creation across components using functional options
  internal/resources/common/pod_spec.go
  internal/resources/common/resources.go
  internal/resources/common/resources_test.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/testdata/fluentbit.yaml
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/core.go
  internal/resources/otelcollector/core_pod_spec.go
  internal/resources/otelcollector/gateway.go
  internal/resources/otelcollector/testdata/log-agent.yaml
  internal/resources/selfmonitor/resources.go
Labels: kind/chore, area/logs, area/metrics, area/traces

#2032 feat: add tolerations to DaemonSet pod specs
  internal/resources/common/pod_spec.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/testdata/fluentbit.yaml
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/testdata/log-agent.yaml
  internal/resources/otelcollector/testdata/metric-agent.yaml
Labels: kind/feature, area/logs, area/metrics

#2022 feat: add support to extract trace information from log
  internal/otelcollector/config/log/agent/config.go
  internal/otelcollector/config/log/agent/receivers.go
  internal/otelcollector/config/log/agent/receivers_test.go
  internal/otelcollector/config/log/agent/testdata/config.yaml
  internal/otelcollector/config/log/agent/testdata/config_compatibility_enabled.yaml
  test/e2e/logs/otel/trace_attributes_parser_test.go
  test/testkit/matchers/log/log_otel_matchers.go
  test/testkit/matchers/log/plog_otel_utils.go
  test/testkit/mocks/loggen/log_producer.go
Labels: kind/feature, area/logs

#2036 feat: otlp logs namespace filter
  config/samples/telemetry_v1alpha1_logparser_fluentbit.yaml
  config/samples/telemetry_v1alpha1_logpipeline_fluentbit.yaml
  config/samples/telemetry_v1alpha1_logpipeline_otel_input_application.yaml
  config/samples/telemetry_v1alpha1_logpipeline_otel_input_otlp.yaml
  internal/fluentbit/config/builder/sections_config_builder_test.go
  internal/otelcollector/config/log/gateway/config.go
  internal/otelcollector/config/log/gateway/config_builder.go
  internal/otelcollector/config/log/gateway/config_builder_test.go
  internal/otelcollector/config/log/gateway/processors.go
  internal/otelcollector/config/log/gateway/processors_test.go
  internal/otelcollector/config/log/gateway/service.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/ottlexpr/expressions.go
  internal/otelcollector/config/ottlexpr/expressions_test.go
  internal/reconciler/logpipeline/fluentbit/reconciler_test.go
  internal/utils/test/log_pipeline_builder.go
  internal/utils/test/metric_pipeline_builder.go
  internal/utils/test/pipeline_opts.go
  test/e2e/logs/fluentbit/disabled_input_test.go
  test/e2e/logs/otel/application/basic_test.go
  test/e2e/logs/otel/application/multi_pipeline_namespace_selector_test.go
  test/e2e/logs/otel/application/multi_pipeline_test.go
  test/e2e/logs/otel/application/no_input_test.go
  test/e2e/logs/otel/application/service_name_test.go
  test/e2e/logs/otel/application/suite_test.go
  test/e2e/logs/otel/application/trace_attributes_parser_test.go
  test/e2e/logs/otel/otlp/basic_test.go
  test/e2e/logs/otel/otlp/extract_labels_test.go
  test/e2e/logs/otel/otlp/multi_pipeline_namespace_selector_test.go
  test/e2e/logs/otel/otlp/service_name_test.go
  test/e2e/logs/otel/otlp/suite_test.go
Labels: kind/feature, area/logs

#2038 chore: bump OTel image version to 0.123.0
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
  test/testkit/images.go
Labels: area/documentation, kind/chore, area/logs, area/metrics, area/traces, area/manager

#2035 feat: copy time field to @timestamp and change date field format to iso8601
  docs/user/02-logs.md
  internal/fluentbit/config/builder/output.go
  internal/fluentbit/config/builder/output_test.go
  internal/fluentbit/config/builder/sections_config_builder.go
  internal/fluentbit/config/builder/sections_config_builder_test.go
  test/e2e/logs/fluentbit/modify_timestamp_date_format_test.go
  test/testkit/matchers/log/log_fluentbit_matchers.go
  test/testkit/matchers/log/log_fluentbit_matchers_test.go
Labels: kind/feature, area/documentation, area/logs

#2042 chore: update to k8s 1.31 and test preview of 1.32
  .env
  .github/workflows/branch-integration.yml
  .k3d-kyma.yaml
  Makefile
  hack/make/provision.mk
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: area/ci, kind/chore

#2057 chore: prepare release 1.38
  .env
  config/manager/kustomization.yaml
  internal/images/images.go
  main.go
  sec-scanners-config.yaml
Labels: kind/chore, area/release

#2063 docs: restore kyma cluster and reduce line jumps
  docs/user/assets/logs-arch.drawio.svg
Labels: area/documentation, kind/docs

#2060 fix: switch bufferInUse alert to a different metric to contain the pipeline name
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/testdata/fluentbit.yaml
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/fluent_bit_rule_builder.go
  internal/selfmonitor/config/rules.go
  internal/selfmonitor/config/rules_test.go
  internal/selfmonitor/config/testdata/config.yaml
  internal/selfmonitor/config/testdata/rules.yaml
  internal/selfmonitor/config/testdata/rules_compatibility.yaml
  internal/selfmonitor/prober/log_pipeline_prober.go
  internal/selfmonitor/prober/log_pipeline_prober_test.go
  internal/selfmonitor/prober/otel_pipeline_prober_test.go
  internal/selfmonitor/webhook/handler_test.go
  test/e2e/logs/otel/application/basic_test.go
  test/e2e/logs/otel/application/multi_pipeline_namespace_selector_test.go
  test/e2e/logs/otel/application/multi_pipeline_test.go
  test/e2e/logs/otel/application/service_name_test.go
  test/e2e/logs/otel/application/trace_attributes_parser_test.go
  test/e2e/logs/otel/otlp/basic_test.go
  test/e2e/logs/otel/otlp/extract_labels_test.go
  test/e2e/logs/otel/otlp/multi_pipeline_namespace_selector_test.go
  test/e2e/logs/otel/otlp/service_name_test.go
  test/e2e/selfmonitor/logs_fluentbit_healthy_test.go
  test/e2e/selfmonitor/logs_otel_healthy_test.go
  test/testkit/assert/logs.go
Labels: kind/bug, area/manager

#2066 chore: update Fluent Bit image in cache to version 4.0.0
  external-images.yaml
Labels: area/ci, kind/chore

#2037 docs: add docs for dynatrace dashboard integration
  docs/user/integration/dynatrace/README.md
  docs/user/integration/dynatrace/telemetry-resource-metrics.json
Labels: area/documentation, kind/docs

#2056 chore: add k3s to image sync
  external-images.yaml
Labels: area/ci, kind/chore

#2064 chore: bump OTel version to 0.124.0
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
  test/testkit/images.go
Labels: area/documentation, kind/chore, area/metrics, area/traces

#2068 docs: e2e test restructuring ADR
  .gitignore
  docs/contributor/arch/020-redesign-e2e-log-test-structure.md
  docs/contributor/pocs/ginkgo-to-go-testing/_service_name_enrichment_test.go
  docs/contributor/pocs/ginkgo-to-go-testing/ginkgo-to-go-testing.md
Labels: area/documentation, kind/docs

#2072 chore: prepare suite pkg for vanilla go tests
  test/testkit/suite/suite.go
Labels: area/tests, kind/chore

#2067 feat: add support for include/exlcude containers
  internal/otelcollector/config/log/agent/config_builder.go
  internal/otelcollector/config/log/agent/config_builder_test.go
  internal/otelcollector/config/log/agent/receivers.go
  internal/otelcollector/config/log/agent/receivers_test.go
  internal/otelcollector/config/log/agent/testdata/config.yaml
  internal/otelcollector/config/log/agent/testdata/config_compatibility_enabled.yaml
  test/e2e/logs/otel/application/exclude_container_test.go
  test/e2e/logs/otel/application/include_container_test.go
Labels: kind/feature, area/logs

#2074 chore: update Fluent Bit image in cache to version 4.0.1
  external-images.yaml
Labels: area/ci, kind/chore

#2078 chore: bump fluent bit image version to 4.0.1
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
Labels: kind/chore, area/logs

#2079 chore: use synced image for k3s
  .env
  Makefile
  hack/make/provision.mk
Labels: area/ci, kind/chore

#2081 chore: update to newest k3d patch version in image cache
  external-images.yaml
Labels: area/ci, kind/chore

#2082 chore: update to newest k3d patch version
  .env
Labels: area/ci, kind/chore

#2070 chore: busola alignment
  .github/workflows/pr-integration.yml
  config/busola/logpipeline_busola_extension_cm.yaml
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/busola/telemetry_busola_extension_cm.yaml
  config/busola/tracepipeline_busola_extension_cm.yaml
Labels: area/dependency, kind/chore

#2075 docs: istio access logs new provider load tests documentation
  docs/contributor/benchmarks/assets/istio-access-logs/fault-injection-config.yaml
  docs/contributor/benchmarks/assets/istio-access-logs/istio-telemetry-envoy.yaml
  docs/contributor/benchmarks/assets/istio-access-logs/istio-telemetry-kyma-logs.yaml
  docs/contributor/benchmarks/assets/istio-access-logs/load-test.yaml
  docs/contributor/benchmarks/assets/istio-access-logs/load_test_setup.drawio.svg
  docs/contributor/benchmarks/assets/istio-access-logs/prom-values.yaml
  docs/contributor/benchmarks/istio-access-logs-otlp-provider.md
Labels: area/documentation, kind/docs

#2085 chore: prepare images for 1.39.0 release
  .env
  config/manager/kustomization.yaml
  internal/images/images.go
  main.go
  sec-scanners-config.yaml
Labels: kind/chore, area/release
