Repository kyma-project/telemetry-manager, pull requests merged in 2025-08, with the labels that each got.

#2335 docs: unstructured log parsing ADR
  docs/contributor/arch/022-switch-metric-pipeline-gateway-to-agent.md
  docs/contributor/arch/023-unstructured-log-parsing.md
Labels: area/logs, kind/docs

#2338 chore: update adr status
  docs/contributor/arch/001-otel-collector-metric-based-pipeline-status.md
  docs/contributor/arch/002-fluent-bit-without-file-system-buffer.md
  docs/contributor/arch/003-integrate-prometheus-with-telemetry-manager-using-alerting.md
  docs/contributor/arch/004-consolidate-pipeline-statuses.md
  docs/contributor/arch/005-do-not-make-prometheus-part of-the-istio-service-mesh.md
  docs/contributor/arch/006-telemetry-api-v1beta1.md
  docs/contributor/arch/007-log-pipeline-otlp-output.md
  docs/contributor/arch/008-telemetry-flow-healthiness-status-api.md
  docs/contributor/arch/009-makefile-architecture.md
  docs/contributor/arch/010-logging-flow-healthiness-status-api.md
  docs/contributor/arch/011-kymastatsmetrics.md
  docs/contributor/arch/012a-leader-receiver-creator.md
  docs/contributor/arch/012b-leader-receiver-creator-as-extension.md
  docs/contributor/arch/013-resource-attributes-enrichment-for-non-workload-metrics.md
  docs/contributor/arch/014-telemetry-self-monitor-storage.md
  docs/contributor/arch/015-impact-of-istio-prometheus-merge-on-metric-pipelines.md
  docs/contributor/arch/016-transform-filter-support-for-telemetry-pipelines.md
  docs/contributor/arch/016a-strategy-for-supported-ottl-functions.md
  docs/contributor/arch/017-fault-tolerant-otel-logging-setup.md
  docs/contributor/arch/018-otel-logging-agent-configuration.md
  docs/contributor/arch/019-switch-from-gateways-to-a-central-agent.md
  docs/contributor/arch/020-redesign-e2e-log-test-structure.md
  docs/contributor/arch/021-refactor-performance-tests.md
  docs/contributor/arch/022-switch-metric-pipeline-gateway-to-agent.md
  docs/contributor/arch/023-unstructured-log-parsing.md
  docs/contributor/arch/024-dynatrace-cummulative-to-delta-support.md
Labels: area/documentation, kind/chore

#2350 docs: update prometheus example to upstream helm changes
  docs/user/integration/prometheus/values.yaml
Labels: area/documentation, kind/docs

#2351 chore: remove experimental image from scanner config
  dependencies/populateimages/main.go
  sec-scanners-config.yaml
Labels: area/ci, kind/chore

#2356 chore: remove ginkgo dependency
  .github/workflows/gardener-integration.yml
  .golangci.yaml
  Makefile
  docs/contributor/development.md
  go.mod
  go.sum
  internal/tools/go.mod
  internal/tools/tools.go
  test/e2e/logs/agent/main_test.go
  test/e2e/logs/fluentbit/main_test.go
  test/e2e/logs/misc/main_test.go
  test/e2e/logs/shared/main_test.go
  test/e2e/metrics/cloud_provider_attributes_test.go
  test/e2e/metrics/main_test.go
  test/e2e/misc/main_test.go
  test/e2e/traces/main_test.go
  test/e2e/upgrade/main_test.go
  test/integration/istio/access_logs_otlp_test.go
  test/integration/istio/access_logs_test.go
  test/integration/istio/main_test.go
  test/integration/istio/metrics_istio_envoy_multi_pipeline_test.go
  test/integration/istio/metrics_istio_input_envoy_metrics_test.go
  test/integration/istio/metrics_istio_input_test.go
  test/integration/istio/metrics_otlp_input_test.go
  test/integration/istio/metrics_prometheus_input_test.go
  test/integration/istio/traces_istio_routing_test.go
  test/selfmonitor/main_test.go
  test/testkit/assert/logs.go
  test/testkit/assert/metrics.go
  test/testkit/assert/traces.go
  test/testkit/matchers/log/fluentbit/log_matchers_test.go
  test/testkit/matchers/log/fluentbit/suite_test.go
  test/testkit/matchers/log/log_matchers_test.go
  test/testkit/matchers/log/suite_test.go
  test/testkit/matchers/metric/metric_matchers_test.go
  test/testkit/matchers/metric/suite_test.go
  test/testkit/matchers/prometheus/prometheus_matcher_test.go
  test/testkit/matchers/prometheus/suite_test.go
  test/testkit/matchers/trace/suite_test.go
  test/testkit/matchers/trace/trace_matchers_test.go
  test/testkit/suite/suite.go
  test/testkit/testing.go
Labels: area/tests, kind/chore

#2347 chore: add proposal for privilege changes to log-agent
  docs/contributor/arch/025-minimal-privileges-for-log-agent.md
Labels: area/documentation, kind/chore

#2357 chore: improve stdout log generator
  dependencies/stdout-log-generator/main.go
  docs/contributor/pocs/sleep-tester/Dockerfile
  docs/contributor/pocs/sleep-tester/go.mod
  docs/contributor/pocs/sleep-tester/go.sum
  docs/contributor/pocs/sleep-tester/main.go
  docs/contributor/pocs/sleep-tester/sleep-tester.md
  docs/contributor/pocs/sleep-tester/sleep-tester.yaml
Labels: kind/chore, area/logs

#2358 docs: redesign of aws integration guide
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/integration/README.md
  docs/user/integration/assets/cloudwatch.drawio.svg
  docs/user/integration/assets/dynatrace.drawio.svg
  docs/user/integration/assets/sap-cloud-logging.drawio.svg
  docs/user/integration/aws-cloudwatch/README.md
  docs/user/integration/aws-cloudwatch/aws-otel.yaml
  docs/user/integration/aws-cloudwatch/values.yaml
Labels: area/documentation, kind/docs

#2372 fix: add log OTLP push endpoint to telemetry status
  apis/operator/v1alpha1/telemetry_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_telemetries.yaml
  config/development/crd/bases/operator.kyma-project.io_telemetries.yaml
  docs/user/gateways.md
  docs/user/resources/01-telemetry.md
  internal/reconciler/telemetry/reconciler.go
  internal/reconciler/telemetry/status.go
  internal/reconciler/telemetry/status_test.go
  internal/utils/test/service_builder.go
  main.go
  test/e2e/misc/telemetry_test.go
Labels: kind/bug, area/logs

#2375 feat: ottl transform
  Makefile
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1alpha1/metricpipeline_types.go
  apis/telemetry/v1alpha1/shared_types.go
  apis/telemetry/v1alpha1/tracepipeline_types.go
  apis/telemetry/v1alpha1/zz_generated.deepcopy.go
  apis/telemetry/v1beta1/logpipeline_types.go
  apis/telemetry/v1beta1/metricpipeline_types.go
  apis/telemetry/v1beta1/shared_types.go
  apis/telemetry/v1beta1/tracepipeline_types.go
  apis/telemetry/v1beta1/zz_generated.deepcopy.go
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_metricpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_tracepipelines.yaml
  internal/otelcollector/config/log/agent/config.go
  internal/otelcollector/config/log/agent/config_builder.go
  internal/otelcollector/config/log/agent/config_builder_test.go
  internal/otelcollector/config/log/agent/processors.go
  internal/otelcollector/config/log/agent/service.go
  internal/otelcollector/config/log/agent/testdata/single-pipeline.yaml
  internal/otelcollector/config/log/agent/testdata/two-pipelines-with-transforms.yaml
  internal/otelcollector/config/log/config.go
  internal/otelcollector/config/log/gateway/config.go
  internal/otelcollector/config/log/gateway/config_builder.go
  internal/otelcollector/config/log/gateway/config_builder_test.go
  internal/otelcollector/config/log/gateway/processors.go
  internal/otelcollector/config/log/gateway/processors_test.go
  internal/otelcollector/config/log/gateway/service.go
  internal/otelcollector/config/log/gateway/testdata/single-pipeline.yaml
  internal/otelcollector/config/log/gateway/testdata/two-pipelines-with-transforms.yaml
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/processors.go
  internal/otelcollector/config/metric/agent/processors_test.go
  internal/otelcollector/config/metric/config.go
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/metric/gateway/processors_test.go
  internal/otelcollector/config/metric/gateway/service.go
  internal/otelcollector/config/metric/gateway/testdata/single-pipeline-otlp-disabled.yaml
  internal/otelcollector/config/metric/gateway/testdata/single-pipeline.yaml
  internal/otelcollector/config/metric/gateway/testdata/two-pipelines-with-transforms.yaml
  internal/otelcollector/config/metric/set_instrumentation_scope_test.go
  internal/otelcollector/config/metric/set_instrumention_scope.go
  internal/otelcollector/config/processors.go
  internal/otelcollector/config/trace/gateway/config.go
  internal/otelcollector/config/trace/gateway/config_builder.go
  internal/otelcollector/config/trace/gateway/config_builder_test.go
  internal/otelcollector/config/trace/gateway/processors.go
  internal/otelcollector/config/trace/gateway/service.go
  internal/otelcollector/config/trace/gateway/testdata/single-pipeline.yaml
  internal/otelcollector/config/trace/gateway/testdata/two-pipelines-with-transforms.yaml
  internal/utils/test/log_pipeline_builder.go
  internal/utils/test/metric_pipeline_builder.go
  internal/utils/test/trace_pipeline_builder.go
Labels: kind/feature, area/logs, area/metrics, area/traces

#2386 chore: adjust the link in the ADR 21
  docs/contributor/arch/021-refactor-performance-tests.md
Labels: area/documentation, kind/chore

#2384 fix: harden OTel log agent securityContext
  internal/otelcollector/config/log/agent/config.go
  internal/otelcollector/config/log/agent/extension.go
  internal/otelcollector/config/log/agent/extension_test.go
  internal/otelcollector/config/log/agent/testdata/single-pipeline.yaml
  internal/otelcollector/config/log/agent/testdata/two-pipelines-with-transforms.yaml
  internal/resources/common/pod_spec.go
  internal/resources/otelcollector/agent.go
  internal/resources/otelcollector/core_pod_spec.go
  internal/resources/otelcollector/testdata/log-agent.yaml
Labels: kind/bug, area/logs

#2391 chore: improve several aspects in integration tests
  .github/workflows/gardener-integration.yml
  docs/user/integration/opentelemetry-demo/values.yaml
  hack/deploy-istio.sh
Labels: area/ci, kind/chore

#2394 chore: include external images in renovate
  renovate.json
Labels: area/ci, kind/chore

#2399 chore: renovate.json was invalid
  docs/contributor/arch/021-refactor-performance-tests.md
  renovate.json
Labels: area/ci, kind/chore

#2354 chore: customize busola config
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1beta1/logpipeline_types.go
  config/busola/logpipeline_busola_extension_cm.yaml
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/busola/tracepipeline_busola_extension_cm.yaml
  config/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
  docs/user/resources/02-logpipeline.md
Labels: area/dependency, kind/chore

#2420 chore: bump images for release 1.46.0
  .env
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  sec-scanners-config.yaml
  test/testkit/images.go
Labels: kind/chore, area/release

#2408 chore: refactor Trace Gateway config builder
  internal/otelcollector/config/common/config_builders.go
  internal/otelcollector/config/common/constants.go
  internal/otelcollector/config/logagent/config_builder.go
  internal/otelcollector/config/loggateway/config_builder.go
  internal/otelcollector/config/metricagent/config_builder.go
  internal/otelcollector/config/metricgateway/config_builder.go
  internal/otelcollector/config/tracegateway/config.go
  internal/otelcollector/config/tracegateway/config_builder.go
  internal/otelcollector/config/tracegateway/config_builder_test.go
  internal/otelcollector/config/tracegateway/processors.go
  internal/otelcollector/config/tracegateway/processors_test.go
  internal/otelcollector/config/tracegateway/service.go
  internal/otelcollector/config/tracegateway/testdata/single-pipeline.yaml
  internal/otelcollector/config/tracegateway/testdata/two-pipelines-with-transforms.yaml
  internal/otelcollector/config/tracegateway/types.go
Labels: kind/chore, area/traces

#2422 fix: conversion of LogPipelines
  apis/telemetry/v1alpha1/logpipeline_conversion.go
  apis/telemetry/v1alpha1/logpipeline_conversion_test.go
Labels: kind/bug, area/logs

#2423 docs: fix broken fluent bit links
  docs/user/02-logs.md
Labels: area/documentation, kind/docs

#2426 chore: update fluentbit image in cache to 4.0.8
  external-images.yaml
Labels: kind/chore, area/logs

#2438 chore: refactor Metric Gateway config builder
  internal/otelcollector/config/common/component_builder.go
  internal/otelcollector/config/common/constants.go
  internal/otelcollector/config/common/types.go
  internal/otelcollector/config/logagent/config_builder.go
  internal/otelcollector/config/metricagent/config_builder.go
  internal/otelcollector/config/metricgateway/config.go
  internal/otelcollector/config/metricgateway/config_builder.go
  internal/otelcollector/config/metricgateway/config_builder_enrichment.go
  internal/otelcollector/config/metricgateway/config_builder_input.go
  internal/otelcollector/config/metricgateway/config_builder_output.go
  internal/otelcollector/config/metricgateway/config_builder_test.go
  internal/otelcollector/config/metricgateway/connectors.go
  internal/otelcollector/config/metricgateway/connectors_test.go
  internal/otelcollector/config/metricgateway/processor_drop_filter.go
  internal/otelcollector/config/metricgateway/processor_drop_filter_test.go
  internal/otelcollector/config/metricgateway/processors.go
  internal/otelcollector/config/metricgateway/processors_test.go
  internal/otelcollector/config/metricgateway/receivers.go
  internal/otelcollector/config/metricgateway/receivers_test.go
  internal/otelcollector/config/metricgateway/service.go
  internal/otelcollector/config/metricgateway/service_test.go
  internal/otelcollector/config/metricgateway/testdata/istio-diagnostic.yaml
  internal/otelcollector/config/metricgateway/testdata/istio-envoy.yaml
  internal/otelcollector/config/metricgateway/testdata/istio-namespace-filters.yaml
  internal/otelcollector/config/metricgateway/testdata/multiple-inputs-mixed.yaml
  internal/otelcollector/config/metricgateway/testdata/otlp-disabled.yaml
  internal/otelcollector/config/metricgateway/testdata/otlp-namespace-filters.yaml
  internal/otelcollector/config/metricgateway/testdata/otlp-only.yaml
  internal/otelcollector/config/metricgateway/testdata/prometheus-diagnostic.yaml
  internal/otelcollector/config/metricgateway/testdata/prometheus-namespace-filters.yaml
  internal/otelcollector/config/metricgateway/testdata/runtime-namespace-filters.yaml
  internal/otelcollector/config/metricgateway/testdata/runtime-resources-all-disabled.yaml
  internal/otelcollector/config/metricgateway/testdata/runtime-resources-some-disabled.yaml
  internal/otelcollector/config/metricgateway/testdata/setup-comprehensive.yaml
  internal/otelcollector/config/metricgateway/testdata/setup-simple.yaml
  internal/otelcollector/config/metricgateway/testdata/user-defined-transforms.yaml
  internal/otelcollector/config/metricgateway/types.go
  internal/reconciler/metricpipeline/mocks/gateway_config_builder.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
Labels: kind/chore, area/metrics

#2432 chore: add e2e tests for transform processor
  test/e2e/logs/shared/transform_test.go
  test/e2e/logs/shared/transform_test_infer_context_test.go
  test/e2e/logs/shared/transform_test_transform_cond_test.go
  test/e2e/metrics/transform_test.go
  test/e2e/metrics/transform_test_cond_statement_test.go
  test/e2e/metrics/transform_test_infer_context_test.go
  test/e2e/traces/transform_test.go
  test/e2e/traces/transform_test_cond_statement_test.go
  test/e2e/traces/transform_test_infer_context_test.go
  test/testkit/matchers/metric/metric_matchers.go
Labels: area/tests, kind/chore

#2418 chore: introduce gotestsum, JUnit reports, and refactor GHAs accordingly
  .github/template/deploy-test-k8s-prerequisites/action.yaml
  .github/template/test-cleanup/action.yaml
  .github/template/test-execute/action.yaml
  .github/template/test-setup/action.yaml
  .github/template/test-summary/action.yaml
  .github/workflows/gardener-integration.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-upgrade.yml
  Makefile
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
Labels: area/tests, kind/chore

#2444 chore: refactor Metric Agent config builder
  internal/otelcollector/config/common/constants.go
  internal/otelcollector/config/metricagent/config_builder.go
  internal/otelcollector/config/metricagent/config_builder_test.go
  internal/otelcollector/config/metricagent/kubeletstats_receivers.go
  internal/otelcollector/config/metricagent/kubeletstats_receivers_test.go
  internal/otelcollector/config/metricagent/processors.go
  internal/otelcollector/config/metricagent/processors_test.go
  internal/otelcollector/config/metricagent/prometheus_receiver_test.go
  internal/otelcollector/config/metricagent/service.go
  internal/otelcollector/config/metricagent/testdata/istio-envoy.yaml
  internal/otelcollector/config/metricagent/testdata/istio-only.yaml
  internal/otelcollector/config/metricagent/testdata/istio-ops-disabled.yaml
  internal/otelcollector/config/metricagent/testdata/istio-ops-enabled.yaml
  internal/otelcollector/config/metricagent/testdata/prometheus-only.yaml
  internal/otelcollector/config/metricagent/testdata/runtime-only.yaml
  internal/otelcollector/config/metricagent/testdata/runtime-resources-all-enabled.yaml
  internal/otelcollector/config/metricagent/testdata/runtime-resources-some-disabled.yaml
  internal/otelcollector/config/metricagent/testdata/setup-comprehensive.yaml
  internal/otelcollector/config/metricagent/types.go
  internal/reconciler/metricpipeline/mocks/agent_config_builder.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
Labels: kind/chore, area/metrics

#2449 feat: bump OTel version to 0.133.0
  .env
  docs/contributor/benchmarks/results/metrics.md
  docs/contributor/benchmarks/results/traces.md
  helm/telemetry-module/values.yaml
  sec-scanners-config.yaml
  test/testkit/images.go
Labels: kind/feature, area/documentation, area/logs, area/metrics, area/traces

#2451 fix: the namespace filter for log agent
  internal/otelcollector/config/logagent/config_builder.go
  internal/otelcollector/config/logagent/config_builder_test.go
  internal/otelcollector/config/logagent/filelog_receiver.go
  internal/otelcollector/config/logagent/filelog_reciever_test.go
  internal/otelcollector/config/logagent/testdata/single-pipeline-namespace-excluded.yaml
  internal/otelcollector/config/logagent/testdata/single-pipeline-namespace-included.yaml
  internal/otelcollector/config/logagent/testdata/single-pipeline.yaml
  internal/otelcollector/config/logagent/testdata/two-pipelines-with-transforms.yaml
Labels: kind/bug, area/logs

#2448 chore: introduce ComponentBuilder[T]
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/metricpipeline_controller.go
  internal/otelcollector/config/common/component_builder.go
  internal/otelcollector/config/common/component_builder_test.go
  internal/otelcollector/config/common/config_builder.go
  internal/otelcollector/config/common/config_builder_test.go
  internal/otelcollector/config/common/config_builders.go
  internal/otelcollector/config/common/constants.go
  internal/otelcollector/config/common/otlpexporter_config_builder_test.go
  internal/otelcollector/config/common/types.go
  internal/otelcollector/config/logagent/config_builder.go
  internal/otelcollector/config/logagent/config_builder_test.go
  internal/otelcollector/config/logagent/testdata/single-pipeline-namespace-excluded.yaml
  internal/otelcollector/config/logagent/testdata/single-pipeline-namespace-included.yaml
  internal/otelcollector/config/logagent/testdata/single-pipeline.yaml
  internal/otelcollector/config/logagent/testdata/two-pipelines-with-transforms.yaml
  internal/otelcollector/config/loggateway/config_builder.go
  internal/otelcollector/config/loggateway/config_builder_test.go
  internal/otelcollector/config/metricagent/config_builder.go
  internal/otelcollector/config/metricagent/config_builder_test.go
  internal/otelcollector/config/metricagent/kubeletstats_receivers_test.go
  internal/otelcollector/config/metricagent/prometheus_receiver_test.go
  internal/otelcollector/config/metricagent/testdata/istio-envoy.yaml
  internal/otelcollector/config/metricagent/testdata/istio-only.yaml
  internal/otelcollector/config/metricagent/testdata/istio-ops-disabled.yaml
  internal/otelcollector/config/metricagent/testdata/istio-ops-enabled.yaml
  internal/otelcollector/config/metricagent/testdata/prometheus-only.yaml
  internal/otelcollector/config/metricagent/testdata/runtime-only.yaml
  internal/otelcollector/config/metricagent/testdata/runtime-resources-all-enabled.yaml
  internal/otelcollector/config/metricagent/testdata/runtime-resources-some-disabled.yaml
  internal/otelcollector/config/metricagent/testdata/setup-comprehensive.yaml
  internal/otelcollector/config/metricgateway/config_builder.go
  internal/otelcollector/config/metricgateway/config_builder_enrichment.go
  internal/otelcollector/config/metricgateway/config_builder_input.go
  internal/otelcollector/config/metricgateway/config_builder_output.go
  internal/otelcollector/config/metricgateway/config_builder_test.go
  internal/otelcollector/config/metricgateway/testdata/istio-diagnostic.yaml
  internal/otelcollector/config/metricgateway/testdata/istio-envoy.yaml
  internal/otelcollector/config/metricgateway/testdata/istio-namespace-filters.yaml
  internal/otelcollector/config/metricgateway/testdata/multiple-inputs-mixed.yaml
  internal/otelcollector/config/metricgateway/testdata/otlp-disabled.yaml
  internal/otelcollector/config/metricgateway/testdata/otlp-namespace-filters.yaml
  internal/otelcollector/config/metricgateway/testdata/otlp-only.yaml
  internal/otelcollector/config/metricgateway/testdata/prometheus-diagnostic.yaml
  internal/otelcollector/config/metricgateway/testdata/prometheus-namespace-filters.yaml
  internal/otelcollector/config/metricgateway/testdata/runtime-namespace-filters.yaml
  internal/otelcollector/config/metricgateway/testdata/runtime-resources-all-disabled.yaml
  internal/otelcollector/config/metricgateway/testdata/runtime-resources-some-disabled.yaml
  internal/otelcollector/config/metricgateway/testdata/setup-comprehensive.yaml
  internal/otelcollector/config/metricgateway/testdata/setup-simple.yaml
  internal/otelcollector/config/metricgateway/testdata/user-defined-transforms.yaml
  internal/otelcollector/config/tracegateway/config_builder.go
  internal/otelcollector/config/tracegateway/config_builder_test.go
Labels: kind/chore, area/logs, area/metrics, area/traces
