Repository kyma-project/telemetry-manager, pull requests merged in 2025-05, with the labels that each got.

#2088 docs: improve benchmarking results for istio access logs (new provider)
  docs/contributor/benchmarks/assets/istio-access-logs/istio-config.yaml
  docs/contributor/benchmarks/istio-access-logs-otlp-provider.md
Labels: area/documentation, kind/docs

#2103 fix: corrected exclude pattern in fluentbit for log agent log exclude
  internal/fluentbit/config/builder/input.go
  internal/fluentbit/config/builder/input_test.go
  internal/fluentbit/config/builder/sections_config_builder_test.go
  internal/otelcollector/config/log/agent/config_builder_test.go
  internal/otelcollector/config/log/agent/receivers.go
  internal/otelcollector/config/log/agent/receivers_test.go
  internal/otelcollector/config/log/agent/testdata/config.yaml
  internal/otelcollector/config/log/agent/testdata/config_compatibility_enabled.yaml
Labels: kind/bug, area/logs

#2107 chore: bump directory-size-exporter
  .env
  internal/images/images.go
  sec-scanners-config.yaml
Labels: area/dependency, kind/chore

#2098 chore: otlp cls performance analysis
  docs/contributor/benchmarks/assets/otel-input.yaml
  docs/contributor/benchmarks/assets/telemetry-gen-direct-to-cls.yml
  docs/contributor/benchmarks/assets/telemetry-gen-using-log-pipeline.yaml
  docs/contributor/benchmarks/cls-performance.md
Labels: area/documentation, kind/chore, area/logs

#2091 chore: move endpoint status to status panel
  config/busola/logpipeline_busola_extension_cm.yaml
  config/busola/metricpipeline_busola_extension_cm.yaml
  config/busola/telemetry_busola_extension_cm.yaml
  config/busola/tracepipeline_busola_extension_cm.yaml
Labels: area/dependency, kind/chore

#2114 chore: configure permissions for all gh actions
  .github/template/finalize-test/action.yaml
  .github/template/setup-golang/action.yaml
  .github/workflows/branch-integration.yml
  .github/workflows/build-image.yml
  .github/workflows/build-sample-app-image.yml
  .github/workflows/build-telemetry-self-monitor-image.yml
  .github/workflows/periodic-github-checks.yml
  .github/workflows/pr-all-checks-passed.yml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-github-checks.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-loadtest.yml
  .github/workflows/pr-release.yml
  .github/workflows/pr-upgrade.yml
  .github/workflows/sync-external-images.yml
  .github/workflows/tag-release.yml
Labels: area/ci, kind/chore

#2116 chore: fix permissions for all gh actions
  .github/workflows/build-image.yml
  .github/workflows/build-sample-app-image.yml
  .github/workflows/build-telemetry-self-monitor-image.yml
  .github/workflows/pr-all-checks-passed.yml
  .github/workflows/pr-github-checks.yml
  .github/workflows/sync-external-images.yml
Labels: area/ci, kind/chore

#2115 fix: prevent cross-usage of fluentbit and otlp features
  apis/telemetry/v1alpha1/logpipeline_types.go
  apis/telemetry/v1beta1/logpipeline_types.go
  config/development/crd/bases/telemetry.kyma-project.io_logpipelines.yaml
Labels: kind/bug, area/logs

#2122 docs: use latest otel-collector version in dynatrace integration guide
  docs/user/integration/dynatrace/exporter-values.yaml
Labels: area/documentation, kind/docs

#2117 fix: move body only if it is json
  internal/otelcollector/config/log/agent/receivers.go
  internal/otelcollector/config/log/agent/receivers_test.go
  internal/otelcollector/config/log/agent/testdata/config.yaml
  internal/otelcollector/config/log/agent/testdata/config_compatibility_enabled.yaml
  test/e2e/logs/fluentbit/keep_original_body_test.go
  test/e2e/logs/otel/application/basic_test.go
  test/e2e/logs/otel/application/multi_pipeline_namespace_selector_test.go
  test/e2e/logs/otel/application/payload_parser_test.go
  test/testkit/mocks/loggen/log_producer.go
Labels: kind/bug, area/logs

#2129 chore: update prometheus image in the cache to 3.4.0
  dependencies/telemetry-self-monitor/envs
Labels: kind/chore, area/manager

#2132 docs: improved exclude expressions for dynatrace guide
  docs/user/integration/dynatrace/README.md
Labels: area/documentation, kind/docs

#2130 chore: update to prometheus 3.4.0 in self-monitor
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
Labels: kind/chore, area/manager

#2136 chore: update fluent-bit image in cache to 4.0.2
  external-images.yaml
Labels: kind/chore, area/logs

#2138 feat: update to fluent-bit 4.0.2
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
Labels: kind/feature, area/logs

#2121 feat: apply enrichments to log agent and move configuration to global
  Makefile
  apis/operator/v1alpha1/telemetry_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  config/development/crd/bases/operator.kyma-project.io_telemetries.yaml
  internal/otelcollector/config/metric/gateway/processors.go
  internal/otelcollector/config/processors/k8s_attribute_proc.go
  internal/otelcollector/config/processors/k8s_attribute_proc_test.go
  internal/otelcollector/config/trace/gateway/processors.go
  internal/reconciler/logpipeline/otel/reconciler.go
  test/e2e-migrated/logs/shared/extract_labels_test.go
Labels: kind/feature, area/documentation, area/logs

#2143 chore: add missing test registration and labels
  test/e2e-migrated/logs/shared/keep_original_body_test.go
  test/e2e-migrated/logs/shared/mtls_test.go
  test/e2e-migrated/logs/shared/self_monitor_happy_path_test.go
Labels: area/tests, kind/chore

#2145 chore: improve mock log backend query assertions
  test/e2e-migrated/logs/agent/instrumentation_scope_test.go
  test/e2e-migrated/logs/agent/payload_parser_test.go
  test/e2e-migrated/logs/agent/trace_attributes_parser_test.go
  test/e2e-migrated/logs/fluentbit/custom_filter_test.go
  test/e2e-migrated/logs/fluentbit/custom_output_test.go
  test/e2e-migrated/logs/fluentbit/dedot_test.go
  test/e2e-migrated/logs/fluentbit/keep_annotation_test.go
  test/e2e-migrated/logs/fluentbit/log_parser_test.go
  test/e2e-migrated/logs/fluentbit/modify_timestamp_date_format_test.go
  test/e2e-migrated/logs/shared/check_metrics_endpoint_test.go
  test/e2e-migrated/logs/shared/container_selector_test.go
  test/e2e-migrated/logs/shared/extract_labels_test.go
  test/e2e-migrated/logs/shared/keep_original_body_test.go
  test/e2e-migrated/logs/shared/mtls_about_to_expire_cert_test.go
  test/e2e-migrated/logs/shared/mtls_test.go
  test/e2e-migrated/logs/shared/multi_pipeline_broken_test.go
  test/e2e-migrated/logs/shared/multi_pipeline_fanout_test.go
  test/e2e-migrated/logs/shared/multi_pipeline_max_pipeline_test.go
  test/e2e-migrated/logs/shared/namespace_selector_test.go
  test/e2e-migrated/logs/shared/observed_time_test.go
  test/e2e-migrated/logs/shared/self_monitor_happy_path_test.go
  test/e2e-migrated/logs/shared/service_name_test.go
  test/e2e-migrated/logs/shared/single_pipeline_test.go
  test/e2e-migrated/logs/shared/single_pipeline_v1beta1_test.go
  test/e2e-migrated/upgrade/upgrade_test.go
  test/e2e/logs/fluentbit/upgrade_test.go
  test/e2e/metrics/basic_v1alpha1_test.go
  test/e2e/metrics/basic_v1beta1_test.go
  test/e2e/metrics/runtime_input_test.go
  test/e2e/misc/telemetry_logs_analysis_test.go
  test/e2e/traces/basic_v1alpha1_test.go
  test/e2e/traces/basic_v1beta1_test.go
  test/integration/istio/logs_self_monitor_outage_test.go
  test/integration/istio/metrics_cloud_provider_attributes_test.go
  test/integration/istio/metrics_self_monitor_outage_test.go
  test/integration/istio/traces_self_monitor_outage_test.go
  test/testkit/apiserverproxy/proxy_client.go
  test/testkit/assert/logs.go
  test/testkit/assert/monitoring.go
  test/testkit/assert/shared.go
  test/testkit/mocks/backend/backend.go
  test/testkit/mocks/backend/collector_config_map.go
  test/testkit/mocks/backend/collector_deployment.go
  test/testkit/mocks/backend/fluentd_config_map.go
  test/testkit/mocks/backend/options.go
Labels: area/tests, kind/chore

#2147 chore: separate OTel and FluentBit log matchers
  test/e2e-migrated/logs/agent/instrumentation_scope_test.go
  test/e2e-migrated/logs/agent/payload_parser_test.go
  test/e2e-migrated/logs/agent/trace_attributes_parser_test.go
  test/e2e-migrated/logs/fluentbit/dedot_test.go
  test/e2e-migrated/logs/fluentbit/keep_annotation_test.go
  test/e2e-migrated/logs/fluentbit/log_parser_test.go
  test/e2e-migrated/logs/fluentbit/modify_timestamp_date_format_test.go
  test/e2e-migrated/logs/shared/extract_labels_test.go
  test/e2e-migrated/logs/shared/keep_original_body_test.go
  test/e2e-migrated/logs/shared/observed_time_test.go
  test/e2e-migrated/logs/shared/service_name_test.go
  test/e2e/misc/overrides_test.go
  test/e2e/misc/telemetry_logs_analysis_test.go
  test/integration/istio/access_logs_test.go
  test/testkit/assert/logs.go
  test/testkit/matchers/log/fluentbit/log_matchers.go
  test/testkit/matchers/log/fluentbit/log_matchers_test.go
  test/testkit/matchers/log/fluentbit/plog_utils.go
  test/testkit/matchers/log/fluentbit/suite_test.go
  test/testkit/matchers/log/log_matchers.go
  test/testkit/matchers/log/log_matchers_test.go
  test/testkit/matchers/log/log_otel_matchers.go
  test/testkit/matchers/log/plog_utils.go
  test/testkit/matchers/metric/pmetric_utils.go
  test/testkit/matchers/trace/ptrace_utils.go
Labels: area/tests, kind/chore

#2148 chore: clean unused code
  internal/fluentbit/config/builder/rewritetag_filter.go
  internal/fluentbit/config/builder/rewritetag_filter_test.go
  test/testkit/mocks/backend/backend.go
  test/testkit/mocks/backend/options.go
Labels: area/tests, kind/chore, area/logs

#2149 chore: fix the logic to run tests on experimental
  .github/workflows/pr-integration.yml
Labels: area/tests, kind/chore

#2124 chore: migrate leader election to use upstream leader elector
  internal/otelcollector/config/config.go
  internal/otelcollector/config/metric/agent/config.go
  internal/otelcollector/config/metric/agent/config_builder.go
  internal/otelcollector/config/metric/agent/config_builder_test.go
  internal/otelcollector/config/metric/agent/receivers.go
  internal/otelcollector/config/metric/agent/receivers_test.go
  internal/otelcollector/config/metric/agent/testdata/config_compatibility_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_enabled.yaml
  internal/otelcollector/config/metric/agent/testdata/config_istio_not_enabled.yaml
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/config_builder.go
  internal/otelcollector/config/metric/gateway/config_builder_test.go
  internal/otelcollector/config/metric/gateway/receivers.go
  internal/otelcollector/config/metric/gateway/receivers_test.go
  internal/otelcollector/config/metric/gateway/service.go
  internal/otelcollector/config/metric/gateway/service_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/metric/gateway/testdata/config_compatibility_enabled.yaml
  internal/otelcollector/config/metric/gateway/testdata/config_otlp_disabled.yaml
  internal/resources/otelcollector/rbac.go
Labels: area/dependency, kind/chore

#2154 chore: remove dead links after singleonreceivercreator removed from repo
  docs/contributor/arch/012b-leader-receiver-creator-as-extension.md
Labels: area/documentation, kind/chore

#2140 fix: validation of reconciliable LogPipelines
  controllers/telemetry/logpipeline_controller.go
  internal/otelcollector/config/log/gateway/config.go
  internal/otelcollector/config/log/gateway/config_builder.go
  internal/otelcollector/config/log/gateway/config_builder_test.go
  internal/otelcollector/config/log/gateway/processors.go
  internal/otelcollector/config/log/gateway/processors_test.go
  internal/otelcollector/config/log/gateway/service.go
  internal/reconciler/logpipeline/otel/reconciler.go
  internal/reconciler/logpipeline/otel/reconciler_test.go
  internal/reconciler/logpipeline/otel/status.go
  internal/reconciler/logpipeline/otel/validator.go
  internal/utils/logpipeline/logpipeline.go
  internal/validators/secretref/secret_ref.go
  internal/validators/secretref/secret_ref_test.go
  test/e2e-migrated/logs/shared/disabled_input_test.go
  test/e2e-migrated/logs/shared/endpoint_validation_test.go
  test/e2e-migrated/logs/shared/mtls_about_to_expire_cert_test.go
  test/e2e-migrated/logs/shared/mtls_cert_key_pair_dont_match_test.go
  test/e2e-migrated/logs/shared/mtls_expired_cert_test.go
  test/e2e-migrated/logs/shared/mtls_invalid_ca_test.go
  test/e2e-migrated/logs/shared/mtls_invalid_cert_test.go
  test/e2e-migrated/logs/shared/multi_pipeline_broken_test.go
  test/e2e-migrated/logs/shared/secret_rotation_test.go
Labels: kind/bug, area/tests, area/logs, area/manager

#2151 feat: add app_name for http outputs
  docs/contributor/arch/012b-leader-receiver-creator-as-extension.md
  docs/contributor/benchmarks/README.md
  docs/user/02-logs.md
  internal/fluentbit/config/builder/sections_config_builder.go
  internal/fluentbit/config/builder/sections_config_builder_test.go
  internal/resources/fluentbit/resources.go
  internal/resources/fluentbit/testdata/fluentbit.yaml
  test/e2e-migrated/logs/fluentbit/app_name_test.go
  test/e2e-migrated/logs/fluentbit/base_payload_with_http_test.go
  test/e2e-migrated/logs/fluentbit/custom_output_test.go
  test/e2e-migrated/logs/fluentbit/custom_parser_test.go
  test/e2e-migrated/logs/fluentbit/dedot_test.go
  test/e2e-migrated/logs/fluentbit/keep_annotation_test.go
  test/testkit/matchers/log/fluentbit/log_matchers.go
Labels: kind/feature, area/documentation, area/logs

#2131 feat: add pipelineSyncer to reconcilers
  .mockery.yml
  controllers/telemetry/logpipeline_controller.go
  controllers/telemetry/metricpipeline_controller.go
  controllers/telemetry/tracepipeline_controller.go
  docs/user/03-traces.md
  docs/user/04-metrics.md
  internal/otelcollector/config/trace/gateway/drop_noisy_spans.go
  internal/reconciler/logpipeline/mocks/pipeline_syncer.go
  internal/reconciler/logpipeline/reconciler.go
  internal/reconciler/logpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/mocks/pipeline_syncer.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/tracepipeline/mocks/pipeline_syncer.go
  internal/reconciler/tracepipeline/reconciler.go
  internal/reconciler/tracepipeline/reconciler_test.go
  internal/resourcelock/lock.go
  internal/resourcelock/lock_test.go
  main.go
Labels: kind/feature, area/documentation, area/logs, area/metrics, area/traces

#2161 docs: align phrasing for multiple pipeline support
  docs/user/02-logs.md
Labels: area/documentation, area/logs, kind/docs

#2170 chore: fix upgrade test
  .github/workflows/pr-upgrade.yml
  hack/wait-for-namespaces.sh
  test/e2e-migrated/upgrade/upgrade_test.go
  test/e2e/logs/fluentbit/suite_test.go
  test/e2e/logs/fluentbit/upgrade_test.go
  test/e2e/metrics/basic_v1alpha1_test.go
  test/e2e/traces/basic_v1alpha1_test.go
  test/e2e/traces/noisy_span_filter_test.go
  test/testkit/mocks/backend/backend.go
  test/testkit/mocks/backend/options.go
Labels: area/tests, kind/chore

#2164 chore: fix flaky FluentBit&LogGateway E2E tests
  .github/workflows/pr-integration.yml
  test/e2e-migrated/logs/agent/severity_parser_test.go
  test/e2e-migrated/logs/agent/trace_parser_test.go
  test/e2e-migrated/logs/fluentbit/base_payload_with_http_test.go
  test/e2e-migrated/logs/shared/extract_labels_test.go
  test/e2e-migrated/logs/shared/keep_original_body_test.go
  test/testkit/assert/logs.go
  test/testkit/assert/shared.go
Labels: area/tests, kind/chore

#2156 chore: fix OTLP data truncation problem in E2E tests
  test/testkit/matchers/log/fluentbit/log_matchers.go
  test/testkit/matchers/log/fluentbit/plog_utils.go
  test/testkit/matchers/log/log_matchers.go
  test/testkit/matchers/log/plog_utils.go
  test/testkit/matchers/metric/pmetric_utils.go
  test/testkit/matchers/trace/ptrace_utils.go
  test/testkit/matchers/unmarshal.go
Labels: area/tests, kind/chore

#2173 chore: update to ARM-based self-monitor
  .env
  Dockerfile
  dependencies/telemetry-self-monitor/Dockerfile
  docs/user/integration/sample-app/Dockerfile
  internal/images/images.go
  sec-scanners-config.yaml
Labels: kind/chore, area/manager
