Repository kyma-project/telemetry-manager, pull requests merged in 2025-07, with the labels that each got.

#2249 docs: align with HP doc
  docs/user/logs.md
Labels: area/documentation, area/logs, kind/docs

#2262 docs: remove schemaUrl from sample-app
  docs/user/integration/sample-app/setup.go
Labels: area/documentation, kind/docs

#2268 docs: sample-app: do not have units in the exported prometheus metrics
  docs/user/integration/sample-app/setup.go
Labels: area/documentation, kind/docs

#2260 fix: runtime_input e2e test flakiness
  .github/workflows/pr-integration.yml
  test/e2e-migrated/metrics/runtime_input_test.go
Labels: kind/bug, area/tests, area/metrics

#2263 feat: update to fluent bit 4.0.4
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
Labels: kind/feature, area/manager

#2267 feat: bump otel to 1.129.0
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
  test/testkit/images.go
Labels: kind/feature, area/documentation, area/logs, area/metrics, area/traces

#2283 chore: group otel packages in renovate
  renovate.json
Labels: area/ci, kind/chore

#2285 chore: update prometheus image in cache to 3.5.0
  dependencies/telemetry-self-monitor/envs
Labels: area/dependency, kind/chore

#2287 chore: update to prometheus 3.5.0
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
Labels: area/dependency, kind/chore

#2289 docs: update dynatrace limitations
  docs/user/integration/dynatrace/README.md
  docs/user/integration/dynatrace/exporter-values.yaml
Labels: area/documentation, kind/docs

#2295 chore: solve logs e2e tests backend not reachable flakiness
  test/e2e-migrated/logs/agent/instrumentation_scope_test.go
  test/e2e-migrated/logs/agent/severity_parser_test.go
  test/e2e-migrated/logs/agent/trace_parser_test.go
  test/e2e-migrated/logs/fluentbit/app_name_test.go
  test/e2e-migrated/logs/fluentbit/base_payload_with_http_test.go
  test/e2e-migrated/logs/fluentbit/custom_filter_test.go
  test/e2e-migrated/logs/fluentbit/custom_output_test.go
  test/e2e-migrated/logs/fluentbit/custom_parser_test.go
  test/e2e-migrated/logs/fluentbit/dedot_test.go
  test/e2e-migrated/logs/fluentbit/keep_annotation_test.go
  test/e2e-migrated/logs/shared/container_selector_test.go
  test/e2e-migrated/logs/shared/disabled_input_test.go
  test/e2e-migrated/logs/shared/extract_labels_test.go
  test/e2e-migrated/logs/shared/keep_original_body_test.go
  test/e2e-migrated/logs/shared/mtls_about_to_expire_cert_test.go
  test/e2e-migrated/logs/shared/mtls_test.go
  test/e2e-migrated/logs/shared/multi_pipeline_broken_test.go
  test/e2e-migrated/logs/shared/multi_pipeline_fanout_test.go
  test/e2e-migrated/logs/shared/multi_pipeline_max_pipeline_test.go
  test/e2e-migrated/logs/shared/namespace_selector_test.go
  test/e2e-migrated/logs/shared/observed_time_test.go
  test/e2e-migrated/logs/shared/secret_rotation_test.go
  test/e2e-migrated/logs/shared/self_monitor_happy_path_test.go
  test/e2e-migrated/logs/shared/service_name_test.go
  test/e2e-migrated/logs/shared/single_pipeline_test.go
  test/e2e-migrated/logs/shared/single_pipeline_v1beta1_test.go
  test/e2e-migrated/traces/mtls_about_to_expire_cert_test.go
  test/e2e-migrated/traces/mtls_test.go
  test/e2e-migrated/traces/multi_pipeline_broken_test.go
  test/e2e-migrated/traces/multi_pipeline_fanout_test.go
  test/e2e-migrated/traces/multi_pipeline_max_pipeline_test.go
  test/e2e-migrated/traces/noisy_span_filter_test.go
  test/e2e-migrated/traces/secret_rotation_test.go
  test/e2e-migrated/traces/single_pipeline_test.go
  test/e2e-migrated/traces/single_pipeline_v1beta1_test.go
  test/e2e-migrated/upgrade/traces_upgrade_test.go
  test/e2e/misc/telemetry_logs_analysis_test.go
  test/e2e/selfmonitor/traces_healthy_test.go
  test/e2e/traces/basic_v1alpha1_test.go
  test/testkit/assert/traces.go
Labels: area/tests, kind/chore, area/logs

#2299 chore: delete sample-app from docs dir
  docs/user/integration/sample-app/Dockerfile
  docs/user/integration/sample-app/Gopkg.lock
  docs/user/integration/sample-app/Gopkg.toml
  docs/user/integration/sample-app/Makefile
  docs/user/integration/sample-app/README.md
  docs/user/integration/sample-app/go.mod
  docs/user/integration/sample-app/go.sum
  docs/user/integration/sample-app/main.go
  docs/user/integration/sample-app/setup.go
Labels: area/documentation, kind/chore

#2300 fix: assert backend reachability using helper function everywhere
  .github/workflows/pr-integration.yml
  test/e2e-migrated/logs/shared/self_monitor_healthy_test.go
  test/e2e-migrated/metrics/kyma_input_test.go
  test/e2e-migrated/metrics/self_monitor_healthy_test.go
  test/e2e-migrated/traces/self_monitor_healthy_test.go
  test/e2e/misc/overrides_test.go
  test/e2e/misc/telemetry_logs_analysis_test.go
  test/integration/istio/access_logs_otlp_test.go
  test/integration/istio/access_logs_test.go
  test/integration/istio/logs_agent_self_monitor_backpressure_test.go
  test/integration/istio/logs_agent_self_monitor_outage_test.go
  test/integration/istio/logs_fluentbit_self_monitor_backpressure_test.go
  test/integration/istio/logs_fluentbit_self_monitor_outage_test.go
  test/integration/istio/logs_gateway_self_monitor_backpressure_test.go
  test/integration/istio/logs_gateway_self_monitor_outage_test.go
  test/integration/istio/metrics_istio_envoy_multi_pipeline_test.go
  test/integration/istio/metrics_istio_input_envoy_metrics_test.go
  test/integration/istio/metrics_istio_input_test.go
  test/integration/istio/metrics_otlp_input_test.go
  test/integration/istio/metrics_prometheus_input_test.go
  test/integration/istio/metrics_self_monitor_backpressure_test.go
  test/integration/istio/metrics_self_monitor_outage_test.go
  test/integration/istio/traces_self_monitor_backpressure_test.go
  test/integration/istio/traces_self_monitor_outage_test.go
  test/integration/istio/traces_test.go
  test/testkit/assert/logs.go
  test/testkit/assert/metrics.go
  test/testkit/assert/telemetry.go
  test/testkit/assert/traces.go
Labels: kind/bug, area/tests

#2309 chore: bump images for 1.44.0 release
  .env
  config/manager/kustomization.yaml
  internal/images/images.go
  sec-scanners-config.yaml
Labels: kind/chore, area/release

#2302 feat: bump OTel Collector to 0.130.1
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
  test/testkit/images.go
Labels: kind/feature, area/logs, area/metrics, area/traces

#2304 docs: provide new deep links for CloudLogging integration
  docs/user/integration/sap-cloud-logging/README.md
  docs/user/integration/sap-cloud-logging/kyma-dashboard-configmap.yaml
  docs/user/integration/sap-cloud-logging/kyma-dashboard-http-configmap.yaml
Labels: area/documentation, kind/docs

#2325 chore: fix the server port
  dependencies/sample-app/main.go
Labels: kind/chore, area/metrics

#2327 feat: update to fluent-bit 4.0.5
  .env
  config/manager/manager.yaml
  dependencies/populateimages/main.go
  docs/contributor/benchmarks/README.md
  docs/contributor/releasing.md
  hack/load-tests/run-load-test.sh
  sec-scanners-config.yaml
Labels: kind/feature, area/logs

#2332 chore: fix inconsistent usage of env vars for telemetry manager image
  .env
  .github/workflows/gardener-integration.yml
  .github/workflows/pr-integration.yml
  .github/workflows/pr-loadtest.yml
  .github/workflows/pr-upgrade.yml
  Makefile
  dependencies/populateimages/main.go
  docs/contributor/development.md
  docs/contributor/installation.md
  docs/contributor/pocs/integrate-prometheus-with-telemetry-manager-using-alerting.md
  docs/contributor/releasing.md
  hack/build-image.sh
  hack/release.sh
Labels: area/ci, kind/chore
