Repository kyma-project/telemetry-manager, pull requests merged in 2025-01, with the labels that each got.

#1712 fix: MetricPipeline should not apply input default when the input not enabled explicitly
  webhook/logpipeline/v1alpha1/defaulter.go
  webhook/logpipeline/v1alpha1/defaulter_test.go
  webhook/logpipeline/v1beta1/defaulter.go
  webhook/logpipeline/v1beta1/defaulter_test.go
  webhook/metricpipeline/v1alpha1/defaulter.go
  webhook/metricpipeline/v1alpha1/defaulter_test.go
  webhook/metricpipeline/v1beta1/defaulter.go
  webhook/metricpipeline/v1beta1/defaulter_test.go
Labels: kind/bug, size/L, lgtm, area/metrics, area/manager, cla: yes

#1728 chore: Prepare images for 1.31.0 release
  .env
  docs/contributor/benchmarks/README.md
  go.mod
  go.sum
  internal/images/images.go
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/connectors.go
  internal/otelcollector/config/metric/gateway/connectors_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/metric/gateway/testdata/config_otlp_disabled.yaml
  sec-scanners-config.yaml
  test/testkit/images.go
Labels: lgtm, size/S, kind/chore, cla: yes, area/release

#1722 chore: Update istio to 1.13.0
  .env
Labels: size/XS, area/dependency, kind/chore, cla: yes

#1734 test: check image build for sample app
  docs/user/integration/sample-app/go.mod
  docs/user/integration/sample-app/go.sum
Labels: do-not-merge/work-in-progress, size/S, cla: yes

#1735 fix: Flaky self-monitoring conditions
  internal/selfmonitor/config/config_builder.go
  internal/selfmonitor/config/config_builder_test.go
  internal/selfmonitor/config/expr_builder.go
  internal/selfmonitor/config/fluent_bit_rule_builder.go
  internal/selfmonitor/config/otelcol_rule_builder.go
  internal/selfmonitor/config/rules.go
  internal/selfmonitor/config/rules_test.go
  internal/selfmonitor/config/testdata/rules.yaml
  internal/selfmonitor/prober/log_pipeline_prober.go
  internal/selfmonitor/prober/log_pipeline_prober_test.go
  internal/selfmonitor/prober/otel_pipeline_prober.go
  internal/selfmonitor/prober/otel_pipeline_prober_test.go
  test/e2e/logs_self_monitor_healthy_test.go
  test/e2e/metrics_self_monitor_healthy_test.go
  test/e2e/traces_self_monitor_healthy_test.go
  test/integration/istio/logs_self_monitor_backpressure_test.go
  test/integration/istio/logs_self_monitor_outage_test.go
  test/integration/istio/metrics_self_monitor_backpressure_test.go
  test/integration/istio/metrics_self_monitor_outage_test.go
  test/integration/istio/traces_self_monitor_backpressure_test.go
  test/integration/istio/traces_self_monitor_outage_test.go
  test/testkit/assert/logs.go
Labels: kind/bug, lgtm, size/XL, area/logs, area/metrics, area/traces, cla: yes

#1739 chore: Update to prometheus 3.1.0
  Dockerfile
  dependencies/telemetry-self-monitor/Dockerfile
  dependencies/telemetry-self-monitor/envs
  docs/contributor/benchmarks/README.md
Labels: size/XS, area/dependency, kind/chore, cla: yes

#1733 docs: Integration guide for sample-app
  .github/workflows/build-image.yml
  .github/workflows/build-sample-app-image.yml
  .github/workflows/build-telemetry-self-monitor-image.yml
  config/samples/telemetry_v1alpha1_metricpipeline.yaml
  docs/user/03-traces.md
  docs/user/integration/assets/sample-app.drawio.svg
  docs/user/integration/sample-app/Dockerfile
  docs/user/integration/sample-app/Gopkg.lock
  docs/user/integration/sample-app/Gopkg.toml
  docs/user/integration/sample-app/Makefile
  docs/user/integration/sample-app/README.md
  docs/user/integration/sample-app/deployment/deployment-prometheus.yaml
  docs/user/integration/sample-app/deployment/deployment.yaml
  docs/user/integration/sample-app/go.mod
  docs/user/integration/sample-app/go.sum
  docs/user/integration/sample-app/main.go
  docs/user/integration/sample-app/setup.go
  test/e2e/metrics_multi_pipeline_test.go
  test/e2e/metrics_prometheus_input_test.go
  test/integration/istio/access_logs_test.go
  test/integration/istio/traces_test.go
  test/testkit/matchers/trace/trace_matchers_test.go
  test/testkit/mocks/prommetricgen/metric_producer.go
Labels: lgtm, size/XXL, area/documentation, cla: yes, kind/docs

#1706 docs: Integration guide for prometheus
  docs/user/integration/assets/prometheus.drawio.svg
  docs/user/integration/jaeger/README.md
  docs/user/integration/prometheus/README.md
  docs/user/integration/prometheus/values.yaml
  docs/user/integration/sample-app/README.md
Labels: lgtm, size/XL, area/metrics, cla: yes, kind/docs

#1752 docs: Fixed prometheus guide and aded links to the overview pages
  docs/user/README.md
  docs/user/integration/README.md
  docs/user/integration/prometheus/values.yaml
Labels: lgtm, area/documentation, size/S, cla: yes, kind/docs

#1756 docs: Add new guides to sidebar
  docs/user/_sidebar.md
Labels: lgtm, size/XS, area/documentation, cla: yes, kind/docs

#1745 test: Fix flaky self-monitoring test
  internal/selfmonitor/config/expr_builder.go
  internal/selfmonitor/config/fluent_bit_rule_builder.go
  internal/selfmonitor/config/testdata/rules.yaml
  test/integration/istio/logs_self_monitor_backpressure_test.go
  test/testkit/assert/logs.go
Labels: area/tests, kind/flaky-test, size/S, cla: yes

#1757 chore: Add renovate for updating istio dependency
  renovate.json
Labels: lgtm, size/M, area/dependency, kind/chore, cla: yes

#1736 chore: Add FluentBit Load Test records/sec columns and re-add generators limits
  .github/workflows/pr-loadtest.yml
  hack/load-tests/convert-results.py
  hack/load-tests/log-fluentbit-test-setup.yaml
  hack/load-tests/metric-agent-test-setup.yaml
  hack/load-tests/run-load-test.sh
Labels: area/ci, size/S, kind/chore, cla: yes

#1759 chore: Fix security scanner setup
  internal/tools/populateimages/main.go
  sec-scanners-config.yaml
Labels: size/XS, area/ci, kind/chore, cla: yes

#1760 chore: Fix renovate commit message
  renovate.json
Labels: lgtm, size/XS, area/ci, kind/chore, cla: yes

#1762 chore: Update to prometheus 3.1.0
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
Labels: lgtm, size/XS, area/dependency, kind/chore, cla: yes

#1761 docs: Fix checkmarx findings for sample-app
  docs/user/integration/sample-app/main.go
  docs/user/integration/sample-app/setup.go
Labels: lgtm, size/M, area/documentation, cla: yes, kind/docs

#1740 chore: Document Fluentbit 3.2.2 perf results
  docs/contributor/benchmarks/README.md
Labels: area/tests, size/M, kind/chore, cla: yes

#1771 chore: Fix checkmarx and update dependencies in sample-app
  .github/dependabot.yml
  docs/user/integration/sample-app/go.mod
  docs/user/integration/sample-app/go.sum
  docs/user/integration/sample-app/main.go
Labels: size/L, lgtm, kind/chore, area/metrics, cla: yes

#1780 chore: Update fluentbit image to 3.2.4
  external-images.yaml
Labels: size/XS, area/dependency, kind/chore, cla: yes

#1781 feat: Update fluentbit agent to 3.2.4
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/XS, area/logs, cla: yes

#1787 feat: Update to OTel-Collector 0.118.0
  .env
  docs/contributor/benchmarks/README.md
  internal/images/images.go
  internal/otelcollector/config/metric/gateway/config.go
  internal/otelcollector/config/metric/gateway/connectors.go
  internal/otelcollector/config/metric/gateway/connectors_test.go
  internal/otelcollector/config/metric/gateway/testdata/config.yaml
  internal/otelcollector/config/metric/gateway/testdata/config_otlp_disabled.yaml
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, size/S, area/logs, area/metrics, cla: yes

#1705 docs: Validate the LogPipeline OTel Setup and test the performance of the log agent
  docs/contributor/benchmarks/load-test-logs.md
  docs/contributor/benchmarks/otlp-logs-validation.md
  docs/contributor/benchmarks/otlp-logs-validation.yaml
  docs/contributor/pocs/assets/otel-log-agent-values.yaml
  docs/contributor/pocs/assets/otel-log-gateway-values.yaml
  docs/contributor/pocs/assets/otel-logs-values.yaml
  hack/load-tests/log-agent-test-setup-generator.yml
  hack/load-tests/log-agent-test-setup.yaml
  hack/load-tests/log-backpressure-config.yaml
  hack/load-tests/run-load-test.sh
Labels: size/XL, area/logs, cla: yes, kind/docs

#1790 chore: Remove unnecessary kube-rbac-proxy reference
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/rbac/kustomization.yaml
Labels: size/M, area/dependency, kind/chore, cla: yes

#1794 docs: Fix dynatrace links
  docs/user/integration/dynatrace/README.md
Labels: lgtm, area/documentation, size/S, cla: yes, kind/docs

#1776 docs: Update release process documentation
  docs/contributor/releasing.md
Labels: size/XS, cla: yes, area/release, kind/docs
