Repository kyma-project/telemetry-manager, pull requests merged in 2025-09, with the labels that each got.

#2460 chore: bump k3d version in image cache
  external-images.yaml
Labels: area/ci, kind/chore

#2462 chore: update k3d image in cache
  external-images.yaml
Labels: area/ci, kind/chore

#2471 fix: fix metric OTLP output with http protocol
  internal/otelcollector/config/common/otlpexporter_config_builders.go
  internal/otelcollector/config/common/types.go
  internal/otelcollector/config/logagent/config_builder_test.go
  internal/otelcollector/config/logagent/testdata/http-protocol-with-custom-path.yaml
  internal/otelcollector/config/logagent/testdata/http-protocol-without-custom-path.yaml
  internal/otelcollector/config/loggateway/config_builder_test.go
  internal/otelcollector/config/loggateway/testdata/http-protocol-with-custom-path.yaml
  internal/otelcollector/config/loggateway/testdata/http-protocol-without-custom-path.yaml
  internal/otelcollector/config/metricgateway/config_builder_output.go
  internal/otelcollector/config/metricgateway/config_builder_test.go
  internal/otelcollector/config/metricgateway/testdata/http-protocol-with-custom-path.yaml
  internal/otelcollector/config/metricgateway/testdata/http-protocol-without-custom-path.yaml
  internal/otelcollector/config/tracegateway/config_builder_test.go
  internal/otelcollector/config/tracegateway/testdata/http-protocol-with-custom-path.yaml
  internal/otelcollector/config/tracegateway/testdata/http-protocol-without-custom-path.yaml
Labels: kind/bug, area/metrics

#2480 fix: fix metric OTLP output with http protocol (#2471)
  .github/workflows/pr-upgrade.yml
  internal/otelcollector/config/common/otlpexporter_config_builders.go
  internal/otelcollector/config/common/types.go
  internal/otelcollector/config/logagent/config_builder_test.go
  internal/otelcollector/config/logagent/testdata/http-protocol-with-custom-path.yaml
  internal/otelcollector/config/logagent/testdata/http-protocol-without-custom-path.yaml
  internal/otelcollector/config/loggateway/config_builder_test.go
  internal/otelcollector/config/loggateway/testdata/http-protocol-with-custom-path.yaml
  internal/otelcollector/config/loggateway/testdata/http-protocol-without-custom-path.yaml
  internal/otelcollector/config/metricgateway/config_builder_output.go
  internal/otelcollector/config/metricgateway/config_builder_test.go
  internal/otelcollector/config/metricgateway/testdata/http-protocol-with-custom-path.yaml
  internal/otelcollector/config/metricgateway/testdata/http-protocol-without-custom-path.yaml
  internal/otelcollector/config/tracegateway/config_builder_test.go
  internal/otelcollector/config/tracegateway/testdata/http-protocol-with-custom-path.yaml
  internal/otelcollector/config/tracegateway/testdata/http-protocol-without-custom-path.yaml
  test/e2e/upgrade/logs_fluentbit_upgrade_test.go
  test/e2e/upgrade/logs_upgrade_test.go
Labels: kind/bug, area/metrics

#2481 chore: bump images for 1.47.1 release
  .env
  helm/telemetry-module/Chart.yaml
  helm/telemetry-module/values.yaml
  sec-scanners-config.yaml
Labels: kind/chore, area/manager

#2482 docs: fix path in loki integration guide
  docs/user/integration/loki/README.md
Labels: area/documentation, kind/docs

#2486 docs: fixed bad formatted md not valid in Vitepress (markdown-it)
  apis/telemetry/v1alpha1/shared_types.go
  apis/telemetry/v1beta1/shared_types.go
  docs/user/02-logs.md
  docs/user/03-traces.md
  docs/user/04-metrics.md
  docs/user/logs.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
  helm/telemetry-module/charts/experimental/templates/telemetry.kyma-project.io_logpipelines.yaml
  helm/telemetry-module/charts/experimental/templates/telemetry.kyma-project.io_metricpipelines.yaml
  helm/telemetry-module/charts/experimental/templates/telemetry.kyma-project.io_tracepipelines.yaml
  helm/telemetry-module/charts/regular/templates/telemetry.kyma-project.io_logpipelines.yaml
  helm/telemetry-module/charts/regular/templates/telemetry.kyma-project.io_metricpipelines.yaml
  helm/telemetry-module/charts/regular/templates/telemetry.kyma-project.io_tracepipelines.yaml
Labels: area/documentation, kind/docs

#2407 chore: add node network io and error metrics in cls
  CODEOWNERS
  docs/user/integration/sap-cloud-logging/dashboard-nodes.ndjson
Labels: area/dependency, kind/chore

#2475 chore: fix broken doc links after repo restructuring
  docs/user/resources/01-telemetry.md
  docs/user/resources/02-logpipeline.md
  docs/user/resources/03-logparser.md
  docs/user/resources/04-tracepipeline.md
  docs/user/resources/05-metricpipeline.md
Labels: area/documentation, kind/chore

#2500 chore: update fluent bit image in cache to 4.0.9
  external-images.yaml
Labels: area/dependency, kind/chore

#2491 chore: update ADR with new Metric Agent config architecture
  docs/contributor/arch/022-switch-metric-pipeline-gateway-to-agent.md
  docs/contributor/assets/metric-agent-pipelines.png
  docs/contributor/assets/sample-metric-agent-config.yaml
Labels: area/documentation, kind/chore, area/metrics

#2521 chore: bump directory size-exporter
  .env
  helm/values.yaml
  sec-scanners-config.yaml
Labels: area/dependency, kind/chore

#2510 chore: add ADR Filter support without OTTL context inference
  docs/contributor/arch/016b-filter-support-without-context-inference-for-telemetry-pipelines.md
Labels: area/documentation, kind/chore, area/logs, area/metrics, area/traces

#2528 chore: metric agent status
  .github/workflows/pr-integration.yml
  .mockery.yml
  controllers/telemetry/metricpipeline_controller.go
  docs/user/04-metrics.md
  internal/conditions/conditions.go
  internal/reconciler/metricpipeline/mocks/agent_flow_health_prober.go
  internal/reconciler/metricpipeline/mocks/gateway_flow_health_prober.go
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
  internal/reconciler/metricpipeline/status.go
  internal/reconciler/telemetry/metric_components_checker_test.go
  internal/selfmonitor/config/rules.go
  internal/selfmonitor/config/testdata/rules.yaml
  internal/selfmonitor/prober/otel_gateway_prober.go
  test/selfmonitor/backpressure_test.go
  test/selfmonitor/main_test.go
  test/selfmonitor/outage_test.go
  test/testkit/k8s/virtual_service.go
  test/testkit/mocks/backend/backend.go
  test/testkit/mocks/backend/options.go
  test/testkit/mocks/prommetricgen/metric_producer.go
Labels: kind/chore, area/metrics

#2542 fix: metricpipeline reconciliation loop agent deployment
  internal/reconciler/metricpipeline/reconciler.go
  internal/reconciler/metricpipeline/reconciler_test.go
Labels: kind/bug, area/metrics

#2540 feat: bump OTel image version to 0.136.0
  .env
  docs/contributor/assets/sample-metric-agent-config.yaml
  docs/contributor/benchmarks/results/metrics.md
  docs/contributor/benchmarks/results/traces.md
  helm/values.yaml
  internal/otelcollector/config/metricagent/kubeletstats_receivers.go
  internal/otelcollector/config/metricagent/kubeletstats_receivers_test.go
  internal/otelcollector/config/metricagent/testdata/istio-ops-disabled.yaml
  internal/otelcollector/config/metricagent/testdata/istio-ops-enabled.yaml
  internal/otelcollector/config/metricagent/testdata/runtime-only.yaml
  internal/otelcollector/config/metricagent/testdata/runtime-resources-all-enabled.yaml
  internal/otelcollector/config/metricagent/testdata/runtime-resources-some-disabled.yaml
  internal/otelcollector/config/metricagent/testdata/setup-comprehensive.yaml
  internal/otelcollector/config/metricagent/types.go
  sec-scanners-config.yaml
  test/testkit/images.go
Labels: kind/feature, area/documentation, area/logs, area/metrics, area/traces

#2550 chore: fix perf result download in load test setup
  .github/workflows/pr-loadtest.yml
Labels: area/ci, kind/chore

#2556 chore: revert "chore: bump images for telemetry release 1.49.0"
  .env
  helm/Chart.yaml
  helm/charts/default/Chart.yaml
  helm/charts/experimental/Chart.yaml
  helm/values.yaml
  sec-scanners-config.yaml
  test/testkit/images.go
Labels: kind/chore, area/release

#2558 chore: release telemetry manage release 1.49.0
  .env
  helm/Chart.yaml
  helm/charts/default/Chart.yaml
  helm/charts/experimental/Chart.yaml
  helm/values.yaml
  sec-scanners-config.yaml
  test/testkit/images.go
Labels: kind/chore, area/release
